import{mensagemDeFalha}from"@/lib/errors/data-access";
import{createHash}from"node:crypto";
import{NextResponse}from"next/server";
import{requireCapability}from"@/lib/authorization";
import{mitFilename,renderMitJson,type MitDebt,type MitDebtBlock,type MitDebtGroup,type MitDocument,type MitSuspension}from"@/lib/rh/integrations/mit-json";

function digits(v:unknown){return String(v??"").replace(/\D/g,"");}
export async function POST(_request:Request,{params}:{params:Promise<{id:string}>}){
 const{id}=await params;const context=await requireCapability("rh","export");
 const{data:a,error:aError}=await context.supabase.from("rh_mit_apurations").select("*,rh_employers(tax_id)").eq("organization_id",context.organizationId).eq("id",id).maybeSingle();if(aError)return NextResponse.json({error:mensagemDeFalha("api.rh.mit.[id].POST", aError)},{status:400});if(!a)return NextResponse.json({error:"Apuração MIT não encontrada."},{status:404});if(["CANCELLED","SUPERSEDED"].includes(a.status))return NextResponse.json({error:`Apuração ${a.status} não pode ser exportada.`},{status:409});
 const[{data:events,error:eError},{data:debts,error:dError},{data:suspensions,error:sError},{data:suspended,error:sdError}]=await Promise.all([context.supabase.from("rh_mit_special_events").select("event_id,event_day,event_type").eq("organization_id",context.organizationId).eq("apuration_id",id).order("event_id"),context.supabase.from("rh_mit_debts").select("id,group_code,debt_id,after_event,event_id,revenue_code,pa_debito,ano_postergado,trim_postergado,ano_debito,cnpj_estabelecimento,cnpj_incorporacao,cnpj_scp,codigo_municipio_ouro,amount").eq("organization_id",context.organizationId).eq("apuration_id",id).order("debt_id"),context.supabase.from("rh_mit_suspensions").select("id,suspension_type,suspension_reason,with_deposit,process_number,third_party_process,decision_date,court_number,judicial_city_code").eq("organization_id",context.organizationId).eq("apuration_id",id).order("created_at"),context.supabase.from("rh_mit_suspended_debts").select("suspension_id,debt_row_id,amount").eq("organization_id",context.organizationId)]);if(eError||dError||sError||sdError)return NextResponse.json({error:mensagemDeFalha("api.rh.mit.[id].POST", eError)??mensagemDeFalha("api.rh.mit.[id].POST", dError)??mensagemDeFalha("api.rh.mit.[id].POST", sError)??mensagemDeFalha("api.rh.mit.[id].POST", sdError)},{status:400});
 const debtBlocks:MitDocument["Debitos"]={};if(a.balanco_lucro_real!=null)debtBlocks.BalancoLucroReal=Boolean(a.balanco_lucro_real);for(const row of debts??[]){const group=row.group_code as MitDebtGroup;const block=(debtBlocks[group]??={}) as MitDebtBlock;const debt:MitDebt={IdDebito:Number(row.debt_id),CodigoDebito:String(row.revenue_code),ValorDebito:Number(row.amount)};if(row.event_id!=null)debt.IdEventoDebito=Number(row.event_id);if(row.pa_debito!=null)debt.PaDebito=Number(row.pa_debito);if(row.ano_postergado!=null)debt.AnoPostergado=Number(row.ano_postergado);if(row.trim_postergado!=null)debt.TrimPostergado=Number(row.trim_postergado);if(row.ano_debito!=null)debt.AnoDebito=Number(row.ano_debito);if(row.cnpj_estabelecimento)debt.CnpjEstabelecimento=String(row.cnpj_estabelecimento);if(row.cnpj_incorporacao)debt.CnpjIncorporacao=String(row.cnpj_incorporacao);if(row.cnpj_scp)debt.CnpjScp=String(row.cnpj_scp);if(row.codigo_municipio_ouro)debt.CodigoMunicipioOuro=String(row.codigo_municipio_ouro);const key=row.after_event?"ListaDebitosAposEvento":"ListaDebitos";block[key]=[...(block[key]??[]),debt];}
 const susp:MitSuspension[]=(suspensions??[]).map(s=>{const item:MitSuspension={TipoSuspensao:Number(s.suspension_type) as 1|2,NumeroProcesso:String(s.process_number),ListaDebitosSuspensos:(suspended??[]).filter(x=>x.suspension_id===s.id).map(x=>{const debt=(debts??[]).find(d=>d.id===x.debt_row_id);return{IdDebitoSuspenso:Number(debt?.debt_id??0),ValorSuspenso:Number(x.amount)};})};if(s.suspension_reason!=null)item.MotivoSuspensao=Number(s.suspension_reason);if(s.with_deposit!=null)item.ComDeposito=Boolean(s.with_deposit);if(s.third_party_process!=null)item.ProcessoTerceiro=Boolean(s.third_party_process);if(s.decision_date!=null)item.DataDecisao=Number(s.decision_date);if(s.court_number!=null)item.VaraJudiciaria=Number(s.court_number);if(s.judicial_city_code)item.CodigoMunicipioSj=String(s.judicial_city_code);return item;});
 const doc:MitDocument={PeriodoApuracao:{MesApuracao:Number(String(a.reference_month).slice(5,7)),AnoApuracao:Number(String(a.reference_month).slice(0,4))},DadosIniciais:{SemMovimento:Boolean(a.sem_movimento),QualificacaoPj:Number(a.qualificacao_pj),ResponsavelApuracao:{CpfResponsavel:String(a.responsible_cpf)}}};if(a.tributacao_lucro!=null)doc.DadosIniciais.TributacaoLucro=Number(a.tributacao_lucro);if(a.variacoes_monetarias!=null)doc.DadosIniciais.VariacoesMonetarias=Number(a.variacoes_monetarias);if(a.regime_pis_cofins!=null)doc.DadosIniciais.RegimePisCofins=Number(a.regime_pis_cofins);if(a.responsible_ddd&&a.responsible_phone)doc.DadosIniciais.ResponsavelApuracao.TelResponsavel={Ddd:String(a.responsible_ddd),NumTelefone:String(a.responsible_phone)};if(a.responsible_email)doc.DadosIniciais.ResponsavelApuracao.EmailResponsavel=String(a.responsible_email);if(a.responsible_crc_state&&a.responsible_crc_number)doc.DadosIniciais.ResponsavelApuracao.RegistroCrc={UfRegistro:String(a.responsible_crc_state),NumRegistro:String(a.responsible_crc_number)};if(events?.length)doc.ListaEventosEspeciais=events.map(e=>({IdEvento:Number(e.event_id),DiaEvento:Number(e.event_day),TipoEvento:Number(e.event_type) as 1|2|3|4|5|6}));if(!a.sem_movimento)doc.Debitos=debtBlocks;if(susp.length)doc.ListaSuspensoes=susp;
 let content:string;try{content=renderMitJson(doc);}catch(error){return NextResponse.json({error:error instanceof Error?mensagemDeFalha("api.rh.mit.[id].POST", error):"MIT JSON inválido."},{status:422});}
 const employer=Array.isArray(a.rh_employers)?a.rh_employers[0]:a.rh_employers;const taxId=digits(employer?.tax_id);if(taxId.length!==14)return NextResponse.json({error:"MIT exige empregador com CNPJ de 14 dígitos."},{status:422});const fileName=mitFilename(taxId.slice(0,8),doc),hash=createHash("sha256").update(content,"utf8").digest("hex");const{error:markError}=await context.supabase.from("rh_mit_apurations").update({status:"EXPORTED",exported_filename:fileName,exported_sha256:hash,exported_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("organization_id",context.organizationId).eq("id",id);if(markError)return NextResponse.json({error:mensagemDeFalha("api.rh.mit.[id].POST", markError)},{status:400});return new NextResponse(content,{status:200,headers:{"Content-Type":"application/json; charset=utf-8","Content-Disposition":`attachment; filename="${fileName}"`,"Cache-Control":"no-store, private","X-Content-SHA256":hash,"X-MIT-Layout":"1.0"}});
}
