import Link from"next/link";
import{InventoryNavigation}from"@/components/inventory/inventory-navigation";
import{requireCapability}from"@/lib/authorization";
import{formatInventoryQuantity}from"@/lib/inventory/domain";

export const dynamic="force-dynamic";
function one<T>(value:T|T[]|null|undefined){return Array.isArray(value)?value[0]??null:value??null;}

export default async function InventoryStocktakesPage(){const context=await requireCapability("estoque","read");const{data:stocktakes}=await context.supabase.from("inventory_stocktakes").select("id,code,name,status,warehouse_id,cutoff_at,started_at,submitted_at,approved_at,posted_at,created_at,inventory_warehouses(name,project_id,projects(code,name)),inventory_stocktake_lines(expected_quantity,final_quantity,difference_quantity)").eq("organization_id",context.organizationId).order("created_at",{ascending:false}).limit(100);return <main className="content inventory-app"><section className="page-heading"><div><span className="badge">ESTOQUE · INVENTÁRIO FÍSICO</span><h1>Inventários</h1><p>Contagens por depósito com posição esperada congelada, revisão e ajuste somente após aprovação.</p></div><Link className="button button-primary" href="/app/estoque/inventarios/novo">Novo inventário</Link></section><InventoryNavigation/><section className="inventory-stocktake-grid">{(stocktakes??[]).map(stocktake=>{const warehouse=one(stocktake.inventory_warehouses);const project=one(warehouse?.projects);const differences=(stocktake.inventory_stocktake_lines??[]).filter(line=>Number(line.difference_quantity??0)!==0);const absoluteDifference=differences.reduce((sum,line)=>sum+Math.abs(Number(line.difference_quantity??0)),0);return <Link className="card card-pad inventory-stocktake-card" href={`/app/estoque/inventarios/${stocktake.id}`} key={stocktake.id}><header><div><span className="eyebrow">{stocktake.code} · {stocktake.status}</span><h2>{stocktake.name}</h2></div><span className={`badge ${differences.length>0?"badge-danger":""}`}>{differences.length} divergência(s)</span></header><dl className="detail-list"><div><dt>Depósito</dt><dd>{warehouse?.name??"—"}</dd></div><div><dt>Obra</dt><dd>{project?`${project.code} · ${project.name}`:"Geral"}</dd></div><div><dt>Linhas</dt><dd>{stocktake.inventory_stocktake_lines?.length??0}</dd></div><div><dt>Divergência absoluta</dt><dd>{formatInventoryQuantity(absoluteDifference)}</dd></div><div><dt>Início</dt><dd>{stocktake.started_at?new Date(stocktake.started_at).toLocaleString("pt-BR"):"—"}</dd></div></dl></Link>})}{!stocktakes?.length&&<div className="empty-state"><h3>Nenhum inventário físico</h3><p>Inicie uma contagem para conferir o saldo de um depósito.</p></div>}</section></main>;}
