import{requireOrganizationContext}from"@/lib/auth";
import{formatMoney}from"@/lib/financial/cash-flow";
export const dynamic="force-dynamic";

type Payslip={publication_id:string;reference_month:string;processing_type:string;registration_number:string;gross_amount:number|string;deduction_amount:number|string;net_amount:number|string};
type PayslipLine={line_id:string;rubric_code:string;rubric_name:string;payroll_kind:string;quantity:number|string|null;amount:number|string};

export default async function MyRhPage({searchParams}:{searchParams:Promise<{recibo?:string}>}){
 const context=await requireOrganizationContext();const q=await searchParams;
 const{data,error}=await context.supabase.rpc("get_my_rh_payslips");if(error)throw new Error(error.message);const payslips=(data??[]) as Payslip[];
 const selected=q.recibo?payslips.find(p=>p.publication_id===q.recibo)??null:null;
 const result=selected?await context.supabase.rpc("get_my_rh_payslip_lines",{p_publication_id:selected.publication_id}):{data:[] as PayslipLine[],error:null};if(result.error)throw new Error(result.error.message);const lines=(result.data??[]) as PayslipLine[];
 return <main className="content"><section className="page-heading"><div><span className="badge">MEU RH</span><h1>Recibos e informações publicadas</h1><p>Esta área mostra somente documentos liberados para o seu vínculo; dados de outros trabalhadores nunca são consultados por esta tela.</p></div></section><section className="card" style={{overflowX:"auto"}}><table className="data-table"><thead><tr><th>Competência</th><th>Tipo</th><th>Matrícula</th><th>Bruto</th><th>Descontos</th><th>Líquido</th><th></th></tr></thead><tbody>{payslips.map(p=><tr key={p.publication_id}><td>{String(p.reference_month).slice(0,7)}</td><td>{p.processing_type}</td><td>{p.registration_number}</td><td>{formatMoney(Number(p.gross_amount))}</td><td>{formatMoney(Number(p.deduction_amount))}</td><td><strong>{formatMoney(Number(p.net_amount))}</strong></td><td><a className="text-link" href={`/app/rh/meu-rh?recibo=${p.publication_id}`}>Ver recibo →</a></td></tr>)}{!payslips.length?<tr><td colSpan={7}><div className="empty-state"><h3>Nenhum recibo publicado</h3><p>Os recibos aparecem aqui somente depois da publicação pelo RH.</p></div></td></tr>:null}</tbody></table></section>{selected?<section className="card" style={{overflowX:"auto"}}><div className="section-heading card-pad"><div><span className="eyebrow">RECIBO</span><h2>{String(selected.reference_month).slice(0,7)} · {selected.processing_type}</h2></div><strong>{formatMoney(Number(selected.net_amount))}</strong></div><table className="data-table"><thead><tr><th>Rubrica</th><th>Descrição</th><th>Tipo</th><th>Quantidade</th><th>Valor</th></tr></thead><tbody>{lines.map(l=><tr key={l.line_id}><td>{l.rubric_code}</td><td>{l.rubric_name}</td><td>{l.payroll_kind}</td><td>{l.quantity??"—"}</td><td>{formatMoney(Number(l.amount))}</td></tr>)}</tbody></table><div className="card-pad"><p><strong>Bruto:</strong> {formatMoney(Number(selected.gross_amount))} · <strong>Descontos:</strong> {formatMoney(Number(selected.deduction_amount))} · <strong>Líquido:</strong> {formatMoney(Number(selected.net_amount))}</p></div></section>:null}</main>;
}
