import Link from "next/link";
import {notFound} from "next/navigation";
import {ReceiptForm} from "@/components/procurement/receipt-form";
import {requireCapability} from "@/lib/authorization";
import {formatCurrency} from "@/lib/procurement/comparison";

export const dynamic="force-dynamic";

export default async function ProcurementOrderDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
  const{id}=await params;const query=await searchParams;const context=await requireCapability("compras","read");
  const{data:order,error}=await context.supabase.from("procurement_orders").select("*,projects(name,code),procurement_suppliers(legal_name,trade_name,email),procurement_requests(id,code,title)").eq("id",id).eq("organization_id",context.organizationId).single();
  if(error||!order)notFound();
  const[{data:items},{data:receipts}]=await Promise.all([
    context.supabase.from("procurement_order_items").select("*").eq("order_id",id).order("description"),
    context.supabase.from("procurement_receipts").select("*,procurement_receipt_quality(assignment_id,response_id)").eq("order_id",id).order("received_at",{ascending:false})
  ]);
  const project=Array.isArray(order.projects)?order.projects[0]:order.projects;const supplier=Array.isArray(order.procurement_suppliers)?order.procurement_suppliers[0]:order.procurement_suppliers;const request=Array.isArray(order.procurement_requests)?order.procurement_requests[0]:order.procurement_requests;
  const ordered=(items??[]).reduce((sum,item)=>sum+Number(item.ordered_quantity),0);const received=(items??[]).reduce((sum,item)=>sum+Number(item.received_quantity),0);const progress=ordered>0?Math.min(100,(received/ordered)*100):0;
  const openItems=(items??[]).filter(item=>Number(item.received_quantity)<Number(item.ordered_quantity));
  return <main className="content procurement-app"><Link className="back-link" href="/app/compras/pedidos">← Pedidos</Link><section className="page-heading"><div><span className="badge">{order.code}</span><h1>{supplier?.trade_name||supplier?.legal_name||"Fornecedor"}</h1><p>{project?.code} · {project?.name} · origem {request?.code} {request?.title}</p></div><div><span className="badge">{order.status}</span><h2>{formatCurrency(Number(order.total),order.currency)}</h2></div></section>{query.error&&<div className="validation blocking">{query.error}</div>}
    <section className="stats-grid"><article className="card"><small>VALOR</small><strong>{formatCurrency(Number(order.total),order.currency)}</strong><span>{order.payment_terms||"Pagamento não informado"}</span></article><article className="card"><small>PREVISÃO</small><strong>{order.expected_at?new Date(`${order.expected_at}T12:00:00`).toLocaleDateString("pt-BR"):"—"}</strong><span>data de entrega</span></article><article className="card"><small>RECEBIDO</small><strong>{progress.toFixed(1)}%</strong><span>{received} de {ordered} unidades</span></article><article className="card"><small>FVM</small><strong>{receipts?.filter(receipt=>receipt.procurement_receipt_quality?.length).length??0}</strong><span>inspeções abertas</span></article></section>
    <div className="procurement-two-column"><section><article className="card card-pad"><div className="section-heading"><div><span className="eyebrow">ITENS DO PEDIDO</span><h2>Saldo de entrega</h2></div></div><div className="procurement-item-list">{(items??[]).map(item=>{const itemProgress=Number(item.ordered_quantity)>0?(Number(item.received_quantity)/Number(item.ordered_quantity))*100:0;return <div className="procurement-order-item" key={item.id}><div><strong>{item.description}</strong><small>{item.specification||"Sem especificação"}</small></div><div><span>{Number(item.received_quantity)} / {Number(item.ordered_quantity)} {item.unit}</span><progress max="100" value={itemProgress}/></div><strong>{formatCurrency(Number(item.total),order.currency)}</strong></div>})}</div></article>
      <article className="card card-pad"><div className="section-heading"><div><span className="eyebrow">HISTÓRICO</span><h2>Recebimentos</h2></div></div><div className="procurement-list">{(receipts??[]).map(receipt=>{const quality=Array.isArray(receipt.procurement_receipt_quality)?receipt.procurement_receipt_quality[0]:receipt.procurement_receipt_quality;return <div className="procurement-row" key={receipt.id}><div><strong>{receipt.code} · NF {receipt.invoice_number||"—"}</strong><small>{new Date(receipt.received_at).toLocaleString("pt-BR")} · {receipt.status}</small></div>{quality?.assignment_id?<Link className="button button-secondary" href={`/app/qualidade/preenchimentos/${quality.assignment_id}`}>Abrir FVM</Link>:<span className="badge">Sem FVM</span>}</div>})}{!receipts?.length&&<div className="empty-state"><h3>Nenhum recebimento</h3><p>Registre a primeira entrega do pedido.</p></div>}</div></article></section>
      <aside>{openItems.length>0&&order.status!=="CANCELED"?<ReceiptForm orderId={id} projectId={order.project_id} items={openItems.map(item=>({id:item.id,description:item.description,unit:item.unit,orderedQuantity:Number(item.ordered_quantity),receivedQuantity:Number(item.received_quantity)}))}/>:<section className="card card-pad procurement-success"><span>✓</span><h2>Pedido recebido</h2><p>Não há saldo pendente para este pedido.</p></section>}<section className="card card-pad"><span className="eyebrow">CONDIÇÕES</span><dl className="detail-list"><div><dt>Subtotal</dt><dd>{formatCurrency(Number(order.subtotal),order.currency)}</dd></div><div><dt>Desconto</dt><dd>{formatCurrency(Number(order.discount),order.currency)}</dd></div><div><dt>Frete</dt><dd>{formatCurrency(Number(order.freight),order.currency)}</dd></div><div><dt>Impostos</dt><dd>{formatCurrency(Number(order.taxes),order.currency)}</dd></div></dl></section></aside></div>
  </main>;
}
