"use server";

import{mensagemDeFalha}from"@/lib/errors/data-access";

import{revalidatePath}from"next/cache";
import{redirect}from"next/navigation";
import{requireCapability}from"@/lib/authorization";
import{lerMoeda}from"@/lib/validacao/moeda";

const BASE="/app/rh/beneficios";
function t(d:FormData,k:string){return String(d.get(k)??"").trim();}function o(d:FormData,k:string){return t(d,k)||null;}function money(d:FormData,k:string){return lerMoeda(t(d,k));}function fail(path:string,m:string):never{redirect(`${path}?error=${encodeURIComponent(m)}`);}
export async function createBenefitCatalogItem(data:FormData){const c=await requireCapability("rh","configure"),code=t(data,"code").toUpperCase();if(!code||!t(data,"name"))fail(BASE,"Código e nome são obrigatórios.");const{error}=await c.supabase.from("rh_benefit_catalog").insert({organization_id:c.organizationId,code,name:t(data,"name"),benefit_type:t(data,"benefitType"),provider_name:o(data,"providerName"),employee_share_type:t(data,"employeeShareType")||"FIXED",employee_share_value:money(data,"employeeShareValue"),created_by:c.userId});if(error)fail(BASE,mensagemDeFalha("rh-benefits.createBenefitCatalogItem", error));revalidatePath(BASE);}
export async function enrollWorkerBenefit(data:FormData){const c=await requireCapability("rh","update");const{error}=await c.supabase.from("rh_benefit_enrollments").insert({organization_id:c.organizationId,employment_id:t(data,"employmentId"),benefit_id:t(data,"benefitId"),valid_from:t(data,"validFrom"),valid_to:o(data,"validTo"),status:"ACTIVE",plan_reference:o(data,"planReference"),created_by:c.userId});if(error)fail(BASE,mensagemDeFalha("rh-benefits.enrollWorkerBenefit", error));revalidatePath(BASE);}
export async function registerBenefitCharge(data:FormData){const c=await requireCapability("rh","update"),month=t(data,"referenceMonth");if(!/^\d{4}-\d{2}$/.test(month))fail(BASE,"Competência inválida.");const{error}=await c.supabase.from("rh_benefit_charges").upsert({organization_id:c.organizationId,enrollment_id:t(data,"enrollmentId"),reference_month:`${month}-01`,provider_amount:money(data,"providerAmount")??0,employer_amount:money(data,"employerAmount")??0,employee_amount:money(data,"employeeAmount")??0,copay_amount:money(data,"copayAmount")??0,source_reference:o(data,"sourceReference"),status:"VALIDATED",created_by:c.userId},{onConflict:"enrollment_id,reference_month"});if(error)fail(BASE,mensagemDeFalha("rh-benefits.registerBenefitCharge", error));revalidatePath(BASE);}
export async function exportBenefitToPayroll(data:FormData){const c=await requireCapability("rh","update");const{error}=await c.supabase.rpc("export_rh_benefit_charge_to_payroll",{p_charge_id:t(data,"chargeId"),p_payroll_period_id:t(data,"payrollPeriodId"),p_rubric_version_id:t(data,"rubricVersionId")});if(error)fail(BASE,mensagemDeFalha("rh-benefits.exportBenefitToPayroll", error));revalidatePath(BASE);}
export async function createBenefitProviderInvoice(data:FormData){const c=await requireCapability("rh","create"),month=t(data,"referenceMonth"),total=money(data,"totalAmount");if(!/^\d{4}-\d{2}$/.test(month)||total==null)fail(BASE,"Competência e total da fatura são obrigatórios.");const{data:id,error}=await c.supabase.from("rh_benefit_provider_invoices").insert({organization_id:c.organizationId,provider_name:t(data,"providerName"),reference_month:`${month}-01`,external_invoice_number:o(data,"externalInvoiceNumber"),total_amount:total,due_date:o(data,"dueDate"),evidence_reference:o(data,"evidenceReference"),status:"IMPORTED",created_by:c.userId}).select("id").single();if(error)fail(BASE,mensagemDeFalha("rh-benefits.createBenefitProviderInvoice", error));redirect(`${BASE}/faturas/${id}`);}
export async function addBenefitProviderInvoiceItem(data:FormData){const c=await requireCapability("rh","update"),invoiceId=t(data,"invoiceId"),path=`${BASE}/faturas/${invoiceId}`,billed=money(data,"billedTotal"),employee=money(data,"billedEmployeeAmount")??0;if(billed==null)fail(path,"Valor faturado obrigatório.");const{error}=await c.supabase.from("rh_benefit_provider_invoice_items").upsert({organization_id:c.organizationId,invoice_id:invoiceId,enrollment_id:t(data,"enrollmentId"),external_worker_reference:o(data,"externalWorkerReference"),billed_total:billed,billed_employee_amount:employee,status:"PENDING",note:o(data,"note"),updated_at:new Date().toISOString()},{onConflict:"invoice_id,enrollment_id"});if(error)fail(path,mensagemDeFalha("rh-benefits.addBenefitProviderInvoiceItem", error));revalidatePath(path);}
export async function reconcileBenefitProviderInvoice(data:FormData){const c=await requireCapability("rh","approve"),invoiceId=t(data,"invoiceId"),path=`${BASE}/faturas/${invoiceId}`;const{error}=await c.supabase.rpc("reconcile_rh_benefit_provider_invoice",{p_invoice_id:invoiceId});if(error)fail(path,mensagemDeFalha("rh-benefits.reconcileBenefitProviderInvoice", error));revalidatePath(path);}
export async function approveBenefitProviderInvoice(data:FormData){const c=await requireCapability("rh","approve"),invoiceId=t(data,"invoiceId"),path=`${BASE}/faturas/${invoiceId}`;const{error}=await c.supabase.rpc("approve_rh_benefit_provider_invoice",{p_invoice_id:invoiceId});if(error)fail(path,mensagemDeFalha("rh-benefits.approveBenefitProviderInvoice", error));revalidatePath(path);}
export async function payBenefitProviderInvoice(data:FormData){const c=await requireCapability("rh","approve"),invoiceId=t(data,"invoiceId"),path=`${BASE}/faturas/${invoiceId}`,paymentReference=t(data,"paymentReference");if(!paymentReference)fail(path,"Referência de pagamento obrigatória.");const{error}=await c.supabase.rpc("pay_rh_benefit_provider_invoice",{p_invoice_id:invoiceId,p_payment_reference:paymentReference,p_evidence_reference:o(data,"evidenceReference")});if(error)fail(path,mensagemDeFalha("rh-benefits.payBenefitProviderInvoice", error));revalidatePath(path);}
