"use server";

import { campoDeTexto } from "@/lib/forms/campos";
import{mensagemDeFalha}from"@/lib/errors/data-access";

import{createHash,randomUUID}from"node:crypto";
import{revalidatePath}from"next/cache";
import{redirect}from"next/navigation";
import{hasCapability,requireCapability}from"@/lib/authorization";

const BASE="/app/rh/documentos",BUCKET="rh-documents",MAX=20*1024*1024;
function t(d:FormData,k:string){return campoDeTexto(d, k).trim();}function o(d:FormData,k:string){return t(d,k)||null;}function fail(path:string,m:string):never{redirect(`${path}?error=${encodeURIComponent(m)}`);}function safeName(name:string){return name.replace(/[^A-Za-z0-9._-]/g,"-").slice(-150)||"documento";}
function detect(bytes:Buffer){if(bytes.subarray(0,5).toString("ascii")==="%PDF-")return"application/pdf";if(bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return"image/jpeg";if(bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return"image/png";return null;}
async function requireSensitiveIfNeeded(context:Awaited<ReturnType<typeof requireCapability>>,sensitivity:string){if(["CLINICAL","JUDICIAL"].includes(sensitivity)&&!await hasCapability("rh","view_sensitive_financials",null,context))fail(BASE,"Documento clínico/judicial exige acesso sensível do RH.");}

export async function uploadRhDocument(data:FormData){
 const context=await requireCapability("rh","create"),file=data.get("file");if(!(file instanceof File))fail(BASE,"Selecione um arquivo.");if(file.size<=0||file.size>MAX)fail(BASE,"Arquivo vazio ou acima de 20 MB.");const bytes=Buffer.from(await file.arrayBuffer()),mime=detect(bytes);if(!mime)fail(BASE,"Formato não permitido. Use PDF, JPEG ou PNG válidos.");const sensitivity=t(data,"sensitivity")||"STANDARD";await requireSensitiveIfNeeded(context,sensitivity);const workerId=o(data,"workerId"),employmentId=o(data,"employmentId");if(workerId&&employmentId){const{data:emp,error}=await context.supabase.from("rh_employments").select("worker_id").eq("organization_id",context.organizationId).eq("id",employmentId).maybeSingle();if(error||!emp||emp.worker_id!==workerId)fail(BASE,"Vínculo não pertence ao trabalhador selecionado.");}
 let documentId=o(data,"documentId");if(documentId){const{data:doc,error}=await context.supabase.from("rh_documents").select("id,sensitivity").eq("organization_id",context.organizationId).eq("id",documentId).maybeSingle();if(error||!doc)fail(BASE,mensagemDeFalha("rh-documents.uploadRhDocument", error, "Documento não encontrado."));await requireSensitiveIfNeeded(context,doc.sensitivity);}else{const{data:doc,error}=await context.supabase.from("rh_documents").insert({organization_id:context.organizationId,worker_id:workerId,employment_id:employmentId,category:t(data,"category")||"OTHER",title:t(data,"title")||file.name,description:o(data,"description"),sensitivity,status:"DRAFT",visible_to_worker:false,retention_until:o(data,"retentionUntil"),legal_hold:false,created_by:context.userId}).select("id").single();if(error)fail(BASE,mensagemDeFalha("rh-documents.uploadRhDocument", error));documentId=doc.id;}
 const{data:last}=await context.supabase.from("rh_document_versions").select("version").eq("organization_id",context.organizationId).eq("document_id",documentId).order("version",{ascending:false}).limit(1).maybeSingle();const version=Number(last?.version??0)+1,path=`${context.organizationId}/rh/${documentId}/${version}-${randomUUID()}-${safeName(file.name)}`,sha=createHash("sha256").update(bytes).digest("hex");const uploaded=await context.supabase.storage.from(BUCKET).upload(path,bytes,{contentType:mime,upsert:false,cacheControl:"0"});if(uploaded.error)fail(BASE,`Falha no Storage privado: ${mensagemDeFalha("rh-documents.uploadRhDocument", uploaded.error)}`);const{error:vError}=await context.supabase.from("rh_document_versions").insert({organization_id:context.organizationId,document_id:documentId,version,status:"ACTIVE",original_name:file.name,mime_type:mime,byte_size:file.size,sha256:sha,storage_path:path,uploaded_by:context.userId});if(vError){await context.supabase.storage.from(BUCKET).remove([path]);fail(BASE,mensagemDeFalha("rh-documents.uploadRhDocument", vError));}await context.supabase.from("rh_documents").update({status:"ACTIVE",updated_at:new Date().toISOString()}).eq("organization_id",context.organizationId).eq("id",documentId);redirect(`${BASE}?document=${documentId}`);
}

export async function publishRhDocument(data:FormData){const context=await requireCapability("rh","approve"),versionId=t(data,"versionId"),visible=data.get("visibleToWorker")==="on";const{data:v,error}=await context.supabase.from("rh_document_versions").select("document_id,rh_documents(sensitivity)").eq("organization_id",context.organizationId).eq("id",versionId).maybeSingle();if(error||!v)fail(BASE,mensagemDeFalha("rh-documents.publishRhDocument", error, "Versão não encontrada."));const doc=Array.isArray(v.rh_documents)?v.rh_documents[0]:v.rh_documents;if(doc)await requireSensitiveIfNeeded(context,doc.sensitivity);const{error:publish}=await context.supabase.rpc("publish_rh_document_version",{p_version_id:versionId,p_visible_to_worker:visible});if(publish)fail(BASE,publish.message);revalidatePath(BASE);revalidatePath("/app/rh/meu-rh");}

export async function archiveRhDocument(data:FormData){const context=await requireCapability("rh","update"),id=t(data,"documentId");const{data:doc,error:load}=await context.supabase.from("rh_documents").select("sensitivity,legal_hold").eq("organization_id",context.organizationId).eq("id",id).maybeSingle();if(load||!doc)fail(BASE,load?.message??"Documento não encontrado.");await requireSensitiveIfNeeded(context,doc.sensitivity);if(doc.legal_hold)fail(BASE,"Documento sob legal hold não pode ser arquivado por este fluxo.");const{error}=await context.supabase.from("rh_documents").update({status:"ARCHIVED",visible_to_worker:false,updated_at:new Date().toISOString()}).eq("organization_id",context.organizationId).eq("id",id);if(error)fail(BASE,mensagemDeFalha("rh-documents.archiveRhDocument", error));revalidatePath(BASE);}
