"use server";

import{mensagemDeFalha}from"@/lib/errors/data-access";

import{redirect}from"next/navigation";
import{requireCapability}from"@/lib/authorization";
import{lerMoeda}from"@/lib/validacao/moeda";
function t(d:FormData,k:string){return String(d.get(k)??"").trim()}function o(d:FormData,k:string){return t(d,k)||null}function n(d:FormData,k:string){return lerMoeda(t(d,k))}function fail(p:string,m:string):never{redirect(`${p}?error=${encodeURIComponent(m)}`)}function ok(p:string,m:string):never{redirect(`${p}?success=${encodeURIComponent(m)}`)}
export async function createVacationEntitlement(d:FormData){const c=await requireCapability("rh","create"),p="/app/rh/ferias";const{error}=await c.supabase.from("rh_vacation_entitlements").insert({organization_id:c.organizationId,employment_id:t(d,"employmentId"),acquisition_start:t(d,"acquisitionStart"),acquisition_end:t(d,"acquisitionEnd"),days_entitled:n(d,"daysEntitled")??30,created_by:c.userId});if(error)fail(p,mensagemDeFalha("rh-movements.createVacationEntitlement", error));ok(p,"Período aquisitivo registrado.")}
export async function createVacationCase(d:FormData){const c=await requireCapability("rh","create"),p="/app/rh/ferias";const{data:ent,error:e}=await c.supabase.from("rh_vacation_entitlements").select("employment_id").eq("organization_id",c.organizationId).eq("id",t(d,"entitlementId")).maybeSingle();if(e||!ent)fail(p,e?.message??"Direito não encontrado.");const{data:x,error}=await c.supabase.from("rh_vacation_cases").insert({organization_id:c.organizationId,entitlement_id:t(d,"entitlementId"),employment_id:ent.employment_id,vacation_start:t(d,"vacationStart"),vacation_end:t(d,"vacationEnd"),days:n(d,"days"),cash_conversion_days:n(d,"cashDays")??0,divisor_days:n(d,"divisorDays")??30,remuneration_base:n(d,"remunerationBase")??0,average_amount:n(d,"averageAmount")??0,pay_date:o(d,"payDate"),reason:o(d,"reason"),evidence_reference:o(d,"evidenceReference"),created_by:c.userId}).select("id").single();if(error)fail(p,mensagemDeFalha("rh-movements.createVacationCase", error));redirect(`/app/rh/ferias/${x.id}`)}
export async function approveVacationCase(d:FormData){const c=await requireCapability("rh","approve"),id=t(d,"caseId"),p=`/app/rh/ferias/${id}`;const{error}=await c.supabase.rpc("approve_rh_vacation_case",{p_case_id:id});if(error)fail(p,mensagemDeFalha("rh-movements.approveVacationCase", error));ok(p,"Férias aprovadas e saldo consumido.")}
export async function exportVacationToPayroll(d:FormData){const c=await requireCapability("rh","update"),id=t(d,"caseId"),p=`/app/rh/ferias/${id}`;const{error}=await c.supabase.rpc("export_rh_vacation_to_payroll",{p_case_id:id,p_payroll_period_id:t(d,"payrollPeriodId"),p_vacation_rubric:t(d,"vacationRubricVersionId"),p_third_rubric:t(d,"thirdRubricVersionId"),p_cash_rubric:o(d,"cashRubricVersionId")});if(error)fail(p,mensagemDeFalha("rh-movements.exportVacationToPayroll", error));ok(p,"Férias exportadas para a folha.")}
export async function createLeaveCase(d:FormData){const c=await requireCapability("rh","create"),p="/app/rh/afastamentos";const{error}=await c.supabase.from("rh_leave_cases").insert({organization_id:c.organizationId,employment_id:t(d,"employmentId"),leave_type:t(d,"leaveType"),internal_reason:t(d,"internalReason"),esocial_reason_code:o(d,"esocialReasonCode"),start_date:t(d,"startDate"),end_date:o(d,"endDate"),paid_percentage:n(d,"paidPercentage"),status:t(d,"status")||"OPEN",document_reference:o(d,"documentReference"),return_fitness_required:d.get("returnFitnessRequired")==="on",created_by:c.userId});if(error)fail(p,mensagemDeFalha("rh-movements.createLeaveCase", error));ok(p,"Afastamento registrado.")}
