"use server";

import { campoDeTexto } from "@/lib/forms/campos";
import{mensagemDeFalha}from"@/lib/errors/data-access";

import{revalidatePath}from"next/cache";
import{redirect}from"next/navigation";
import{requireCapability}from"@/lib/authorization";
import{lerMoeda}from"@/lib/validacao/moeda";

const BASE="/app/rh/obrigacoes/dctfweb/mit";
function t(d:FormData,k:string){return campoDeTexto(d, k).trim();}function o(d:FormData,k:string){return t(d,k)||null;}function num(d:FormData,k:string){const v=t(d,k);return v?Number(v):null;}function money(d:FormData,k:string){return lerMoeda(t(d,k));}function check(d:FormData,k:string){return d.get(k)==="on"||d.get(k)==="true";}function digits(v:string){return v.replace(/\D/g,"");}function fail(path:string,m:string):never{redirect(`${path}?error=${encodeURIComponent(m)}`);}

export async function createMitApuration(data:FormData){const context=await requireCapability("rh","create");const month=t(data,"referenceMonth");if(!/^\d{4}-\d{2}$/.test(month))fail(BASE,"Competência inválida.");const sem=check(data,"semMovimento"),cpf=digits(t(data,"responsibleCpf"));if(cpf.length!==11)fail(BASE,"CPF do responsável deve conter 11 dígitos.");const{data:id,error}=await context.supabase.rpc("create_rh_mit_apuration",{p_organization_id:context.organizationId,p_employer_id:t(data,"employerId"),p_reference_month:`${month}-01`,p_sem_movimento:sem,p_qualificacao_pj:Number(t(data,"qualificacaoPj")),p_tributacao_lucro:sem?null:num(data,"tributacaoLucro"),p_variacoes_monetarias:sem?null:num(data,"variacoesMonetarias"),p_regime_pis_cofins:sem?null:num(data,"regimePisCofins"),p_balanco_lucro_real:sem?null:check(data,"balancoLucroReal"),p_responsible_cpf:cpf,p_responsible_ddd:digits(t(data,"responsibleDdd"))||null,p_responsible_phone:digits(t(data,"responsiblePhone"))||null,p_responsible_email:o(data,"responsibleEmail"),p_responsible_crc_state:o(data,"crcState")?.toUpperCase()??null,p_responsible_crc_number:o(data,"crcNumber")});if(error)fail(BASE,mensagemDeFalha("rh-mit.createMitApuration", error));redirect(`${BASE}/${id}`);}

export async function addMitDebt(data:FormData){const context=await requireCapability("rh","update"),id=t(data,"apurationId"),path=`${BASE}/${id}`,amount=money(data,"amount");if(amount==null)fail(path,"Valor do débito obrigatório.");const{error}=await context.supabase.from("rh_mit_debts").insert({organization_id:context.organizationId,apuration_id:id,group_code:t(data,"groupCode"),debt_id:Number(t(data,"debtId")),after_event:check(data,"afterEvent"),event_id:num(data,"eventId"),revenue_code:digits(t(data,"revenueCode")),pa_debito:num(data,"paDebito"),ano_postergado:num(data,"anoPostergado"),trim_postergado:num(data,"trimPostergado"),ano_debito:num(data,"anoDebito"),cnpj_estabelecimento:digits(t(data,"cnpjEstabelecimento"))||null,cnpj_incorporacao:digits(t(data,"cnpjIncorporacao"))||null,cnpj_scp:digits(t(data,"cnpjScp"))||null,codigo_municipio_ouro:digits(t(data,"codigoMunicipioOuro"))||null,amount,created_by:context.userId});if(error)fail(path,mensagemDeFalha("rh-mit.addMitDebt", error));revalidatePath(path);}

export async function addMitSpecialEvent(data:FormData){const context=await requireCapability("rh","update"),id=t(data,"apurationId"),path=`${BASE}/${id}`;const{error}=await context.supabase.from("rh_mit_special_events").insert({organization_id:context.organizationId,apuration_id:id,event_id:Number(t(data,"eventId")),event_day:Number(t(data,"eventDay")),event_type:Number(t(data,"eventType"))});if(error)fail(path,mensagemDeFalha("rh-mit.addMitSpecialEvent", error));revalidatePath(path);}

export async function addMitSuspension(data:FormData){const context=await requireCapability("rh","update"),id=t(data,"apurationId"),path=`${BASE}/${id}`,process=digits(t(data,"processNumber"));const{data:s,error}=await context.supabase.from("rh_mit_suspensions").insert({organization_id:context.organizationId,apuration_id:id,suspension_type:Number(t(data,"suspensionType")),suspension_reason:num(data,"suspensionReason"),with_deposit:check(data,"withDeposit"),process_number:process,third_party_process:check(data,"thirdPartyProcess"),decision_date:num(data,"decisionDate"),court_number:num(data,"courtNumber"),judicial_city_code:digits(t(data,"judicialCityCode"))||null}).select("id").single();if(error)fail(path,mensagemDeFalha("rh-mit.addMitSuspension", error));const debtRowId=t(data,"debtRowId"),amount=money(data,"suspendedAmount");if(debtRowId&&amount!=null){const{error:linkError}=await context.supabase.from("rh_mit_suspended_debts").insert({organization_id:context.organizationId,suspension_id:s.id,debt_row_id:debtRowId,amount});if(linkError)fail(path,mensagemDeFalha("rh-mit.addMitSuspension", linkError));}revalidatePath(path);}

export async function markMitImported(data:FormData){const context=await requireCapability("rh","approve"),id=t(data,"apurationId"),path=`${BASE}/${id}`;const{error}=await context.supabase.from("rh_mit_apurations").update({status:"IMPORTED",imported_at:new Date().toISOString(),evidence_reference:o(data,"evidenceReference"),updated_at:new Date().toISOString()}).eq("organization_id",context.organizationId).eq("id",id).eq("status","EXPORTED");if(error)fail(path,mensagemDeFalha("rh-mit.markMitImported", error));revalidatePath(path);}
