"use server";

import{mensagemDeFalha}from"@/lib/errors/data-access";
import{redirect}from"next/navigation";
import{revalidatePath}from"next/cache";
import{requireCapability}from"@/lib/authorization";
import{lerMoeda}from"@/lib/validacao/moeda";
const THIRTEENTH="/app/rh/folha/decimo-terceiro",RETRO="/app/rh/folha/retroativos";function text(d:FormData,k:string){return String(d.get(k)??"").trim();}function fail(path:string,m:string):never{redirect(`${path}?error=${encodeURIComponent(m)}`);}function money(d:FormData,k:string){const v=text(d,k);return v?lerMoeda(v):0;}
export async function createThirteenthCase(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.from("rh_thirteenth_cases").insert({organization_id:context.organizationId,employment_id:text(data,"employmentId"),reference_year:Number(text(data,"referenceYear")),reference_date:text(data,"referenceDate"),entitled_months:Number(text(data,"entitledMonths")),average_base:money(data,"averageBase"),advance_percent:Number(text(data,"advancePercent").replace(",",".")||50),created_by:context.userId});if(error)fail(THIRTEENTH,mensagemDeFalha("rh-payroll-special.createThirteenthCase", error));revalidatePath(THIRTEENTH);redirect(THIRTEENTH);}
export async function calculateThirteenth(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.rpc("calculate_rh_thirteenth",{p_case_id:text(data,"caseId")});if(error)fail(THIRTEENTH,mensagemDeFalha("rh-payroll-special.calculateThirteenth", error));revalidatePath(THIRTEENTH);redirect(THIRTEENTH);}
export async function mapThirteenthRubric(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.from("rh_thirteenth_rubric_mappings").insert({organization_id:context.organizationId,mapping_key:text(data,"mappingKey"),rubric_version_id:text(data,"rubricVersionId"),valid_from:text(data,"validFrom"),created_by:context.userId});if(error)fail(THIRTEENTH,mensagemDeFalha("rh-payroll-special.mapThirteenthRubric", error));revalidatePath(THIRTEENTH);redirect(THIRTEENTH);}
export async function exportThirteenth(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.rpc("export_rh_thirteenth",{p_case_id:text(data,"caseId"),p_period_id:text(data,"periodId"),p_installment:text(data,"installment")});if(error)fail(THIRTEENTH,mensagemDeFalha("rh-payroll-special.exportThirteenth", error));revalidatePath(THIRTEENTH);redirect(THIRTEENTH);}
export async function createPayrollDifference(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.rpc("materialize_rh_payroll_difference",{p_original_run:text(data,"originalRunId"),p_revised_run:text(data,"revisedRunId"),p_reason:text(data,"reason")});if(error)fail(RETRO,mensagemDeFalha("rh-payroll-special.createPayrollDifference", error));revalidatePath(RETRO);redirect(RETRO);}
export async function mapPayrollDifferenceLine(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.from("rh_payroll_difference_lines").update({export_rubric_version_id:text(data,"rubricVersionId"),explanation:text(data,"explanation")||null}).eq("organization_id",context.organizationId).eq("id",text(data,"lineId"));if(error)fail(RETRO,mensagemDeFalha("rh-payroll-special.mapPayrollDifferenceLine", error));revalidatePath(RETRO);redirect(RETRO);}
export async function approvePayrollDifference(data:FormData){const context=await requireCapability("rh","approve");const{error}=await context.supabase.rpc("approve_rh_payroll_difference_case",{p_case_id:text(data,"caseId"),p_target_period_id:text(data,"targetPeriodId")});if(error)fail(RETRO,mensagemDeFalha("rh-payroll-special.approvePayrollDifference", error));revalidatePath(RETRO);redirect(RETRO);}
export async function exportPayrollDifference(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.rpc("export_rh_payroll_difference_case",{p_case_id:text(data,"caseId")});if(error)fail(RETRO,mensagemDeFalha("rh-payroll-special.exportPayrollDifference", error));revalidatePath(RETRO);redirect(RETRO);}
