"use server";

import { campoDeTexto } from "@/lib/forms/campos";
import{mensagemDeFalha}from"@/lib/errors/data-access";

import{revalidatePath}from"next/cache";
import{redirect}from"next/navigation";
import{requireCapability}from"@/lib/authorization";

const PATH="/app/rh/sst";
function text(d:FormData,k:string){return campoDeTexto(d, k).trim();}
function opt(d:FormData,k:string){return text(d,k)||null;}
function num(d:FormData,k:string){const v=text(d,k);return v===""?null:Number(v.replace(",","."));}
function bool(d:FormData,k:string){return d.get(k)==="on"||text(d,k)==="true";}
function fail(message:string):never{redirect(`${PATH}?error=${encodeURIComponent(message)}`);}
function success(message:string):never{redirect(`${PATH}?success=${encodeURIComponent(message)}`);}

export async function createSstCat(data:FormData){
 const context=await requireCapability("rh","update");
 const payload={accidentDate:text(data,"accidentDate"),accidentTime:opt(data,"accidentTime"),hoursWorkedBefore:num(data,"hoursWorkedBefore"),accidentType:Number(text(data,"accidentType")),catType:Number(text(data,"catType")||1),death:bool(data,"death"),deathDate:opt(data,"deathDate"),policeReport:bool(data,"policeReport"),generatingSituationCode:text(data,"generatingSituationCode").replace(/\D/g,""),initiatorType:Number(text(data,"initiatorType")||1),lastWorkedDay:opt(data,"lastWorkedDay"),causedLeave:bool(data,"causedLeave"),locationType:Number(text(data,"locationType")),locationDescription:text(data,"locationDescription"),streetType:opt(data,"streetType"),street:text(data,"street"),streetNumber:text(data,"streetNumber")||"S/N",complement:opt(data,"complement"),neighborhood:opt(data,"neighborhood"),postalCode:opt(data,"postalCode"),cityIbgeCode:opt(data,"cityIbgeCode"),stateCode:opt(data,"stateCode"),countryCode:opt(data,"countryCode"),foreignPostalCode:opt(data,"foreignPostalCode"),establishmentRegistrationType:num(data,"establishmentRegistrationType"),establishmentRegistrationNumber:opt(data,"establishmentRegistrationNumber"),observation:opt(data,"observation"),evidenceReference:opt(data,"evidenceReference"),bodyPart:{code:text(data,"bodyPartCode").replace(/\D/g,""),laterality:Number(text(data,"laterality")||0)},agent:{code:text(data,"agentCode").replace(/\D/g,"")},attestation:{attendanceDate:text(data,"attendanceDate"),attendanceTime:text(data,"attendanceTime"),hospitalization:bool(data,"hospitalization"),treatmentDurationDays:Number(text(data,"treatmentDurationDays")||0),leaveRecommended:bool(data,"leaveRecommended"),injuryNatureCode:text(data,"injuryNatureCode").replace(/\D/g,""),injuryDescription:opt(data,"injuryDescription"),probableDiagnosis:opt(data,"probableDiagnosis"),cidCode:text(data,"cidCode"),observation:opt(data,"attestationObservation"),professionalName:text(data,"professionalName"),professionalRegistrationType:text(data,"professionalRegistrationType"),professionalRegistrationNumber:text(data,"professionalRegistrationNumber"),professionalState:opt(data,"professionalState")}};
 const{data:id,error}=await context.supabase.rpc("create_rh_sst_cat",{p_organization_id:context.organizationId,p_employment_id:text(data,"employmentId"),p_payload:payload});if(error)fail(mensagemDeFalha("rh-sst.createSstCat", error));revalidatePath(PATH);success(`CAT ${String(id).slice(0,8)} registrada.`);
}

export async function createSstAso(data:FormData){
 const context=await requireCapability("rh","update");const lines=text(data,"procedures").split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)fail("Informe ao menos um procedimento do ASO.");
 const procedures=lines.map((line,index)=>{const[examDate,procedureCode,observation,examOrderCode,resultCode]=line.split(";").map(x=>x?.trim()??"");if(!examDate||!procedureCode)throw new Error(`Procedimento ${index+1}: use data;código;observação;ordem;resultado.`);return{examDate,procedureCode:procedureCode.replace(/\D/g,""),observation:observation||null,examOrderCode:examOrderCode||null,resultCode:resultCode||null};});
 const payload={examType:Number(text(data,"examType")),asoDate:text(data,"asoDate"),resultCode:opt(data,"resultCode"),physicianName:text(data,"physicianName"),physicianCpf:text(data,"physicianCpf"),physicianCrm:opt(data,"physicianCrm"),physicianState:opt(data,"physicianState"),pcmsoResponsibleCpf:opt(data,"pcmsoResponsibleCpf"),pcmsoResponsibleName:opt(data,"pcmsoResponsibleName"),pcmsoResponsibleCrm:opt(data,"pcmsoResponsibleCrm"),pcmsoResponsibleState:opt(data,"pcmsoResponsibleState"),evidenceReference:opt(data,"evidenceReference"),procedures};
 const{data:id,error}=await context.supabase.rpc("create_rh_sst_aso",{p_organization_id:context.organizationId,p_employment_id:text(data,"employmentId"),p_payload:payload});if(error)fail(mensagemDeFalha("rh-sst.createSstAso", error));revalidatePath(PATH);success(`ASO ${String(id).slice(0,8)} registrado.`);
}

export async function createSstExposure(data:FormData){
 const context=await requireCapability("rh","update");const agentCode=text(data,"agentCode");const epiDocs=text(data,"epiDocuments").split(/[;,\n]/).map(x=>x.trim()).filter(Boolean);
 const agent={agentCode,description:opt(data,"agentDescription"),evaluationType:opt(data,"evaluationType"),intensity:opt(data,"intensity"),toleranceLimit:opt(data,"toleranceLimit"),unitCode:opt(data,"unitCode"),measurementTechnique:opt(data,"measurementTechnique"),judicialProcessNumber:opt(data,"judicialProcessNumber"),epcImplemented:data.has("epcImplemented")?bool(data,"epcImplemented"):null,epcEffective:data.has("epcEffective")?bool(data,"epcEffective"):null,epiUsed:data.has("epiUsed")?bool(data,"epiUsed"):null,epiEffective:data.has("epiEffective")?bool(data,"epiEffective"):null,protectiveMeasuresAttempted:data.has("protectiveMeasuresAttempted")?bool(data,"protectiveMeasuresAttempted"):null,epiUseConditionCompliant:data.has("epiUseConditionCompliant")?bool(data,"epiUseConditionCompliant"):null,uninterruptedUseObserved:data.has("uninterruptedUseObserved")?bool(data,"uninterruptedUseObserved"):null,epiExpiryObserved:data.has("epiExpiryObserved")?bool(data,"epiExpiryObserved"):null,epiChangeFrequencyObserved:data.has("epiChangeFrequencyObserved")?bool(data,"epiChangeFrequencyObserved"):null,epiCleaningObserved:data.has("epiCleaningObserved")?bool(data,"epiCleaningObserved"):null,epiDocuments:epiDocs};
 const payload={validFrom:text(data,"validFrom"),validTo:opt(data,"validTo"),environmentCode:text(data,"environmentCode")||"ENV",environmentLocationType:Number(text(data,"environmentLocationType")||1),sectorDescription:text(data,"sectorDescription"),activityDescription:text(data,"activityDescription"),environmentRegistrationType:Number(text(data,"environmentRegistrationType")),environmentRegistrationNumber:text(data,"environmentRegistrationNumber"),responsibleCpf:opt(data,"responsibleCpf"),responsibleRegistrationType:opt(data,"responsibleRegistrationType"),responsibleRegistrationNumber:opt(data,"responsibleRegistrationNumber"),responsibleState:opt(data,"responsibleState"),observation:opt(data,"observation"),evidenceReference:opt(data,"evidenceReference"),agents:[agent]};
 const{data:id,error}=await context.supabase.rpc("create_rh_sst_exposure",{p_organization_id:context.organizationId,p_employment_id:text(data,"employmentId"),p_payload:payload});if(error)fail(mensagemDeFalha("rh-sst.createSstExposure", error));revalidatePath(PATH);success(`Exposição ${String(id).slice(0,8)} registrada.`);
}

export async function markSstReady(data:FormData){const context=await requireCapability("rh","approve");const{error}=await context.supabase.rpc("mark_rh_sst_ready",{p_kind:text(data,"kind"),p_id:text(data,"id")});if(error)fail(mensagemDeFalha("rh-sst.markSstReady", error));revalidatePath(PATH);success("Registro SST liberado para projeção eSocial.");}
export async function createSstEpi(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.from("rh_sst_epi_catalog").insert({organization_id:context.organizationId,code:text(data,"code"),name:text(data,"name"),certificate_number:text(data,"certificateNumber"),manufacturer:opt(data,"manufacturer"),created_by:context.userId});if(error)fail(mensagemDeFalha("rh-sst.createSstEpi", error));revalidatePath(PATH);success("EPI cadastrado.");}
export async function deliverSstEpi(data:FormData){const context=await requireCapability("rh","update");const{error}=await context.supabase.from("rh_sst_epi_deliveries").insert({organization_id:context.organizationId,employment_id:text(data,"employmentId"),epi_id:text(data,"epiId"),delivered_at:text(data,"deliveredAt"),quantity:num(data,"quantity")??1,reason:opt(data,"reason"),evidence_reference:opt(data,"evidenceReference"),created_by:context.userId});if(error)fail(mensagemDeFalha("rh-sst.deliverSstEpi", error));revalidatePath(PATH);success("Entrega de EPI registrada.");}
