import{createRhEmployer,createRhEstablishment,createRhFunction,createRhPosition,createRhTaxAllocation,createRhUnion,createRhWorkSchedule}from"@/app/actions/rh";
import{requireCapability}from"@/lib/authorization";

export const dynamic="force-dynamic";
export default async function RhStructureConfigurationPage({searchParams}:{searchParams:Promise<{error?:string}>}){const context=await requireCapability("rh","configure");const query=await searchParams;const[employersResult,establishmentsResult,allocationsResult,positionsResult,functionsResult,unionsResult,schedulesResult]=await Promise.all([
context.supabase.from("rh_employers").select("id,code,legal_name,trade_name,tax_id,status").eq("organization_id",context.organizationId).order("code"),
context.supabase.from("rh_establishments").select("id,employer_id,code,name,registration_type,registration_number,status,rh_employers(code,legal_name)").eq("organization_id",context.organizationId).order("code"),
context.supabase.from("rh_tax_allocations").select("id,employer_id,establishment_id,code,name,esocial_lotacao_code,valid_from,valid_to").eq("organization_id",context.organizationId).order("code"),
context.supabase.from("rh_positions").select("id,code,name,cbo_code,active").eq("organization_id",context.organizationId).order("code"),
context.supabase.from("rh_functions").select("id,code,name,description,active").eq("organization_id",context.organizationId).order("code"),
context.supabase.from("rh_unions").select("id,code,name,tax_id,category_name,valid_from,valid_to,active").eq("organization_id",context.organizationId).order("code"),
context.supabase.from("rh_work_schedules").select("id,code,name,weekly_hours,description,active").eq("organization_id",context.organizationId).order("code")]);
const firstError=employersResult.error??establishmentsResult.error??allocationsResult.error??positionsResult.error??functionsResult.error??unionsResult.error??schedulesResult.error;if(firstError)throw new Error(firstError.message);const employers=employersResult.data??[];const establishments=establishmentsResult.data??[];return <main className="content"><section className="page-heading"><div><span className="badge">RH · CONFIGURAÇÃO · ESTRUTURA</span><h1>Empresas e estrutura de DP</h1><p>Cadastros usados pelo vínculo, folha e projeções eSocial. Alterações futuras serão versionadas por condição do vínculo.</p></div></section>{query.error?<div className="validation blocking">{query.error}</div>:null}
<section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">EMPRESAS</span><h2>Empresa empregadora</h2></div></div><form action={createRhEmployer} className="relationship-form"><div className="form-grid"><label><span>Código *</span><input name="code" required/></label><label><span>Razão social *</span><input name="legalName" required/></label><label><span>Nome fantasia</span><input name="tradeName"/></label><label><span>CNPJ/CPF *</span><input name="taxId" required/></label></div><div className="form-actions"><button className="button button-secondary" type="submit">Adicionar empresa</button></div></form><div className="finance-list">{employers.map(e=><div className="finance-row" key={e.id}><div><strong>{e.code} · {e.legal_name}</strong><small>{e.trade_name||"—"} · {e.tax_id}</small></div><span className="badge">{e.status}</span></div>)}</div></section>
<section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">ESTABELECIMENTOS</span><h2>Inscrições de operação</h2></div></div><form action={createRhEstablishment} className="relationship-form"><div className="form-grid"><label><span>Empresa *</span><select name="employerId" required defaultValue=""><option value="" disabled>Selecione</option>{employers.map(e=><option value={e.id} key={e.id}>{e.code} · {e.legal_name}</option>)}</select></label><label><span>Código *</span><input name="code" required/></label><label><span>Nome *</span><input name="name" required/></label><label><span>Tipo inscrição</span><select name="registrationType"><option value="CNPJ">CNPJ</option><option value="CNO">CNO</option><option value="CAEPF">CAEPF</option><option value="OTHER">Outra</option></select></label><label><span>Número *</span><input name="registrationNumber" required/></label></div><div className="form-actions"><button className="button button-secondary" type="submit">Adicionar estabelecimento</button></div></form><div className="finance-list">{establishments.map(e=>{const employer=Array.isArray(e.rh_employers)?e.rh_employers[0]:e.rh_employers;return <div className="finance-row" key={e.id}><div><strong>{e.code} · {e.name}</strong><small>{employer?.code} · {e.registration_type} {e.registration_number}</small></div><span className="badge">{e.status}</span></div>})}</div></section>
<section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">LOTAÇÕES TRIBUTÁRIAS</span><h2>Lotação e mapeamento eSocial</h2></div></div><form action={createRhTaxAllocation} className="relationship-form"><div className="form-grid"><label><span>Empresa *</span><select name="employerId" required defaultValue=""><option value="" disabled>Selecione</option>{employers.map(e=><option value={e.id} key={e.id}>{e.code} · {e.legal_name}</option>)}</select></label><label><span>Estabelecimento</span><select name="establishmentId" defaultValue=""><option value="">Geral</option>{establishments.map(e=><option value={e.id} key={e.id}>{e.code} · {e.name}</option>)}</select></label><label><span>Código *</span><input name="code" required/></label><label><span>Nome *</span><input name="name" required/></label><label><span>Código eSocial</span><input name="esocialLotacaoCode"/></label><label><span>Vigência inicial *</span><input name="validFrom" type="date" required/></label><label><span>Vigência final</span><input name="validTo" type="date"/></label></div><div className="form-actions"><button className="button button-secondary" type="submit">Adicionar lotação</button></div></form><div className="finance-list">{(allocationsResult.data??[]).map(a=><div className="finance-row" key={a.id}><div><strong>{a.code} · {a.name}</strong><small>eSocial {a.esocial_lotacao_code||"não mapeado"} · {a.valid_from}{a.valid_to?` → ${a.valid_to}`:""}</small></div></div>)}</div></section>
<div className="finance-two-column"><section className="card card-pad"><span className="eyebrow">CARGOS</span><h2>Cargos/CBO</h2><form action={createRhPosition} className="relationship-form"><label><span>Código *</span><input name="code" required/></label><label><span>Nome *</span><input name="name" required/></label><label><span>CBO</span><input name="cboCode"/></label><button className="button button-secondary" type="submit">Adicionar cargo</button></form><div className="finance-list">{(positionsResult.data??[]).map(p=><div className="finance-row" key={p.id}><div><strong>{p.code} · {p.name}</strong><small>CBO {p.cbo_code||"—"}</small></div></div>)}</div></section><section className="card card-pad"><span className="eyebrow">FUNÇÕES</span><h2>Funções</h2><form action={createRhFunction} className="relationship-form"><label><span>Código *</span><input name="code" required/></label><label><span>Nome *</span><input name="name" required/></label><label><span>Descrição</span><input name="description"/></label><button className="button button-secondary" type="submit">Adicionar função</button></form><div className="finance-list">{(functionsResult.data??[]).map(f=><div className="finance-row" key={f.id}><div><strong>{f.code} · {f.name}</strong><small>{f.description||"—"}</small></div></div>)}</div></section></div>
<div className="finance-two-column"><section className="card card-pad"><span className="eyebrow">SINDICATOS</span><h2>Entidades e categorias</h2><form action={createRhUnion} className="relationship-form"><label><span>Código *</span><input name="code" required/></label><label><span>Nome *</span><input name="name" required/></label><label><span>CNPJ</span><input name="taxId"/></label><label><span>Categoria</span><input name="categoryName"/></label><label><span>Vigência inicial</span><input name="validFrom" type="date"/></label><label><span>Vigência final</span><input name="validTo" type="date"/></label><button className="button button-secondary" type="submit">Adicionar sindicato</button></form><div className="finance-list">{(unionsResult.data??[]).map(u=><div className="finance-row" key={u.id}><div><strong>{u.code} · {u.name}</strong><small>{u.category_name||"—"}</small></div></div>)}</div></section><section className="card card-pad"><span className="eyebrow">JORNADAS</span><h2>Jornadas contratuais</h2><form action={createRhWorkSchedule} className="relationship-form"><label><span>Código *</span><input name="code" required/></label><label><span>Nome *</span><input name="name" required/></label><label><span>Horas semanais *</span><input name="weeklyHours" inputMode="decimal" required/></label><label><span>Descrição</span><input name="description"/></label><button className="button button-secondary" type="submit">Adicionar jornada</button></form><div className="finance-list">{(schedulesResult.data??[]).map(s=><div className="finance-row" key={s.id}><div><strong>{s.code} · {s.name}</strong><small>{s.weekly_hours} h/semana · {s.description||"—"}</small></div></div>)}</div></section></div></main>;}
