import fs from"node:fs";
import{expect,test}from"@playwright/test";
import{createClient}from"@supabase/supabase-js";

const baseURL=(process.env.RH_E2E_BASE_URL??"").replace(/\/$/,"");const email=process.env.RH_E2E_EMAIL??"",password=process.env.RH_E2E_PASSWORD??"",seedPath=process.env.RH_E2E_SEED_FILE??"test-results/rh-e2e-seed.json";
function required(){test.skip(!baseURL||!email||!password,"RH_E2E_BASE_URL, RH_E2E_EMAIL e RH_E2E_PASSWORD são obrigatórios.");if(!fs.existsSync(seedPath))throw new Error(`Seed transacional ausente: ${seedPath}`);return JSON.parse(fs.readFileSync(seedPath,"utf8"));}
async function login(page:import("@playwright/test").Page){await page.goto(`${baseURL}/login`,{waitUntil:"domcontentloaded"});await page.locator('input[name="email"]').fill(email);await page.locator('input[name="password"]').fill(password);await Promise.all([page.waitForURL(url=>!url.pathname.startsWith("/login"),{timeout:30000}),page.getByRole("button",{name:/entrar|acessar/i}).click()]);}

test.describe("RH profissional transacional",()=>{test("lançamento, cálculo, fechamento, portal e PDF",async({page,context})=>{const seed=required();await login(page);await page.goto(`${baseURL}/app/rh/folha/competencias/${seed.periodId}`,{waitUntil:"networkidle"});await expect(page.locator("main")).toContainText(seed.workerCode);await page.locator('select[name="employmentId"]').selectOption(seed.employmentId);await page.locator('select[name="rubricVersionId"]').selectOption(seed.rubricVersionId);await page.locator('input[name="amount"]').fill("1234,56");await page.getByRole("button",{name:"Adicionar lançamento"}).click();await expect(page.locator("main")).toContainText(seed.rubricCode);await page.getByRole("button",{name:"Calcular folha"}).click();await expect(page.locator("main")).toContainText("CALCULATED",{timeout:30000});await expect(page.locator("main")).toContainText("1.234,56");await page.screenshot({path:"test-results/rh-transaction-calculated.png",fullPage:true});await page.getByRole("button",{name:"Fechar competência"}).click();await expect(page.locator("main")).toContainText("CLOSED",{timeout:30000});
 const service=process.env.SUPABASE_SERVICE_ROLE_KEY,url=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!service||!url)throw new Error("Service Role/URL necessários para preparar a publicação de recibo do harness.");const supabase=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:run,error:rError}=await supabase.from("rh_payroll_runs").select("id,run_number").eq("period_id",seed.periodId).eq("status","COMPLETED").order("run_number",{ascending:false}).limit(1).single();if(rError)throw rError;const{data:wr,error:wError}=await supabase.from("rh_payroll_worker_results").select("id").eq("run_id",run.id).eq("employment_id",seed.employmentId).single();if(wError)throw wError;await supabase.from("rh_worker_user_links").upsert({organization_id:seed.organizationId,user_id:seed.userId,worker_id:seed.workerId,active:true,valid_from:"2026-01-01",created_by:seed.userId},{onConflict:"organization_id,user_id,worker_id"});const{data:existing}=await supabase.from("rh_payslip_publications").select("id").eq("organization_id",seed.organizationId).eq("period_id",seed.periodId).eq("worker_id",seed.workerId).eq("status","PUBLISHED").limit(1).maybeSingle();let publicationId=existing?.id;if(!publicationId){const{data:publication,error:pError}=await supabase.from("rh_payslip_publications").insert({organization_id:seed.organizationId,period_id:seed.periodId,run_id:run.id,worker_result_id:wr.id,worker_id:seed.workerId,employment_id:seed.employmentId,publication_version:1,status:"PUBLISHED",published_by:seed.userId,published_at:new Date().toISOString()}).select("id").single();if(pError)throw pError;publicationId=publication.id;}
 await page.goto(`${baseURL}/app/rh/meu-rh`,{waitUntil:"networkidle"});await expect(page.locator("main")).toContainText(seed.registration);await expect(page.locator("main")).toContainText(String(seed.referenceMonth).slice(0,7));const pdfResponse=await context.request.get(`${baseURL}/api/rh/payslips/${publicationId}/pdf`);expect(pdfResponse.status()).toBe(200);expect(pdfResponse.headers()["content-type"]).toContain("application/pdf");const pdf=await pdfResponse.body();expect(pdf.subarray(0,5).toString("ascii")).toBe("%PDF-");await page.screenshot({path:"test-results/rh-transaction-portal.png",fullPage:true});});});
