import Link from "next/link";
import { notFound } from "next/navigation";
import { createQualityAssignment, createQualityTemplateVersion, publishQualityTemplate } from "@/app/actions/quality";
import { QualityFormBuilder } from "@/components/quality/quality-form-builder";
import { requireCapability } from "@/lib/authorization";
import { parseQualityFormSchema, schemaSummary } from "@/lib/quality/forms";

export const dynamic="force-dynamic";
export default async function QualityTemplateDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;share?:string;assignment?:string}>}){
  const{id}=await params;const query=await searchParams;const context=await requireCapability("qualidade","read");
  const{data:template,error}=await context.supabase.from("quality_form_templates").select("*").eq("id",id).eq("organization_id",context.organizationId).single();
  if(error||!template)notFound();
  const[{data:current},{data:versions},{data:assignments},{data:projects},{data:clients}]=await Promise.all([
    template.current_version_id?context.supabase.from("quality_form_versions").select("*").eq("id",template.current_version_id).single():Promise.resolve({data:null}),
    context.supabase.from("quality_form_versions").select("id,version_number,change_summary,frozen_at,created_at").eq("template_id",id).order("version_number",{ascending:false}),
    context.supabase.from("quality_form_assignments").select("*").in("template_version_id",(await context.supabase.from("quality_form_versions").select("id").eq("template_id",id)).data?.map((item:any)=>item.id)??[]).order("created_at",{ascending:false}),
    context.supabase.from("projects").select("id,name,client_id").eq("organization_id",context.organizationId).order("name"),
    context.supabase.from("clients").select("id,legal_name,trade_name,user_id").eq("organization_id",context.organizationId).order("legal_name")
  ]);
  const schema=current?parseQualityFormSchema(current.schema_json):null;const summary=schema?schemaSummary(schema):null;
  return <main className="content quality-app"><Link className="back-link" href="/app/qualidade/formularios">← Modelos</Link><section className="page-heading"><div><span className="badge">{template.kind} · {template.code}</span><h1>{template.title}</h1><p>{template.description}</p></div><span className={`badge ${template.status==="PUBLISHED"?"badge-success":"badge-warning"}`}>{template.status}</span></section>{query.error&&<div className="validation blocking">{query.error}</div>}{query.share&&<section className="validation quality-share"><strong>Link criado</strong><code>{query.share}</code><p>Copie agora. Por segurança, somente o hash do token foi armazenado.</p></section>}
  <div className="quality-two-column"><section><article className="card card-pad"><div className="section-heading"><div><span className="eyebrow">VERSÃO ATUAL</span><h2>V{current?.version_number??"—"}</h2></div>{current&&!current.frozen_at&&<form action={publishQualityTemplate}><input type="hidden" name="templateId" value={id}/><input type="hidden" name="versionId" value={current.id}/><button className="button button-primary">Publicar e congelar</button></form>}</div>{summary&&<div className="stats-grid quality-summary"><article><small>CAMPOS</small><strong>{summary.fields}</strong></article><article><small>OBRIGATÓRIOS</small><strong>{summary.required}</strong></article><article><small>CHECKLISTS</small><strong>{summary.checklistItems}</strong></article><article><small>UPLOADS</small><strong>{summary.uploadFields}</strong></article></div>}<div className="quality-field-summary">{schema?.fields.map(field=><div key={field.key}><span className="badge">{field.type}</span><strong>{field.label}</strong><small>{field.required?"Obrigatório":"Opcional"}</small></div>)}</div></article>
  {schema&&<details className="card card-pad quality-version-editor"><summary><strong>Criar nova versão a partir da atual</strong></summary><QualityFormBuilder action={createQualityTemplateVersion} mode="version" templateId={id} initialSchema={schema}/></details>}
  <section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">DISTRIBUIÇÕES</span><h2>Formulários enviados</h2></div></div><div className="quality-assignment-list">{(assignments??[]).map((assignment:any)=><Link key={assignment.id} href={`/app/qualidade/preenchimentos/${assignment.id}`}><div><strong>{assignment.title}</strong><small>{assignment.status} · {assignment.responses_count}/{assignment.max_responses} resposta(s)</small></div><span>{assignment.due_at?new Date(assignment.due_at).toLocaleDateString("pt-BR"):"Sem prazo"}</span></Link>)}{!assignments?.length&&<p className="muted">Nenhuma distribuição criada.</p>}</div></section></section>
  <aside><form action={createQualityAssignment} className="card card-pad quality-distribution-form"><input type="hidden" name="templateId" value={id}/><span className="eyebrow">DISTRIBUIR</span><h2>Novo preenchimento</h2><label>Título<input name="assignmentTitle" defaultValue={template.title} required/></label><label>Instruções<textarea name="instructions" rows={3}/></label><label>Obra<select name="projectId"><option value="">Sem obra</option>{(projects??[]).map((project:any)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Cliente<select name="clientId"><option value="">Público ou interno</option>{(clients??[]).map((client:any)=><option key={client.id} value={client.id}>{client.trade_name||client.legal_name}</option>)}</select></label><label>Usuário do cliente<select name="assigneeUserId"><option value="">Não vincular usuário</option>{(clients??[]).filter((client:any)=>client.user_id).map((client:any)=><option key={client.user_id} value={client.user_id}>{client.trade_name||client.legal_name}</option>)}</select></label><div className="quality-grid quality-grid-2"><label>Vencimento<input type="datetime-local" name="dueAt"/></label><label>Expiração do link<input type="datetime-local" name="expiresAt"/></label></div><label>Máximo de respostas<input type="number" min="1" max="10000" name="maxResponses" defaultValue={template.kind==="SURVEY"?100:1}/></label><button className="button button-primary">Criar e gerar link</button></form><section className="card card-pad"><h2>Histórico de versões</h2><div className="quality-version-list">{(versions??[]).map((version:any)=><div key={version.id}><strong>V{version.version_number}</strong><span>{version.frozen_at?"Publicada":"Rascunho"}</span><small>{version.change_summary||"Sem resumo"}</small></div>)}</div></section></aside></div></main>;
}
