import{createHash}from"node:crypto";
import{NextResponse}from"next/server";
import{PDFDocument,StandardFonts,rgb}from"pdf-lib";
import{requireOrganizationContext}from"@/lib/auth";

type PayslipLine={code:string;name:string;kind:string;quantity:number|string|null;baseAmount:number|string|null;amount:number|string};
type PayslipData={publicationId:string;publicationVersion:number;referenceMonth:string;processingType:string;payDate:string|null;registrationNumber:string;workerName:string;workerFullName:string;cpf:string|null;grossAmount:number|string;deductionAmount:number|string;netAmount:number|string;lines:PayslipLine[]};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
function clean(value:unknown){return String(value??"").replace(/[\u2012-\u2015]/g,"-").replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g,"?");}
function cpf(value:string|null){const d=String(value??"").replace(/\D/g,"");return d.length===11?`${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6,9)}-${d.slice(9)}`:"-";}
function month(value:string){const s=String(value).slice(0,7);return /^\d{4}-\d{2}$/.test(s)?`${s.slice(5,7)}/${s.slice(0,4)}`:s;}

export async function GET(_request:Request,{params}:{params:Promise<{publicationId:string}>}){const{publicationId}=await params,context=await requireOrganizationContext();const{data,error}=await context.supabase.rpc("get_rh_payslip_pdf_data",{p_publication_id:publicationId});if(error||!data)return NextResponse.json({error:error?.message??"Recibo não disponível."},{status:error?.message?.includes("FORBIDDEN")?403:404});const d=data as PayslipData;const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);let page=doc.addPage([595.28,841.89]),y=800;const margin=42,width=511;const text=(s:string,x:number,yy:number,size=9,b=false)=>page.drawText(clean(s),{x,y:yy,size,font:b?bold:font,color:rgb(0.08,0.08,0.08)});const line=(yy:number)=>page.drawLine({start:{x:margin,y:yy},end:{x:margin+width,y:yy},thickness:.5,color:rgb(.75,.75,.75)});const newPage=()=>{page=doc.addPage([595.28,841.89]);y=800;};
 text("RECIBO DE PAGAMENTO",margin,y,15,true);text(`Competência ${month(d.referenceMonth)} - ${d.processingType}`,margin,y-22,10);text(`Publicação v${d.publicationVersion}`,430,y,8);y-=48;line(y);y-=20;text(`Trabalhador: ${d.workerFullName||d.workerName}`,margin,y,10,true);text(`Matrícula: ${d.registrationNumber}`,360,y,9);y-=18;text(`CPF: ${cpf(d.cpf)}`,margin,y,9);text(`Pagamento: ${d.payDate??"-"}`,360,y,9);y-=24;line(y);y-=20;
 text("Rubrica",margin,y,8,true);text("Descrição",105,y,8,true);text("Qtd.",350,y,8,true);text("Provento",405,y,8,true);text("Desconto",490,y,8,true);y-=12;line(y);y-=15;
 for(const row of d.lines??[]){if(y<110){newPage();text("RECIBO DE PAGAMENTO - continuação",margin,y,11,true);y-=28;text("Rubrica",margin,y,8,true);text("Descrição",105,y,8,true);text("Qtd.",350,y,8,true);text("Provento",405,y,8,true);text("Desconto",490,y,8,true);y-=12;line(y);y-=15;}const amount=Number(row.amount);text(row.code,margin,y,8);text(clean(row.name).slice(0,38),105,y,8);text(row.quantity==null?"-":String(row.quantity),350,y,8);if(row.kind==="EARNING")text(money.format(amount),405,y,8);else if(row.kind==="DEDUCTION")text(money.format(amount),490,y,8);else text(money.format(amount),405,y,8);y-=17;}
 y-=4;line(y);y-=23;text(`Total de proventos: ${money.format(Number(d.grossAmount))}`,margin,y,10,true);text(`Total de descontos: ${money.format(Number(d.deductionAmount))}`,300,y,10,true);y-=24;text(`Líquido: ${money.format(Number(d.netAmount))}`,margin,y,13,true);y-=34;text("Documento gerado a partir de publicação controlada da folha. Consulte a memória de cálculo no sistema para rastreabilidade.",margin,y,7);text(`ID: ${d.publicationId}`,margin,y-14,7);
 const bytes=Buffer.from(await doc.save()),hash=createHash("sha256").update(bytes).digest("hex"),fileName=`recibo-${d.registrationNumber}-${String(d.referenceMonth).slice(0,7)}.pdf`;return new NextResponse(bytes,{status:200,headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="${fileName}"`,"Cache-Control":"no-store, private","X-Content-SHA256":hash}});}
