"use client";

import{useMemo,useState}from"react";
import{createInventoryReservation}from"@/app/actions/inventory";

type Warehouse={id:string;name:string;project_id:string|null;inventory_locations:{id:string;name:string}[]};
type Item={id:string;code:string;name:string;controls_lot:boolean;inventory_units:{code:string}|null;inventory_lots:{id:string;batch_number:string}[]};
type Project={id:string;code:string;name:string};
type Line={itemId:string;locationId:string;lotId:string;quantity:string;notes:string};
const empty:Line={itemId:"",locationId:"",lotId:"",quantity:"1",notes:""};

export function InventoryReservationForm({warehouses,items,projects}:{warehouses:Warehouse[];items:Item[];projects:Project[]}){
 const[warehouseId,setWarehouseId]=useState("");const[lines,setLines]=useState<Line[]>([{...empty}]);
 const warehouse=warehouses.find(value=>value.id===warehouseId);
 const serialized=useMemo(()=>lines.map(line=>({itemId:line.itemId,locationId:line.locationId,lotId:line.lotId||null,quantity:Number(line.quantity),notes:line.notes})),[lines]);
 function update(index:number,patch:Partial<Line>){setLines(current=>current.map((line,i)=>i===index?{...line,...patch}:line));}
 return <form action={createInventoryReservation} className="card card-pad inventory-form"><div className="form-grid form-grid-2"><label>Obra<select name="projectId" required><option value="">Selecione</option>{projects.map(project=><option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></label><label>Depósito<select name="warehouseId" value={warehouseId} onChange={event=>{setWarehouseId(event.target.value);setLines(current=>current.map(line=>({...line,locationId:""})));}} required><option value="">Selecione</option>{warehouses.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label>Necessidade<input type="date" name="neededBy"/></label><label>Expiração<input type="datetime-local" name="expiresAt"/></label><label>Chave de idempotência<input name="idempotencyKey" placeholder="Opcional"/></label></div><label>Motivo<textarea name="reason" rows={3}/></label><div className="section-heading"><div><span className="eyebrow">ITENS RESERVADOS</span><h2>Quantidade por localização</h2></div><button type="button" className="button button-secondary" onClick={()=>setLines(current=>[...current,{...empty}])}>Adicionar item</button></div><div className="inventory-line-list">{lines.map((line,index)=>{const item=items.find(value=>value.id===line.itemId);return <article className="inventory-line" key={index}><div className="form-grid form-grid-3"><label>Item<select value={line.itemId} onChange={event=>update(index,{itemId:event.target.value,lotId:""})} required><option value="">Selecione</option>{items.map(value=><option key={value.id} value={value.id}>{value.code} · {value.name}</option>)}</select></label><label>Localização<select value={line.locationId} onChange={event=>update(index,{locationId:event.target.value})} required><option value="">Selecione</option>{(warehouse?.inventory_locations??[]).map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label>{item?.controls_lot&&<label>Lote<select value={line.lotId} onChange={event=>update(index,{lotId:event.target.value})} required><option value="">Selecione</option>{item.inventory_lots.map(value=><option key={value.id} value={value.id}>{value.batch_number}</option>)}</select></label>}<label>Quantidade ({item?.inventory_units?.code??"un"})<input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={event=>update(index,{quantity:event.target.value})} required/></label><label>Observação<input value={line.notes} onChange={event=>update(index,{notes:event.target.value})}/></label></div>{lines.length>1&&<button type="button" className="text-link danger-link" onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}>Remover linha</button>}</article>})}</div><input type="hidden" name="linesJson" value={JSON.stringify(serialized)}/><button className="button button-primary">Ativar reserva</button></form>;
}
