import{mensagemDeFalha}from"@/lib/errors/data-access";
import Link from"next/link";
import{createEsocialBatch}from"@/app/actions/rh-esocial";
import{requireCapability}from"@/lib/authorization";
import{esocialConfigurationStatus}from"@/lib/rh/integrations/government";

export const dynamic="force-dynamic";
export default async function EsocialQueuePage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const context=await requireCapability("rh","read");const query=await searchParams;const config=esocialConfigurationStatus();
 const[{data:events,error:eError},{data:batches,error:bError}]=await Promise.all([
  context.supabase.from("rh_esocial_events").select("id,event_type,event_key,event_group,operation,environment,layout_version,status,payload_sha256,receipt_number,response_code,response_description,created_at").eq("organization_id",context.organizationId).order("created_at",{ascending:false}).limit(100),
  context.supabase.from("rh_esocial_batches").select("id,environment,event_group,status,protocol_number,response_code,response_description,created_at,sent_at,completed_at,rh_esocial_batch_events(event_id)").eq("organization_id",context.organizationId).order("created_at",{ascending:false}).limit(50)
 ]);
 if(eError||bError)throw new Error(mensagemDeFalha("app.rh.obrigacoes.esocial.EsocialQueuePage", eError)??mensagemDeFalha("app.rh.obrigacoes.esocial.EsocialQueuePage", bError, "Falha ao carregar eSocial."));const selectable=(events??[]).filter(item=>["SIGNED","QUEUED"].includes(item.status));
 return <main className="content"><section className="page-heading"><div><span className="badge">OBRIGAÇÕES · ESOCIAL</span><h1>Fila eSocial</h1><p>Eventos individualmente assinados, lotes homogêneos, transmissão oficial e consulta de protocolo.</p></div><div className="page-actions"><Link className="button button-secondary" href="/app/rh/configuracao">Configuração</Link><Link className="button button-primary" href="/app/rh/obrigacoes/esocial/novo">Registrar XML assinado</Link></div></section>{query.error?<div className="validation blocking">{query.error}</div>:null}{query.success?<div className="alert alert-success">{query.success}</div>:null}
 <section className="stats-grid"><article className="card"><small>EVENTOS DISPONÍVEIS</small><strong>{selectable.length}</strong><span>assinados/na fila</span></article><article className="card"><small>LOTES</small><strong>{batches?.length??0}</strong><span>histórico carregado</span></article><article className="card"><small>CERTIFICADO</small><strong>{config.certificateConfigured&&config.privateKeyConfigured?"OK":"—"}</strong><span>{config.certificateConfigured?"configurado no servidor":"não configurado"}</span></article><article className="card"><small>PRODUÇÃO</small><strong>{config.productionEnabled?"ON":"OFF"}</strong><span>bloqueada por padrão</span></article></section>
 <section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">NOVO LOTE</span><h2>Selecionar eventos compatíveis</h2></div></div><p>O banco exige o mesmo ambiente, empregador, transmissor e grupo e limita o lote a 50 eventos.</p><form action={createEsocialBatch} className="relationship-form"><div style={{overflowX:"auto"}}><table className="data-table"><thead><tr><th></th><th>Evento</th><th>Grupo</th><th>Ambiente</th><th>Layout</th><th>Hash</th></tr></thead><tbody>{selectable.map(item=><tr key={item.id}><td><input type="checkbox" name="eventIds" value={item.id} aria-label={`Selecionar ${item.event_key}`}/></td><td><Link className="text-link" href={`/app/rh/obrigacoes/esocial/eventos/${item.id}`}><strong>{item.event_type}</strong></Link><small style={{display:"block"}}>{item.event_key}</small></td><td>{item.event_group}</td><td><span className="badge">{item.environment}</span></td><td>{item.layout_version}</td><td><code>{item.payload_sha256.slice(0,12)}…</code></td></tr>)}{!selectable.length?<tr><td colSpan={6}><div className="empty-state"><h3>Sem eventos disponíveis</h3><p>Registre um XML de evento já assinado para formar um lote.</p></div></td></tr>:null}</tbody></table></div><div className="form-actions"><button className="button button-primary" type="submit" disabled={!selectable.length}>Criar lote</button></div></form></section>
 <section className="card" style={{overflowX:"auto"}}><div className="section-heading card-pad"><div><span className="eyebrow">LOTES</span><h2>Transmissões e processamento</h2></div></div><table className="data-table"><thead><tr><th>Criado</th><th>Ambiente</th><th>Grupo</th><th>Eventos</th><th>Protocolo</th><th>Status</th><th>Retorno</th></tr></thead><tbody>{(batches??[]).map(batch=><tr key={batch.id}><td><Link className="text-link" href={`/app/rh/obrigacoes/esocial/lotes/${batch.id}`}>{String(batch.created_at).replace("T"," ").slice(0,16)}</Link></td><td>{batch.environment}</td><td>{batch.event_group}</td><td>{Array.isArray(batch.rh_esocial_batch_events)?batch.rh_esocial_batch_events.length:0}</td><td>{batch.protocol_number??"—"}</td><td><span className="badge">{batch.status}</span></td><td><small>{batch.response_code??"—"}{batch.response_description?` · ${batch.response_description}`:""}</small></td></tr>)}{!batches?.length?<tr><td colSpan={7}><div className="empty-state"><h3>Nenhum lote</h3><p>Os lotes enviados e consultados aparecerão aqui.</p></div></td></tr>:null}</tbody></table></section>
 </main>;
}
