import{createEsocialEmployerProfile,createEsocialEstablishmentProfile,createEsocialTaxAllocationProfile,configureEsocialRubricVersion}from"@/app/actions/rh-esocial-config";
import{requireCapability}from"@/lib/authorization";

export const dynamic="force-dynamic";
export default async function RhEsocialConfigurationPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 const context=await requireCapability("rh","configure");const query=await searchParams;
 const[{data:employers},{data:establishments},{data:allocations},{data:rubricVersions},{data:rubrics},{data:employerProfiles},{data:estProfiles},{data:allocationProfiles}]=await Promise.all([
  context.supabase.from("rh_employers").select("id,code,legal_name").eq("organization_id",context.organizationId).order("code"),
  context.supabase.from("rh_establishments").select("id,code,name").eq("organization_id",context.organizationId).order("code"),
  context.supabase.from("rh_tax_allocations").select("id,code,name").eq("organization_id",context.organizationId).order("code"),
  context.supabase.from("rh_rubric_versions").select("id,rubric_id,version,valid_from,esocial_nature_code,cod_inc_cp,cod_inc_irrf,cod_inc_fgts,esocial_table_code,esocial_rubric_type").eq("organization_id",context.organizationId).eq("status","PUBLISHED").order("valid_from",{ascending:false}),
  context.supabase.from("rh_rubrics").select("id,code,name").eq("organization_id",context.organizationId).order("code"),
  context.supabase.from("rh_esocial_employer_profiles").select("id,employer_id,valid_from,valid_to,class_trib").eq("organization_id",context.organizationId).order("valid_from",{ascending:false}),
  context.supabase.from("rh_esocial_establishment_profiles").select("id,establishment_id,valid_from,valid_to,cnae_preponderant,rat_rate,fap").eq("organization_id",context.organizationId).order("valid_from",{ascending:false}),
  context.supabase.from("rh_esocial_tax_allocation_profiles").select("id,tax_allocation_id,valid_from,valid_to,lotacao_type,fpas_code,third_parties_code").eq("organization_id",context.organizationId).order("valid_from",{ascending:false})
 ]);
 const employerMap=new Map((employers??[]).map(x=>[x.id,`${x.code} · ${x.legal_name}`]));const estMap=new Map((establishments??[]).map(x=>[x.id,`${x.code} · ${x.name}`]));const allocationMap=new Map((allocations??[]).map(x=>[x.id,`${x.code} · ${x.name}`]));const rubricMap=new Map((rubrics??[]).map(x=>[x.id,`${x.code} · ${x.name}`]));
 return <main className="content"><section className="page-heading"><div><span className="badge">RH · CONFIGURAÇÃO · ESOCIAL</span><h1>Parametrização eSocial S-1.3</h1><p>Dados mestres usados pelos geradores automáticos. Vigência é preservada e sobreposição é bloqueada.</p></div></section>{query.error?<div className="validation blocking">{query.error}</div>:null}
 <section className="card card-pad"><span className="eyebrow">S-1000</span><h2>Perfil do empregador</h2><form action={createEsocialEmployerProfile} className="relationship-form"><div className="form-grid"><label><span>Empregador *</span><select name="employerId" required defaultValue=""><option value="" disabled>Selecione</option>{(employers??[]).map(e=><option value={e.id} key={e.id}>{e.code} · {e.legal_name}</option>)}</select></label><label><span>Vigência inicial *</span><input name="validFrom" type="date" required/></label><label><span>Vigência final</span><input name="validTo" type="date"/></label><label><span>Classificação tributária *</span><input name="classTrib" required/></label><label><span>Cooperativa</span><input name="indCoop" type="number" defaultValue="0" min="0" max="3"/></label><label><span>Construtora</span><input name="indConstr" type="number" defaultValue="0" min="0" max="2"/></label><label><span>Desoneração folha</span><input name="indDesFolha" type="number" defaultValue="0" min="0" max="1"/></label><label><span>Registro eletrônico</span><input name="indOptRegEletron" type="number" defaultValue="1" min="0" max="1"/></label><label><span>Entidade educativa</span><input name="indEntEd" type="number" defaultValue="0" min="0" max="1"/></label><label><span>Empresa trabalho temporário</span><input name="indEtt" type="number" defaultValue="0" min="0" max="1"/></label></div><button className="button button-primary" type="submit">Salvar perfil S-1000</button></form><div className="finance-list">{(employerProfiles??[]).map(p=><div className="finance-row" key={p.id}><div><strong>{employerMap.get(p.employer_id)??p.employer_id}</strong><small>{p.valid_from}{p.valid_to?` → ${p.valid_to}`:""} · classe {p.class_trib}</small></div></div>)}</div></section>
 <section className="card card-pad"><span className="eyebrow">S-1005</span><h2>Perfil do estabelecimento</h2><form action={createEsocialEstablishmentProfile} className="relationship-form"><div className="form-grid"><label><span>Estabelecimento *</span><select name="establishmentId" required defaultValue=""><option value="" disabled>Selecione</option>{(establishments??[]).map(e=><option value={e.id} key={e.id}>{e.code} · {e.name}</option>)}</select></label><label><span>Vigência inicial *</span><input name="validFrom" type="date" required/></label><label><span>Vigência final</span><input name="validTo" type="date"/></label><label><span>CNAE preponderante *</span><input name="cnaePreponderant" required/></label><label><span>Alíquota RAT</span><input name="ratRate" inputMode="decimal"/></label><label><span>FAP</span><input name="fap" inputMode="decimal"/></label></div><button className="button button-primary" type="submit">Salvar perfil S-1005</button></form><div className="finance-list">{(estProfiles??[]).map(p=><div className="finance-row" key={p.id}><div><strong>{estMap.get(p.establishment_id)??p.establishment_id}</strong><small>{p.valid_from}{p.valid_to?` → ${p.valid_to}`:""} · CNAE {p.cnae_preponderant} · RAT {p.rat_rate??"—"} · FAP {p.fap??"—"}</small></div></div>)}</div></section>
 <section className="card card-pad"><span className="eyebrow">S-1020</span><h2>Perfil da lotação tributária</h2><form action={createEsocialTaxAllocationProfile} className="relationship-form"><div className="form-grid"><label><span>Lotação *</span><select name="taxAllocationId" required defaultValue=""><option value="" disabled>Selecione</option>{(allocations??[]).map(a=><option value={a.id} key={a.id}>{a.code} · {a.name}</option>)}</select></label><label><span>Vigência inicial *</span><input name="validFrom" type="date" required/></label><label><span>Vigência final</span><input name="validTo" type="date"/></label><label><span>Tipo de lotação *</span><input name="lotacaoType" required/></label><label><span>FPAS *</span><input name="fpasCode" required/></label><label><span>Código terceiros</span><input name="thirdPartiesCode"/></label></div><button className="button button-primary" type="submit">Salvar perfil S-1020</button></form><div className="finance-list">{(allocationProfiles??[]).map(p=><div className="finance-row" key={p.id}><div><strong>{allocationMap.get(p.tax_allocation_id)??p.tax_allocation_id}</strong><small>{p.valid_from}{p.valid_to?` → ${p.valid_to}`:""} · tipo {p.lotacao_type} · FPAS {p.fpas_code} · terceiros {p.third_parties_code??"—"}</small></div></div>)}</div></section>
 <section className="card card-pad"><span className="eyebrow">S-1010</span><h2>Complemento da versão de rubrica</h2><p>Natureza e incidências continuam na própria versão da rubrica; aqui são definidos a tabela e o tipo externo.</p><form action={configureEsocialRubricVersion} className="relationship-form"><div className="form-grid"><label><span>Versão *</span><select name="rubricVersionId" required defaultValue=""><option value="" disabled>Selecione</option>{(rubricVersions??[]).map(v=><option key={v.id} value={v.id}>{rubricMap.get(v.rubric_id)??v.rubric_id} · v{v.version} · {v.valid_from}</option>)}</select></label><label><span>ideTabRubr *</span><input name="tableCode" required/></label><label><span>tpRubr *</span><select name="rubricType" defaultValue="1"><option value="1">1 — Vencimento/provento</option><option value="2">2 — Desconto</option><option value="3">3 — Informativa</option><option value="4">4 — Informativa dedutora</option></select></label></div><button className="button button-primary" type="submit">Configurar S-1010</button></form></section>
 </main>;
}
