import{MetricCard}from"@/components/reports/metric-card";
import{ReportNavigation}from"@/components/reports/report-navigation";
import{evaluateMetric,formatReportNumber,targetFor}from"@/lib/reports/metrics";
import{loadReportDashboard}from"@/lib/reports/server";

export const dynamic="force-dynamic";

export default async function ReportsQualityPage(){
 const{dashboard}=await loadReportDashboard({});const responses=dashboard.projects.reduce((sum,row)=>sum+row.quality_responses,0);const approved=dashboard.projects.reduce((sum,row)=>sum+row.quality_approved,0);const rejected=dashboard.projects.reduce((sum,row)=>sum+row.quality_rejected,0);const pending=dashboard.projects.reduce((sum,row)=>sum+row.pending_quality_reviews,0);const assignments=dashboard.projects.reduce((sum,row)=>sum+row.pending_quality_assignments,0);
 return <main className="content reports-app"><section className="page-heading"><div><span className="badge">RELATÓRIOS · QUALIDADE</span><h1>Indicadores de Qualidade</h1><p>FVS, FVM, formulários, conformidade, revisões e satisfação.</p></div></section><ReportNavigation/><section className="stats-grid report-stats"><MetricCard label="CONFORMIDADE MÉDIA" value={formatReportNumber(dashboard.executive.averageQualityScore,"percent")} detail={`${responses} resposta(s) avaliadas`} health={evaluateMetric(dashboard.executive.averageQualityScore,targetFor(dashboard.targets,"average_quality_score"))}/><MetricCard label="APROVADAS" value={formatReportNumber(approved)} detail="respostas aprovadas"/><MetricCard label="REJEITADAS" value={formatReportNumber(rejected)} detail="exigem correção" health={rejected>0?"WARNING":"OK"}/><MetricCard label="EM REVISÃO" value={formatReportNumber(pending)} detail="aguardando parecer"/><MetricCard label="ATRIBUIÇÕES ABERTAS" value={formatReportNumber(assignments)} detail="FVS/FVM e formulários"/><MetricCard label="NPS" value={formatReportNumber(dashboard.executive.nps,"score")} detail="pesquisas de satisfação" health={evaluateMetric(dashboard.executive.nps,targetFor(dashboard.targets,"nps"))}/></section><section className="card card-pad report-table-wrap"><table className="data-table"><thead><tr><th>Obra</th><th>Conformidade</th><th>Respostas</th><th>Aprovadas</th><th>Rejeitadas</th><th>Revisões</th><th>Atribuições abertas</th><th>NPS</th></tr></thead><tbody>{dashboard.projects.map(project=>{const qualityHealth=evaluateMetric(project.average_quality_score,targetFor(dashboard.targets,"average_quality_score",project.project_id));return <tr key={project.project_id}><td><strong>{project.code} · {project.name}</strong></td><td><span className={`report-health-text report-health-${qualityHealth.toLowerCase()}`}>{formatReportNumber(project.average_quality_score,"percent")}</span></td><td>{project.quality_responses}</td><td>{project.quality_approved}</td><td>{project.quality_rejected}</td><td>{project.pending_quality_reviews}</td><td>{project.pending_quality_assignments}</td><td>{formatReportNumber(project.nps,"score")}</td></tr>})}</tbody></table>{!dashboard.projects.length&&<div className="empty-state"><h3>Sem indicadores de qualidade</h3><p>Distribua e preencha formulários para formar a análise.</p></div>}</section></main>;
}
