import{saveSignedEsocialEvent}from"@/app/actions/rh-esocial";
import{requireCapability}from"@/lib/authorization";
import{esocialConfigurationStatus}from"@/lib/rh/integrations/government";

export const dynamic="force-dynamic";
export default async function NewEsocialSignedEventPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 await requireCapability("rh","update");const query=await searchParams;const config=esocialConfigurationStatus();
 return <main className="content"><section className="page-heading"><div><span className="badge">ESOCIAL · NOVO EVENTO</span><h1>Registrar evento assinado</h1><p>O evento deve chegar já validado contra o XSD vigente e assinado individualmente com XMLDSig.</p></div></section>{query.error?<div className="validation blocking">{query.error}</div>:null}
 <section className="card card-pad"><div className="validation"><strong>Etapa atual do adapter:</strong> transporte mTLS, lote, protocolo e consulta já estão em código; a geração automática e a assinatura XMLDSig dos eventos a partir dos domínios RH entram na próxima fatia. Esta tela existe para homologar o transporte com XML assinado por ferramenta/processo confiável, sem fingir que a assinatura já foi automatizada.</div><dl className="detail-list"><div><dt>Certificado no servidor</dt><dd>{config.certificateConfigured?"configurado":"não configurado"}</dd></div><div><dt>Chave/PFX</dt><dd>{config.privateKeyConfigured?"configurado":"não configurado"}</dd></div><div><dt>Produção</dt><dd>{config.productionEnabled?"habilitada":"bloqueada"}</dd></div></dl></section>
 <form action={saveSignedEsocialEvent} className="card card-pad relationship-form"><div className="form-grid"><label><span>Tipo do evento *</span><input name="eventType" required placeholder="S-1010"/></label><label><span>Grupo *</span><select name="eventGroup" defaultValue="1"><option value="1">1 — Tabelas</option><option value="2">2 — Não periódicos</option><option value="3">3 — Periódicos</option></select></label><label><span>Operação</span><select name="operation" defaultValue="INCLUDE"><option value="INCLUDE">Inclusão</option><option value="RECTIFY">Retificação</option><option value="DELETE">Exclusão</option></select></label><label><span>Ambiente</span><select name="environment" defaultValue="RESTRICTED"><option value="RESTRICTED">Produção Restrita</option><option value="PRODUCTION" disabled={!config.productionEnabled}>Produção</option></select></label><label><span>Versão do leiaute *</span><input name="layoutVersion" required placeholder="S-1.3 / evento vigente"/></label><label><span>Chave do evento</span><input name="eventKey" placeholder="Opcional; validada contra Id do XML"/></label><label><span>Tipo inscrição empregador *</span><select name="employerRegistrationType" defaultValue="1"><option value="1">1 — CNPJ</option><option value="2">2 — CPF</option></select></label><label><span>Inscrição empregador *</span><input name="employerRegistrationNumber" required/></label><label><span>Tipo inscrição transmissor *</span><select name="transmitterRegistrationType" defaultValue="1"><option value="1">1 — CNPJ</option><option value="2">2 — CPF</option></select></label><label><span>Inscrição transmissor *</span><input name="transmitterRegistrationNumber" required/></label><label><span>Origem</span><input name="sourceType" defaultValue="MANUAL_SIGNED_XML"/></label><label className="span-2"><span>XML individual assinado *</span><textarea name="signedXml" required rows={18} spellCheck={false} placeholder={'<eSocial xmlns="http://www.esocial.gov.br/schema/evt/...">...<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">...</Signature></eSocial>'}/></label></div><div className="form-actions"><button className="button button-primary" type="submit">Validar e registrar evento</button></div></form>
 </main>;
}
