import{saveSignedEsocialEvent}from"@/app/actions/rh-esocial";
import{generateSignedEsocialTableEvent}from"@/app/actions/rh-esocial-generation";
import{requireCapability}from"@/lib/authorization";
import{esocialConfigurationStatus}from"@/lib/rh/integrations/government";

export const dynamic="force-dynamic";
export default async function NewEsocialSignedEventPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 const context=await requireCapability("rh","update");const query=await searchParams;const config=esocialConfigurationStatus();
 const[{data:employers},{data:employerProfiles},{data:establishments},{data:estProfiles},{data:allocations},{data:allocationProfiles},{data:rubricVersions},{data:rubrics}]=await Promise.all([
  context.supabase.from("rh_employers").select("id,code,legal_name").eq("organization_id",context.organizationId).eq("status","ACTIVE").order("code"),
  context.supabase.from("rh_esocial_employer_profiles").select("id,employer_id,valid_from,class_trib").eq("organization_id",context.organizationId).order("valid_from",{ascending:false}),
  context.supabase.from("rh_establishments").select("id,code,name").eq("organization_id",context.organizationId).eq("status","ACTIVE").order("code"),
  context.supabase.from("rh_esocial_establishment_profiles").select("id,establishment_id,valid_from,cnae_preponderant").eq("organization_id",context.organizationId).order("valid_from",{ascending:false}),
  context.supabase.from("rh_tax_allocations").select("id,code,name").eq("organization_id",context.organizationId).order("code"),
  context.supabase.from("rh_esocial_tax_allocation_profiles").select("id,tax_allocation_id,valid_from,lotacao_type").eq("organization_id",context.organizationId).order("valid_from",{ascending:false}),
  context.supabase.from("rh_rubric_versions").select("id,rubric_id,version,valid_from,esocial_nature_code,esocial_table_code,esocial_rubric_type").eq("organization_id",context.organizationId).eq("status","PUBLISHED").order("valid_from",{ascending:false}),
  context.supabase.from("rh_rubrics").select("id,code,name").eq("organization_id",context.organizationId).eq("active",true).order("code")
 ]);
 const empMap=new Map((employers??[]).map(item=>[item.id,`${item.code} · ${item.legal_name}`]));
 const estMap=new Map((establishments??[]).map(item=>[item.id,`${item.code} · ${item.name}`]));
 const allocMap=new Map((allocations??[]).map(item=>[item.id,`${item.code} · ${item.name}`]));
 const rubMap=new Map((rubrics??[]).map(item=>[item.id,`${item.code} · ${item.name}`]));
 const signingReady=config.signingConfigured;
 return <main className="content"><section className="page-heading"><div><span className="badge">ESOCIAL · NOVO EVENTO</span><h1>Gerar, assinar e registrar</h1><p>Eventos de tabela são projetados dos cadastros canônicos e assinados no servidor. XML manual continua disponível somente como fallback controlado.</p></div></section>{query.error?<div className="validation blocking">{query.error}</div>:null}
 <section className="card card-pad"><dl className="detail-list"><div><dt>Assinatura XMLDSig</dt><dd>{signingReady?"configurada":"bloqueada — configure certificado/chave PEM"}</dd></div><div><dt>mTLS</dt><dd>{config.certificateConfigured&&config.privateKeyConfigured?"configurado":"não configurado"}</dd></div><div><dt>Produção</dt><dd>{config.productionEnabled?"habilitada":"bloqueada"}</dd></div></dl><p>Produção continua bloqueada por padrão. A geração automática não substitui a validação XSD nem a homologação em Produção Restrita.</p></section>
 <section className="finance-launch-grid">
  <form action={generateSignedEsocialTableEvent} className="card card-pad relationship-form"><input type="hidden" name="eventType" value="S-1000"/><h2>S-1000 · Empregador</h2><label><span>Perfil vigente *</span><select name="sourceId" required defaultValue=""><option value="" disabled>Selecione</option>{(employerProfiles??[]).map(p=><option key={p.id} value={p.id}>{empMap.get(p.employer_id)??p.employer_id} · {p.valid_from} · classe {p.class_trib}</option>)}</select></label><label><span>Ambiente</span><select name="environment" defaultValue="RESTRICTED"><option value="RESTRICTED">Produção Restrita</option><option value="PRODUCTION" disabled={!config.productionEnabled}>Produção</option></select></label><input type="hidden" name="operation" value="INCLUDE"/><button className="button button-primary" type="submit" disabled={!signingReady}>Gerar + assinar S-1000</button></form>
  <form action={generateSignedEsocialTableEvent} className="card card-pad relationship-form"><input type="hidden" name="eventType" value="S-1005"/><h2>S-1005 · Estabelecimento</h2><label><span>Perfil vigente *</span><select name="sourceId" required defaultValue=""><option value="" disabled>Selecione</option>{(estProfiles??[]).map(p=><option key={p.id} value={p.id}>{estMap.get(p.establishment_id)??p.establishment_id} · {p.valid_from} · CNAE {p.cnae_preponderant}</option>)}</select></label><label><span>Ambiente</span><select name="environment" defaultValue="RESTRICTED"><option value="RESTRICTED">Produção Restrita</option><option value="PRODUCTION" disabled={!config.productionEnabled}>Produção</option></select></label><input type="hidden" name="operation" value="INCLUDE"/><button className="button button-primary" type="submit" disabled={!signingReady}>Gerar + assinar S-1005</button></form>
  <form action={generateSignedEsocialTableEvent} className="card card-pad relationship-form"><input type="hidden" name="eventType" value="S-1010"/><h2>S-1010 · Rubrica</h2><label><span>Empregador *</span><select name="employerId" required defaultValue=""><option value="" disabled>Selecione</option>{(employers??[]).map(e=><option key={e.id} value={e.id}>{e.code} · {e.legal_name}</option>)}</select></label><label><span>Versão de rubrica *</span><select name="sourceId" required defaultValue=""><option value="" disabled>Selecione</option>{(rubricVersions??[]).map(v=><option key={v.id} value={v.id}>{rubMap.get(v.rubric_id)??v.rubric_id} · v{v.version} · {v.valid_from}{v.esocial_nature_code?` · nat. ${v.esocial_nature_code}`:" · parametrização incompleta"}</option>)}</select></label><label><span>Ambiente</span><select name="environment" defaultValue="RESTRICTED"><option value="RESTRICTED">Produção Restrita</option><option value="PRODUCTION" disabled={!config.productionEnabled}>Produção</option></select></label><input type="hidden" name="operation" value="INCLUDE"/><button className="button button-primary" type="submit" disabled={!signingReady}>Gerar + assinar S-1010</button></form>
  <form action={generateSignedEsocialTableEvent} className="card card-pad relationship-form"><input type="hidden" name="eventType" value="S-1020"/><h2>S-1020 · Lotação</h2><label><span>Perfil vigente *</span><select name="sourceId" required defaultValue=""><option value="" disabled>Selecione</option>{(allocationProfiles??[]).map(p=><option key={p.id} value={p.id}>{allocMap.get(p.tax_allocation_id)??p.tax_allocation_id} · {p.valid_from} · tipo {p.lotacao_type}</option>)}</select></label><label><span>Ambiente</span><select name="environment" defaultValue="RESTRICTED"><option value="RESTRICTED">Produção Restrita</option><option value="PRODUCTION" disabled={!config.productionEnabled}>Produção</option></select></label><input type="hidden" name="operation" value="INCLUDE"/><button className="button button-primary" type="submit" disabled={!signingReady}>Gerar + assinar S-1020</button></form>
 </section>
 <section className="card card-pad"><span className="eyebrow">FALLBACK CONTROLADO</span><h2>Registrar XML já assinado</h2><p>Use apenas para homologação, migração ou diagnóstico. O domínio não deve ser contornado por edição manual de XML.</p><form action={saveSignedEsocialEvent} className="relationship-form"><div className="form-grid"><label><span>Tipo do evento *</span><input name="eventType" required placeholder="S-1010"/></label><label><span>Grupo *</span><select name="eventGroup" defaultValue="1"><option value="1">1 — Tabelas</option><option value="2">2 — Não periódicos</option><option value="3">3 — Periódicos</option></select></label><label><span>Operação</span><select name="operation" defaultValue="INCLUDE"><option value="INCLUDE">Inclusão</option><option value="RECTIFY">Retificação</option><option value="DELETE">Exclusão</option></select></label><label><span>Ambiente</span><select name="environment" defaultValue="RESTRICTED"><option value="RESTRICTED">Produção Restrita</option><option value="PRODUCTION" disabled={!config.productionEnabled}>Produção</option></select></label><label><span>Versão do leiaute *</span><input name="layoutVersion" required defaultValue="S-1.3"/></label><label><span>Chave do evento</span><input name="eventKey"/></label><label><span>Tipo inscrição empregador *</span><select name="employerRegistrationType" defaultValue="1"><option value="1">1 — CNPJ</option><option value="2">2 — CPF</option></select></label><label><span>Inscrição empregador *</span><input name="employerRegistrationNumber" required/></label><label><span>Tipo inscrição transmissor *</span><select name="transmitterRegistrationType" defaultValue="1"><option value="1">1 — CNPJ</option><option value="2">2 — CPF</option></select></label><label><span>Inscrição transmissor *</span><input name="transmitterRegistrationNumber" required/></label><label><span>Origem</span><input name="sourceType" defaultValue="MANUAL_SIGNED_XML"/></label><label className="span-2"><span>XML individual assinado *</span><textarea name="signedXml" required rows={14} spellCheck={false}/></label></div><div className="form-actions"><button className="button button-secondary" type="submit">Validar e registrar XML externo</button></div></form></section>
 </main>;
}
