import Link from"next/link";
import{ReportNavigation}from"@/components/reports/report-navigation";
import{evaluateMetric,formatReportNumber,targetFor}from"@/lib/reports/metrics";
import{loadReportDashboard}from"@/lib/reports/server";

export const dynamic="force-dynamic";

export default async function ReportsProjectsPage({searchParams}:{searchParams:Promise<{start?:string;end?:string}>}){
 const query=await searchParams;const{dashboard,start,end}=await loadReportDashboard({start:query.start,end:query.end});
 return <main className="content reports-app"><section className="page-heading"><div><span className="badge">RELATÓRIOS</span><h1>Indicadores por obra</h1><p>Comparação de avanço, prazo, compras, qualidade, campo e valores autorizados.</p></div><Link className="button button-secondary" href={`/api/relatorios/exportar?start=${start}&end=${end}`}>Exportar CSV</Link></section><ReportNavigation/>
 <section className="report-project-grid">{dashboard.projects.map(project=>{const scheduleHealth=evaluateMetric(project.schedule_variance_pp,targetFor(dashboard.targets,"schedule_variance_pp",project.project_id));const qualityHealth=evaluateMetric(project.average_quality_score,targetFor(dashboard.targets,"average_quality_score",project.project_id));return <Link className="card card-pad report-project-card" href={`/app/relatorios/obras/${project.project_id}?start=${start}&end=${end}`} key={project.project_id}><header><div><span className="eyebrow">{project.code}</span><h2>{project.name}</h2></div><span className="badge">{project.status}</span></header><div className="report-progress"><span style={{width:`${Math.max(0,Math.min(100,project.progress))}%`}}/><strong>{formatReportNumber(project.progress,"percent")}</strong></div><dl className="detail-list"><div><dt>Previsto</dt><dd>{formatReportNumber(project.planned_progress,"percent")}</dd></div><div><dt>Desvio</dt><dd className={`report-health-text report-health-${scheduleHealth.toLowerCase()}`}>{formatReportNumber(project.schedule_variance_pp,"percent")}</dd></div><div><dt>Dias de atraso</dt><dd>{project.overdue_days}</dd></div><div><dt>Tarefas bloqueadas</dt><dd>{project.blocked_tasks}</dd></div><div><dt>Qualidade</dt><dd className={`report-health-text report-health-${qualityHealth.toLowerCase()}`}>{formatReportNumber(project.average_quality_score,"percent")}</dd></div><div><dt>Pedidos atrasados</dt><dd>{project.overdue_purchase_orders}</dd></div><div><dt>Valor contratado</dt><dd>{formatReportNumber(project.contract_value,"currency")}</dd></div><div><dt>Saldo a receber</dt><dd>{formatReportNumber(project.receivable_open,"currency")}</dd></div></dl></Link>})}{!dashboard.projects.length&&<div className="empty-state"><h3>Nenhuma obra disponível</h3><p>Não existem obras no escopo atual do usuário.</p></div>}</section></main>;
}
