import Link from"next/link";
import{requireCapability}from"@/lib/authorization";
import{cashFlowRisk,formatMoney,summarizeCashFlow}from"@/lib/financial/cash-flow";

export const dynamic="force-dynamic";

export default async function FinanceDashboard(){
 const context=await requireCapability("financeiro","read");
 await context.supabase.rpc("refresh_finance_overdue_statuses",{p_organization_id:context.organizationId});
 const[{data:balances},{count:pendingApprovals},{count:overdue},{count:measurements},{data:flow},{data:recent}]=await Promise.all([
  context.supabase.from("finance_entry_balances_v").select("direction,balance,settled_amount,status").eq("organization_id",context.organizationId),
  context.supabase.from("finance_approvals").select("id",{count:"exact",head:true}).eq("organization_id",context.organizationId).eq("status","PENDING"),
  context.supabase.from("finance_installments").select("id",{count:"exact",head:true}).eq("organization_id",context.organizationId).eq("status","OVERDUE"),
  context.supabase.from("finance_measurements").select("id",{count:"exact",head:true}).eq("organization_id",context.organizationId).eq("status","SUBMITTED"),
  context.supabase.from("finance_cash_flow_monthly_v").select("period_month,planned_inflow,planned_outflow,realized_inflow,realized_outflow").eq("organization_id",context.organizationId).order("period_month").limit(12),
  context.supabase.from("finance_entries").select("id,code,description,direction,status,total_amount,issue_date,projects(name)").eq("organization_id",context.organizationId).order("created_at",{ascending:false}).limit(8)
 ]);
 const payable=(balances??[]).filter(item=>item.direction==="PAYABLE").reduce((sum,item)=>sum+Number(item.balance),0);
 const receivable=(balances??[]).filter(item=>item.direction==="RECEIVABLE").reduce((sum,item)=>sum+Number(item.balance),0);
 const summary=summarizeCashFlow((flow??[]).map(row=>({month:row.period_month,plannedInflow:Number(row.planned_inflow),plannedOutflow:Number(row.planned_outflow),realizedInflow:Number(row.realized_inflow),realizedOutflow:Number(row.realized_outflow)})));
 const risk=cashFlowRisk(summary);
 return <main className="content finance-app"><section className="page-heading"><div><span className="badge">APLICATIVO · FINANCEIRO</span><h1>Financeiro Operacional</h1><p>Contas, parcelas, medições, aprovações, liquidações e fluxo de caixa por obra.</p></div><div className="page-actions"><Link className="button button-secondary" href="/app/financeiro/fluxo-de-caixa">Fluxo de caixa</Link><Link className="button button-primary" href="/app/financeiro/lancamentos/novo">Novo lançamento</Link></div></section>
 <section className="stats-grid"><article className="card"><small>A RECEBER</small><strong>{formatMoney(receivable)}</strong><span>saldo aberto</span></article><article className="card"><small>A PAGAR</small><strong>{formatMoney(payable)}</strong><span>saldo aberto</span></article><article className="card"><small>APROVAÇÕES</small><strong>{pendingApprovals??0}</strong><span>pendentes</span></article><article className="card"><small>ATRASOS</small><strong>{overdue??0}</strong><span>parcelas vencidas</span></article></section>
 <section className="finance-launch-grid"><Link className="card card-pad finance-launch" href="/app/financeiro/lancamentos"><span>▤</span><div><h2>Contas e parcelas</h2><p>Gerencie obrigações, recebíveis e baixas.</p></div></Link><Link className="card card-pad finance-launch" href="/app/financeiro/medicoes"><span>▥</span><div><h2>Medições</h2><p>{measurements??0} aguardando aprovação.</p></div></Link><Link className="card card-pad finance-launch" href="/app/financeiro/configuracoes"><span>⚙</span><div><h2>Configurações</h2><p>Categorias, centros de custo e contas.</p></div></Link></section>
 <div className="finance-two-column"><section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">ÚLTIMOS LANÇAMENTOS</span><h2>Movimentações financeiras</h2></div><Link className="text-link" href="/app/financeiro/lancamentos">Ver todos →</Link></div><div className="finance-list">{(recent??[]).map(item=>{const project=Array.isArray(item.projects)?item.projects[0]:item.projects;return <Link className="finance-row" href={`/app/financeiro/lancamentos/${item.id}`} key={item.id}><div><strong>{item.code} · {item.description}</strong><small>{project?.name??"Sem obra"} · {item.issue_date}</small></div><div><span className="badge">{item.status}</span><strong className={item.direction==="RECEIVABLE"?"finance-positive":"finance-negative"}>{item.direction==="RECEIVABLE"?"+":"-"}{formatMoney(Number(item.total_amount))}</strong></div></Link>})}{!recent?.length&&<div className="empty-state"><h3>Nenhum lançamento</h3><p>Crie o primeiro lançamento financeiro.</p></div>}</div></section><aside className="card card-pad"><span className="eyebrow">RISCO DE CAIXA</span><h2>{formatMoney(risk.maximumCashRequirement)}</h2><p>Necessidade máxima projetada no horizonte atual.</p><dl className="detail-list"><div><dt>Menor saldo projetado</dt><dd>{formatMoney(risk.minimumProjectedBalance)}</dd></div><div><dt>Meses negativos</dt><dd>{risk.negativeMonths.length}</dd></div><div><dt>Saldo final previsto</dt><dd>{formatMoney(summary.at(-1)?.accumulatedPlanned??0)}</dd></div><div><dt>Saldo final realizado</dt><dd>{formatMoney(summary.at(-1)?.accumulatedRealized??0)}</dd></div></dl></aside></div></main>;
}
