import Link from"next/link";
import{runHealthSnapshot}from"@/app/actions/observability";
import{ObservabilityNavigation}from"@/components/observability/observability-navigation";
import{dateTime,healthLabel,severityLabel,text,number}from"@/lib/observability/domain";
import{loadObservabilityDashboard}from"@/lib/observability/server";

export const dynamic="force-dynamic";

export default async function ObservabilityDashboard({searchParams}:{searchParams:Promise<{hours?:string;error?:string}>}){
 const query=await searchParams;const hours=Math.min(8760,Math.max(1,Number(query.hours)||24));const{dashboard,error}=await loadObservabilityDashboard(hours);
 return <main className="content observability-app"><section className="page-heading"><div><span className="badge">APLICATIVO · AUDITORIA</span><h1>Auditoria e Observabilidade</h1><p>Eventos correlacionados, alertas, saúde operacional e diagnósticos sem exposição de payloads sensíveis.</p></div><form action={runHealthSnapshot}><button className="button button-primary">Executar diagnóstico</button></form></section><ObservabilityNavigation/>{(query.error||error)&&<div className="validation blocking">{query.error||error}</div>}
 <form className="card card-pad observability-filter" method="get"><label>Período<select name="hours" defaultValue={String(hours)}><option value="24">24 horas</option><option value="168">7 dias</option><option value="720">30 dias</option><option value="8760">12 meses</option></select></label><button className="button button-secondary">Atualizar</button></form>
 <section className="observability-stats"><article><span>EVENTOS</span><strong>{dashboard.events.total}</strong><small>{dashboard.events.error} erro(s) · {dashboard.events.critical} crítico(s)</small></article><article><span>ALERTAS ABERTOS</span><strong>{dashboard.openAlerts}</strong><small>abertos ou reconhecidos</small></article><article><span>SAÚDE</span><strong>{dashboard.unhealthyChecks}</strong><small>componente(s) degradado(s)</small></article><article><span>DIAGNÓSTICOS</span><strong>{dashboard.unresolvedDiagnostics}</strong><small>pendência(s) técnica(s)</small></article></section>
 <div className="observability-columns"><section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">RISCO ATUAL</span><h2>Alertas recentes</h2></div><Link className="text-link" href="/app/auditoria/alertas">Ver todos →</Link></div><div className="observability-list">{dashboard.recentAlerts.map(item=><article key={text(item.id)}><div><span className={`severity severity-${text(item.severity).toLowerCase()}`}>{severityLabel(text(item.severity))}</span><strong>{text(item.title)}</strong><small>{text(item.module_key,"sistema")} · {number(item.occurrence_count)} ocorrência(s)</small></div><time>{dateTime(item.last_occurred_at)}</time></article>)}{!dashboard.recentAlerts.length&&<div className="empty-state"><h3>Nenhum alerta</h3><p>Não há alertas registrados para esta organização.</p></div>}</div></section>
 <section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">COMPONENTES</span><h2>Último estado</h2></div><Link className="text-link" href="/app/auditoria/saude">Detalhar →</Link></div><div className="observability-list">{dashboard.latestHealth.map(item=><article key={text(item.check_key)}><div><span className={`health health-${text(item.status).toLowerCase()}`}>{healthLabel(text(item.status))}</span><strong>{text(item.component)}</strong><small>{text(item.message)}</small></div><time>{dateTime(item.checked_at)}</time></article>)}{!dashboard.latestHealth.length&&<div className="empty-state"><h3>Sem snapshot</h3><p>Execute o diagnóstico para registrar o estado dos componentes.</p></div>}</div></section></div>
 <section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">ORIGEM DOS EVENTOS</span><h2>Atividade por módulo</h2></div><Link className="text-link" href="/app/auditoria/eventos">Abrir fluxo →</Link></div><div className="observability-modules">{dashboard.byModule.map(item=><div key={text(item.module)}><strong>{text(item.module)}</strong><span>{number(item.count)}</span></div>)}</div></section></main>;
}
