apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-worker
    spec:
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["node","dist/worker.js"]
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            - name: WORKER_MAX_CONCURRENCY
              value: "{{ .Values.worker.concurrency }}"
            - name: POD_NAME
              valueFrom: {fieldRef: {fieldPath: metadata.name}}
          envFrom:
            - secretRef: {name: {{ .Release.Name }}-secrets}
            - configMapRef: {name: {{ .Release.Name }}-config}
