import{describe,expect,it}from"vitest";
import{mitFilename,renderMitJson,validateMitDocument,type MitDocument}from"@/lib/rh/integrations/mit-json";

const noMovement:MitDocument={PeriodoApuracao:{MesApuracao:8,AnoApuracao:2026},DadosIniciais:{SemMovimento:true,QualificacaoPj:1,ResponsavelApuracao:{CpfResponsavel:"12345678900"}}};
const movement:MitDocument={PeriodoApuracao:{MesApuracao:8,AnoApuracao:2026},DadosIniciais:{SemMovimento:false,QualificacaoPj:1,TributacaoLucro:3,VariacoesMonetarias:2,ResponsavelApuracao:{CpfResponsavel:"12345678900",EmailResponsavel:"responsavel@example.com"}},Debitos:{ContribuicoesDiversas:{ListaDebitos:[{IdDebito:1,CodigoDebito:"123456",ValorDebito:777.55}]}}};

describe("MIT JSON 1.0",()=>{
 it("renderiza apuração sem movimento no layout oficial",()=>{const json=renderMitJson(noMovement);expect(JSON.parse(json)).toEqual(noMovement);expect(mitFilename("12345678",noMovement)).toBe("12345678-MIT-202608.json");});
 it("renderiza apuração com movimento e débito sequencial",()=>{const result=validateMitDocument(movement);expect(result).toEqual({valid:true,errors:[]});expect(JSON.parse(renderMitJson(movement)).Debitos.ContribuicoesDiversas.ListaDebitos[0].ValorDebito).toBe(777.55);});
 it("bloqueia movimento sem débitos e sem variações monetárias",()=>{const invalid:MitDocument={PeriodoApuracao:{MesApuracao:8,AnoApuracao:2026},DadosIniciais:{SemMovimento:false,QualificacaoPj:1,TributacaoLucro:3,ResponsavelApuracao:{CpfResponsavel:"12345678900"}}};const result=validateMitDocument(invalid);expect(result.valid).toBe(false);expect(result.errors.join(" ")).toMatch(/VariacoesMonetarias/);expect(result.errors.join(" ")).toMatch(/grupo de débito/);});
 it("bloqueia IDs de débito não sequenciais",()=>{const invalid:MitDocument={...movement,Debitos:{ContribuicoesDiversas:{ListaDebitos:[{IdDebito:2,CodigoDebito:"123456",ValorDebito:10}]}}};expect(validateMitDocument(invalid).errors.join(" ")).toMatch(/sequencial/);});
 it("exige eventos especiais cronológicos e IDs sequenciais",()=>{const invalid:MitDocument={...movement,ListaEventosEspeciais:[{IdEvento:2,DiaEvento:20,TipoEvento:4},{IdEvento:1,DiaEvento:10,TipoEvento:6}]};const errors=validateMitDocument(invalid).errors.join(" ");expect(errors).toMatch(/IdEvento/);expect(errors).toMatch(/ordem cronológica/);});
 it("restringe grupos por qualificação e tributação",()=>{const invalid:MitDocument={PeriodoApuracao:{MesApuracao:8,AnoApuracao:2026},DadosIniciais:{SemMovimento:false,QualificacaoPj:9,TributacaoLucro:3,VariacoesMonetarias:2,RegimePisCofins:1,ResponsavelApuracao:{CpfResponsavel:"12345678900"}},Debitos:{Irrf:{ListaDebitos:[{IdDebito:1,CodigoDebito:"123456",ValorDebito:100}]}}};expect(validateMitDocument(invalid).errors.join(" ")).toMatch(/Irrf: grupo não permitido/);});
 it("bloqueia ListaDebitosAposEvento sem evento especial compatível",()=>{const invalid:MitDocument={...movement,Debitos:{ContribuicoesDiversas:{ListaDebitosAposEvento:[{IdDebito:1,IdEventoDebito:1,CodigoDebito:"123456",ValorDebito:100}]}}};const errors=validateMitDocument(invalid).errors.join(" ");expect(errors).toMatch(/ListaDebitosAposEvento exige/);expect(errors).toMatch(/não referencia evento existente/);});
 it("exige BalancoLucroReal quando aplicável ao Lucro Real Anual",()=>{const invalid:MitDocument={PeriodoApuracao:{MesApuracao:8,AnoApuracao:2026},DadosIniciais:{SemMovimento:false,QualificacaoPj:1,TributacaoLucro:1,VariacoesMonetarias:2,RegimePisCofins:1,ResponsavelApuracao:{CpfResponsavel:"12345678900"}},Debitos:{Irpj:{ListaDebitos:[{IdDebito:1,CodigoDebito:"123456",ValorDebito:100}]}}};expect(validateMitDocument(invalid).errors.join(" ")).toMatch(/BalancoLucroReal/);const valid={...invalid,Debitos:{BalancoLucroReal:false,Irpj:invalid.Debitos!.Irpj}};expect(validateMitDocument(valid).errors).not.toContain(expect.stringMatching(/BalancoLucroReal/));});
 it("exige campos processuais completos para suspensão judicial",()=>{const invalid:MitDocument={...movement,ListaSuspensoes:[{TipoSuspensao:2,MotivoSuspensao:1,NumeroProcesso:"12345678901234567890",ListaDebitosSuspensos:[{IdDebitoSuspenso:1,ValorSuspenso:100}]}]};const errors=validateMitDocument(invalid).errors.join(" ");expect(errors).toMatch(/ComDeposito/);expect(errors).toMatch(/ProcessoTerceiro/);expect(errors).toMatch(/DataDecisao/);expect(errors).toMatch(/VaraJudiciaria/);expect(errors).toMatch(/CodigoMunicipioSj/);});
});
