import{createAlertRule,updateRetentionPolicy}from"@/app/actions/observability";
import{ObservabilityNavigation}from"@/components/observability/observability-navigation";
import{MODULE_REGISTRY}from"@/lib/modules/registry";
import{number,record,text}from"@/lib/observability/domain";
import{loadObservabilitySettings}from"@/lib/observability/server";

export const dynamic="force-dynamic";

export default async function ObservabilitySettings({searchParams}:{searchParams:Promise<{error?:string}>}){
 const query=await searchParams;const{rules,retention,error}=await loadObservabilitySettings();
 return <main className="content observability-app"><section className="page-heading"><div><span className="badge">AUDITORIA · CONFIGURAÇÃO</span><h1>Regras e retenção</h1><p>Configuração restrita à direção e aos administradores do aplicativo.</p></div></section><ObservabilityNavigation/>{(query.error||error)&&<div className="validation blocking">{query.error||error}</div>}
 <div className="observability-columns"><section className="card card-pad"><span className="eyebrow">NOVA REGRA</span><h2>Gerar alerta</h2><form action={createAlertRule} className="observability-form"><label>Nome<input name="name" required/></label><label>Módulo<select name="moduleKey"><option value="">Todos</option>{MODULE_REGISTRY.map(item=><option value={item.key} key={item.key}>{item.name}</option>)}</select></label><label>Padrão do evento<input name="eventTypePattern" placeholder="signature.% ou vazio"/></label><label>Severidade mínima<select name="minimumSeverity" defaultValue="ERROR"><option>INFO</option><option>WARNING</option><option>ERROR</option><option>CRITICAL</option></select></label><label>Quantidade<input name="thresholdCount" type="number" min="1" defaultValue="1"/></label><label>Janela em minutos<input name="windowMinutes" type="number" min="1" defaultValue="15"/></label><label>Cooldown em minutos<input name="cooldownMinutes" type="number" min="0" defaultValue="30"/></label><button className="button button-primary">Criar regra</button></form></section>
 <section className="card card-pad"><span className="eyebrow">RETENÇÃO</span><h2>Política de eventos</h2><form action={updateRetentionPolicy} className="observability-form"><label>Fonte<input name="sourceTable" defaultValue="audit_events" readOnly/></label><label>Dias<input name="retentionDays" type="number" min="30" max="3650" defaultValue={number(record(retention[0]).retention_days,365)}/></label><label className="check-label"><input name="preserveCritical" type="checkbox" defaultChecked={record(retention[0]).preserve_critical!==false}/>Preservar eventos críticos</label><button className="button button-primary">Salvar retenção</button></form><p className="muted">A exclusão física futura será executada somente por worker administrativo e nunca removerá eventos críticos quando a preservação estiver ativa.</p></section></div>
 <section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">REGRAS ATIVAS</span><h2>Catálogo da organização</h2></div></div><div className="observability-table-wrap"><table className="data-table"><thead><tr><th>Nome</th><th>Módulo</th><th>Padrão</th><th>Severidade</th><th>Limite</th><th>Janela</th><th>Ativa</th></tr></thead><tbody>{rules.map(raw=>{const rule=record(raw);return <tr key={text(rule.id)}><td>{text(rule.name)}</td><td>{text(rule.module_key,"todos")}</td><td>{text(rule.event_type_pattern,"qualquer")}</td><td>{text(rule.minimum_severity)}</td><td>{number(rule.threshold_count)}</td><td>{number(rule.window_minutes)} min</td><td>{rule.active?"Sim":"Não"}</td></tr>})}</tbody></table></div></section></main>;
}
