import Link from "next/link";
import { uploadQualityDocument } from "@/app/actions/quality";
import { requireCapability } from "@/lib/authorization";

export const dynamic="force-dynamic";
const kindLabels:Record<string,string>={PROCEDURE:"Procedimento",FVS:"FVS",FVM:"FVM",FORM_ATTACHMENT:"Anexo de formulário",SURVEY_REPORT:"Relatório de pesquisa",OTHER:"Outro"};
export default async function QualityDocuments({searchParams}:{searchParams:Promise<{error?:string}>}){
  const query=await searchParams;const context=await requireCapability("qualidade","read");
  const[{data:documents},{data:projects},{data:clients}]=await Promise.all([
    context.supabase.from("quality_documents").select("*").eq("organization_id",context.organizationId).eq("is_current",true).order("created_at",{ascending:false}),
    context.supabase.from("projects").select("id,name,client_id").eq("organization_id",context.organizationId).order("name"),
    context.supabase.from("clients").select("id,legal_name,trade_name").eq("organization_id",context.organizationId).order("legal_name")
  ]);
  return <main className="content quality-app"><Link className="back-link" href="/app/qualidade">← Qualidade</Link><section className="page-heading"><div><span className="badge">BIBLIOTECA ONLINE</span><h1>Documentos da qualidade</h1><p>Leitura no navegador, download autorizado, upload e histórico por versão.</p></div></section>{query.error&&<div className="validation blocking">{query.error}</div>}
  <div className="quality-two-column"><section><div className="quality-document-grid">{(documents??[]).map(document=><article className="card quality-document-card" key={document.id}><div className="quality-document-icon">{document.mime_type==="application/pdf"?"PDF":document.mime_type.includes("word")?"DOCX":"ARQ"}</div><div><span className="badge">{kindLabels[document.kind]??document.kind} · V{document.version_number}</span><h2>{document.title}</h2><p>{document.description||document.file_name}</p><small>SHA-256 · {document.sha256.slice(0,16)}… · {(Number(document.size_bytes)/1024/1024).toFixed(2)} MB</small><div className="quality-card-actions"><a className="button button-primary" href={`/api/qualidade/documentos/${document.id}`} target="_blank">Ler online</a><a className="button button-secondary" href={`/api/qualidade/documentos/${document.id}?download=1`}>Baixar</a></div></div>{document.client_visible&&<span className="quality-client-flag">Visível ao cliente</span>}</article>)}{!documents?.length&&<div className="empty-state card card-pad"><h2>Biblioteca vazia</h2><p>Envie o primeiro procedimento, FVS ou FVM.</p></div>}</div></section>
  <aside><form action={uploadQualityDocument} encType="multipart/form-data" className="card card-pad quality-upload-form"><span className="eyebrow">NOVO ARQUIVO</span><h2>Enviar para a biblioteca</h2><label>Título<input name="title" required/></label><label>Tipo<select name="kind"><option value="PROCEDURE">Procedimento</option><option value="FVS">FVS</option><option value="FVM">FVM</option><option value="OTHER">Outro</option></select></label><label>Descrição<textarea name="description" rows={3}/></label><label>Obra, opcional<select name="projectId"><option value="">Geral</option>{(projects??[]).map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Cliente, opcional<select name="clientId"><option value="">Nenhum</option>{(clients??[]).map(client=><option key={client.id} value={client.id}>{client.trade_name||client.legal_name}</option>)}</select></label><label>Arquivo<input type="file" name="file" accept="application/pdf,.docx,.xlsx,image/*" required/></label><label className="quality-inline-check"><input type="checkbox" name="clientVisible"/> Liberar leitura no portal do cliente</label><button className="button button-primary" type="submit">Enviar arquivo</button><small>Até 50 MB. PDF, DOCX, XLSX ou imagem. O SHA-256 é calculado antes do registro.</small></form></aside></div></main>;
}
