import{makeEsocialEventId,normalizeEmployerRegistrationNumber,type EsocialEnvironment}from"./esocial-xml";
const LAYOUT="v_S_01_03_00";const VER_PROC=process.env.ESOCIAL_PROCESS_VERSION?.trim()||"Innovar-RH/0.1";
function x(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");}function tag(n:string,v:unknown){return `<${n}>${x(v)}</${n}>`;}function opt(n:string,v:unknown){return v===null||v===undefined||v===""?"":tag(n,v);}function digits(v:string){return v.replace(/\D/g,"");}function tpAmb(e:EsocialEnvironment){return e==='PRODUCTION'?1:2;}function ideEmpregador(t:1|2,n:string){return `<ideEmpregador>${tag('tpInsc',t)}${tag('nrInsc',normalizeEmployerRegistrationNumber(t,n))}</ideEmpregador>`;}function ideEventoPeriodic(e:EsocialEnvironment,period:string,receipt?:string|null){return `<ideEvento>${tag('indRetif',receipt?2:1)}${receipt?tag('nrRecibo',receipt):''}${tag('indApuracao',1)}${tag('perApur',period)}${tag('tpAmb',tpAmb(e))}${tag('procEmi',1)}${tag('verProc',VER_PROC)}</ideEvento>`;}function root(ns:string,eventTag:string,key:string,body:string){return `<eSocial xmlns="${ns}"><${eventTag} Id="${x(key)}">${body}</${eventTag}></eSocial>`;}
export type S1200RubricLine={rubricCode:string;tableCode:string;amount:number;quantity?:number|null;factor?:number|null;};
export type S1200Input={environment:EsocialEnvironment;employerType:1|2;employerNumber:string;period:string;cpf:string;registrationNumber:string;categoryCode:string;demonstrativeId:string;establishmentType:1|3|4;establishmentNumber:string;lotacaoCode:string;lines:S1200RubricLine[];receipt?:string|null;eventKey?:string;};
export function buildS1200(input:S1200Input){const key=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);if(!/^\d{4}-\d{2}$/.test(input.period))throw new Error('S-1200 exige competência AAAA-MM.');if(!/^\d{11}$/.test(digits(input.cpf)))throw new Error('S-1200 exige CPF.');if(!/^\d{3}$/.test(input.categoryCode))throw new Error('S-1200 exige categoria eSocial.');if(!input.lines.length)throw new Error('S-1200 exige rubricas.');const items=input.lines.map(l=>{if(!l.rubricCode||!l.tableCode)throw new Error('Rubrica S-1200 sem código/tabela.');return `<itensRemun>${tag('codRubr',l.rubricCode)}${tag('ideTabRubr',l.tableCode)}${opt('qtdRubr',l.quantity)}${opt('fatorRubr',l.factor)}${tag('vrRubr',Math.abs(Number(l.amount)).toFixed(2))}</itensRemun>`;}).join('');const remun=`<dmDev>${tag('ideDmDev',input.demonstrativeId)}${tag('codCateg',input.categoryCode)}<infoPerApur><ideEstabLot>${tag('tpInsc',input.establishmentType)}${tag('nrInsc',digits(input.establishmentNumber))}${tag('codLotacao',input.lotacaoCode)}<remunPerApur>${tag('matricula',input.registrationNumber)}${items}</remunPerApur></ideEstabLot></infoPerApur></dmDev>`;return root(`http://www.esocial.gov.br/schema/evt/evtRemun/${LAYOUT}`,'evtRemun',key,`${ideEventoPeriodic(input.environment,input.period,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}<ideTrabalhador>${tag('cpfTrab',digits(input.cpf))}</ideTrabalhador>${remun}`);}
export type S1210Input={environment:EsocialEnvironment;employerType:1|2;employerNumber:string;period:string;cpf:string;paymentDate:string;paymentType:1|2|3|4|5|6|7;referencePeriod:string;demonstrativeId:string;netAmount:number;receipt?:string|null;eventKey?:string;};
export function buildS1210(input:S1210Input){const key=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);if(!/^\d{11}$/.test(digits(input.cpf)))throw new Error('S-1210 exige CPF.');if(input.netAmount<0)throw new Error('S-1210 não aceita líquido negativo.');const pg=`<infoPgto>${tag('dtPgto',input.paymentDate)}${tag('tpPgto',input.paymentType)}${tag('perRef',input.referencePeriod)}${tag('ideDmDev',input.demonstrativeId)}${tag('vrLiq',Number(input.netAmount).toFixed(2))}</infoPgto>`;return root(`http://www.esocial.gov.br/schema/evt/evtPgtos/${LAYOUT}`,'evtPgtos',key,`${ideEventoPeriodic(input.environment,input.period,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}<ideBenef>${tag('cpfBenef',digits(input.cpf))}</ideBenef>${pg}`);}
export type S1299Input={environment:EsocialEnvironment;employerType:1|2;employerNumber:string;period:string;hasRemuneration:boolean;hasPayments:boolean;hasProduction:boolean;hasNonPayrollContracting:boolean;hasAdditionalPeriodInfo:boolean;receipt?:string|null;eventKey?:string;};
export function buildS1299(input:S1299Input){const key=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);const b=(v:boolean)=>v?'S':'N';const info=`<infoFech>${tag('evtRemun',b(input.hasRemuneration))}${tag('evtPgtos',b(input.hasPayments))}${tag('evtComProd',b(input.hasProduction))}${tag('evtContratAvNP',b(input.hasNonPayrollContracting))}${tag('evtInfoComplPer',b(input.hasAdditionalPeriodInfo))}</infoFech>`;return root(`http://www.esocial.gov.br/schema/evt/evtFechaEvPer/${LAYOUT}`,'evtFechaEvPer',key,`${ideEventoPeriodic(input.environment,input.period,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}${info}`);}
export type S1298Input={environment:EsocialEnvironment;employerType:1|2;employerNumber:string;period:string;receipt?:string|null;eventKey?:string;};
export function buildS1298(input:S1298Input){const key=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);return root(`http://www.esocial.gov.br/schema/evt/evtReabreEvPer/${LAYOUT}`,'evtReabreEvPer',key,`${ideEventoPeriodic(input.environment,input.period,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}`);}
