import { makeEsocialEventId,normalizeEmployerRegistrationNumber,type EsocialEnvironment } from "./esocial-xml";

const LAYOUT="v_S_01_03_00";const VER_PROC=process.env.ESOCIAL_PROCESS_VERSION?.trim()||"Innovar-RH/0.1";
function x(v:unknown){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");}
function tag(n:string,v:unknown){return `<${n}>${x(v)}</${n}>`;}function opt(n:string,v:unknown){return v===null||v===undefined||v===""?"":tag(n,v);}function digits(v:string){return v.replace(/\D/g,"");}
function yes(v:boolean){return v?"S":"N";}function tpAmb(e:EsocialEnvironment){return e==="PRODUCTION"?1:2;}function ideEvento(e:EsocialEnvironment,r?:string|null){return `<ideEvento>${tag("indRetif",r?2:1)}${r?tag("nrRecibo",r):""}${tag("tpAmb",tpAmb(e))}${tag("procEmi",1)}${tag("verProc",VER_PROC)}</ideEvento>`;}function ideEmpregador(t:1|2,n:string){return `<ideEmpregador>${tag("tpInsc",t)}${tag("nrInsc",normalizeEmployerRegistrationNumber(t,n))}</ideEmpregador>`;}function ideVinculo(cpf:string,matricula:string){return `<ideVinculo>${tag("cpfTrab",digits(cpf))}${tag("matricula",matricula)}</ideVinculo>`;}function root(ns:string,eventTag:string,eventKey:string,body:string){return `<eSocial xmlns="${ns}"><${eventTag} Id="${x(eventKey)}">${body}</${eventTag}></eSocial>`;}
function hhmm(value:string|null|undefined){if(!value)return null;const parts=value.slice(0,5).split(":");return parts.length===2?`${parts[0].padStart(2,"0")}${parts[1].padStart(2,"0")}`:value.replace(/\D/g,"").padStart(4,"0").slice(0,4);}
function hoursToHHMM(value:number|null|undefined){if(value===null||value===undefined)return null;const h=Math.floor(value);const m=Math.round((value-h)*60);return `${String(h).padStart(2,"0")}${String(m).padStart(2,"0")}`;}

export type S2210Input={
 environment:EsocialEnvironment;employerType:1|2;employerNumber:string;cpf:string;registrationNumber:string;accidentDate:string;accidentTime?:string|null;hoursWorkedBefore?:number|null;
 accidentType:1|2|3;catType:1|2|3;death:boolean;deathDate?:string|null;policeReport:boolean;generatingSituationCode:string;initiatorType:1|2|3;observation?:string|null;
 lastWorkedDay?:string|null;causedLeave:boolean;locationType:1|2|3|4|5|6|9;locationDescription?:string|null;streetType?:string|null;street:string;streetNumber:string;
 complement?:string|null;neighborhood?:string|null;postalCode?:string|null;cityIbgeCode?:string|null;stateCode?:string|null;countryCode?:string|null;foreignPostalCode?:string|null;
 establishmentRegistrationType?:1|3|4|null;establishmentRegistrationNumber?:string|null;bodyPartCode:string;laterality:0|1|2|3;agentCode:string;
 attestation:{attendanceDate:string;attendanceTime:string;hospitalization:boolean;treatmentDurationDays:number;leaveRecommended:boolean;injuryNatureCode:string;injuryDescription?:string|null;probableDiagnosis?:string|null;cidCode:string;observation?:string|null;professionalName:string;professionalRegistrationType:1|2|3;professionalRegistrationNumber:string;professionalState?:string|null};
 originalCatReceipt?:string|null;receipt?:string|null;eventKey?:string;
};
export function buildS2210(input:S2210Input){
 const eventKey=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);
 if(!/^\d{11}$/.test(digits(input.cpf)))throw new Error("S-2210 exige CPF com 11 dígitos.");if(!/^\d{9}$/.test(digits(input.generatingSituationCode)))throw new Error("S-2210 exige situação geradora com 9 dígitos.");if(!/^\d{9}$/.test(digits(input.bodyPartCode))||!/^\d{9}$/.test(digits(input.agentCode)))throw new Error("S-2210 exige códigos de parte atingida e agente com 9 dígitos.");if(input.death&&!input.deathDate)throw new Error("CAT com óbito exige data do óbito.");if(input.catType!==1&&!input.originalCatReceipt)throw new Error("Reabertura/comunicação de óbito exige recibo da CAT anterior.");if([1,3].includes(input.accidentType)&&(!input.accidentTime||input.hoursWorkedBefore===null||input.hoursWorkedBefore===undefined))throw new Error("Acidente típico/trajeto exige hora e horas trabalhadas antes do acidente.");
 if([1,3,5].includes(input.locationType)&&!input.postalCode)throw new Error("Local da CAT no Brasil exige CEP para este tipo de local.");if([1,3,4,5].includes(input.locationType)&&(!input.cityIbgeCode||!input.stateCode))throw new Error("Local da CAT no Brasil exige município IBGE e UF.");if(input.locationType===2&&(!input.countryCode||!input.foreignPostalCode))throw new Error("Local de acidente no exterior exige país e código postal.");
 const local=`<localAcidente>${tag("tpLocal",input.locationType)}${opt("dscLocal",input.locationDescription)}${opt("tpLograd",input.streetType)}${tag("dscLograd",input.street)}${tag("nrLograd",input.streetNumber)}${opt("complemento",input.complement)}${opt("bairro",input.neighborhood)}${opt("cep",input.postalCode?digits(input.postalCode):null)}${opt("codMunic",input.cityIbgeCode?digits(input.cityIbgeCode):null)}${opt("uf",input.stateCode)}${opt("pais",input.countryCode)}${opt("codPostal",input.foreignPostalCode)}${input.establishmentRegistrationType&&input.establishmentRegistrationNumber?`<ideLocalAcid>${tag("tpInsc",input.establishmentRegistrationType)}${tag("nrInsc",digits(input.establishmentRegistrationNumber))}</ideLocalAcid>`:""}</localAcidente>`;
 const a=input.attestation;const normalizedCid=a.cidCode.replace(/[.\s-]/g,"").toUpperCase();if(!/^[A-Z][0-9]{2}[0-9A-Z]?$/.test(normalizedCid))throw new Error("CAT exige CID alfanumérico em formato de 3 ou 4 caracteres.");const atestado=`<atestado>${tag("dtAtendimento",a.attendanceDate)}${tag("hrAtendimento",hhmm(a.attendanceTime))}${tag("indInternacao",yes(a.hospitalization))}${tag("durTrat",a.treatmentDurationDays)}${tag("indAfast",yes(a.leaveRecommended))}${tag("dscLesao",digits(a.injuryNatureCode))}${opt("dscCompLesao",a.injuryDescription)}${opt("diagProvavel",a.probableDiagnosis)}${tag("codCID",normalizedCid)}${opt("observacao",a.observation)}<emitente>${tag("nmEmit",a.professionalName)}${tag("ideOC",a.professionalRegistrationType)}${tag("nrOC",a.professionalRegistrationNumber)}${opt("ufOC",a.professionalState)}</emitente></atestado>`;
 const cat=`<cat>${tag("dtAcid",input.accidentDate)}${opt("tpAcid",input.accidentType)}${opt("hrAcid",hhmm(input.accidentTime))}${opt("hrsTrabAntesAcid",hoursToHHMM(input.hoursWorkedBefore))}${tag("tpCat",input.catType)}${tag("indCatObito",yes(input.death))}${opt("dtObito",input.deathDate)}${tag("indComunPolicia",yes(input.policeReport))}${tag("codSitGeradora",digits(input.generatingSituationCode))}${tag("iniciatCAT",input.initiatorType)}${opt("obsCAT",input.observation)}${opt("ultDiaTrab",input.lastWorkedDay)}${tag("houveAfast",yes(input.causedLeave))}${local}<parteAtingida>${tag("codParteAting",digits(input.bodyPartCode))}${tag("lateralidade",input.laterality)}</parteAtingida><agenteCausador>${tag("codAgntCausador",digits(input.agentCode))}</agenteCausador>${atestado}${input.originalCatReceipt?`<catOrigem>${tag("nrRecCatOrig",input.originalCatReceipt)}</catOrigem>`:""}</cat>`;
 return root(`http://www.esocial.gov.br/schema/evt/evtCAT/${LAYOUT}`,"evtCAT",eventKey,`${ideEvento(input.environment,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}${ideVinculo(input.cpf,input.registrationNumber)}${cat}`);
}

export type S2220Procedure={examDate:string;procedureCode:string;observation?:string|null;examOrderCode?:1|2|null;resultCode?:1|2|3|4|null};
export type S2220Input={environment:EsocialEnvironment;employerType:1|2;employerNumber:string;cpf:string;registrationNumber:string;examType:0|1|2|3|4|9;asoDate:string;asoResult?:1|2|null;procedures:S2220Procedure[];physicianName:string;physicianCrm?:string|null;physicianState?:string|null;pcmso?:{cpf?:string|null;name:string;crm:string;state:string}|null;receipt?:string|null;eventKey?:string;};
export function buildS2220(input:S2220Input){
 const eventKey=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);if(!/^\d{11}$/.test(digits(input.cpf)))throw new Error("S-2220 exige CPF com 11 dígitos.");if(input.procedures.length<1||input.procedures.length>99)throw new Error("S-2220 exige de 1 a 99 procedimentos.");
 const exames=input.procedures.map(p=>{if(!/^\d{4}$/.test(digits(p.procedureCode)))throw new Error("Procedimento S-2220 deve possuir 4 dígitos.");return `<exame>${tag("dtExm",p.examDate)}${tag("procRealizado",digits(p.procedureCode))}${opt("obsProc",p.observation)}${opt("ordExame",p.examOrderCode)}${opt("indResult",p.resultCode)}</exame>`;}).join("");
 const medico=`<medico>${tag("nmMed",input.physicianName)}${opt("nrCRM",input.physicianCrm)}${opt("ufCRM",input.physicianState)}</medico>`;const aso=`<aso>${tag("dtAso",input.asoDate)}${opt("resAso",input.asoResult)}${exames}${medico}</aso>`;const resp=input.pcmso?`<respMonit>${opt("cpfResp",input.pcmso.cpf?digits(input.pcmso.cpf):null)}${tag("nmResp",input.pcmso.name)}${tag("nrCRM",input.pcmso.crm)}${tag("ufCRM",input.pcmso.state)}</respMonit>`:"";
 return root(`http://www.esocial.gov.br/schema/evt/evtMonit/${LAYOUT}`,"evtMonit",eventKey,`${ideEvento(input.environment,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}${ideVinculo(input.cpf,input.registrationNumber)}<exMedOcup>${tag("tpExameOcup",input.examType)}${aso}${resp}</exMedOcup>`);
}

export type S2240Agent={agentCode:string;description?:string|null;evaluationType?:1|2|null;intensity?:number|null;toleranceLimit?:number|null;unitCode?:number|null;measurementTechnique?:string|null;judicialProcessNumber?:string|null;epcImplemented?:boolean|null;epcEffective?:boolean|null;epiUsed?:boolean|null;epiEffective?:boolean|null;epiDocuments?:string[];protectiveMeasuresAttempted?:boolean|null;epiUseConditionCompliant?:boolean|null;uninterruptedUseObserved?:boolean|null;epiExpiryObserved?:boolean|null;epiChangeFrequencyObserved?:boolean|null;epiCleaningObserved?:boolean|null};
export type S2240Input={environment:EsocialEnvironment;employerType:1|2;employerNumber:string;cpf:string;registrationNumber:string;conditionStart:string;environmentLocationType:1|2;sectorDescription:string;environmentRegistrationType:1|3|4;environmentRegistrationNumber:string;activityDescription:string;agents:S2240Agent[];responsible?:{cpf:string;classBody?:1|4|9|null;classBodyDescription?:string|null;registrationNumber?:string|null;state?:string|null}|null;observation?:string|null;receipt?:string|null;eventKey?:string;};
export function buildS2240(input:S2240Input){
 const eventKey=input.eventKey??makeEsocialEventId(input.employerType,input.employerNumber);if(!/^\d{11}$/.test(digits(input.cpf)))throw new Error("S-2240 exige CPF com 11 dígitos.");if(input.agents.length<1||input.agents.length>999)throw new Error("S-2240 exige de 1 a 999 agentes, usando 09.01.001 quando não houver exposição.");
 const hasNoExposure=input.agents.some(a=>a.agentCode==="09.01.001");if(hasNoExposure&&input.agents.length!==1)throw new Error("Agente 09.01.001 não pode coexistir com outro agente.");
 const agents=input.agents.map(a=>{if(!/^\d{2}\.\d{2}\.\d{3}$/.test(a.agentCode))throw new Error(`Código de agente inválido: ${a.agentCode}`);if(a.agentCode==="09.01.001")return `<agNoc>${tag("codAgNoc",a.agentCode)}${opt("dscAgNoc",a.description)}</agNoc>`;if(!a.evaluationType)throw new Error(`Agente ${a.agentCode} exige tipo de avaliação.`);if(a.evaluationType===1&&(a.intensity===null||a.intensity===undefined||!a.unitCode||!a.measurementTechnique))throw new Error(`Agente quantitativo ${a.agentCode} exige intensidade, unidade e técnica.`);const utilizEpc=a.epcImplemented===null||a.epcImplemented===undefined?0:a.epcImplemented?2:1;const utilizEpi=a.epiUsed===null||a.epiUsed===undefined?0:a.epiUsed?2:1;if(utilizEpi===2&&(!a.epiDocuments||a.epiDocuments.length===0))throw new Error(`Agente ${a.agentCode} com EPI exige CA/documento de avaliação.`);const epis=(a.epiDocuments??[]).map(doc=>`<epi>${tag("docAval",doc)}</epi>`).join("");const compl=utilizEpi===2?`<epiCompl>${tag("medProtecao",yes(Boolean(a.protectiveMeasuresAttempted)))}${tag("condFuncto",yes(Boolean(a.epiUseConditionCompliant)))}${tag("usoInint",yes(Boolean(a.uninterruptedUseObserved)))}${tag("przValid",yes(Boolean(a.epiExpiryObserved)))}${tag("periodicTroca",yes(Boolean(a.epiChangeFrequencyObserved)))}${tag("higienizacao",yes(Boolean(a.epiCleaningObserved)))}</epiCompl>`:"";const epcEpi=`<epcEpi>${tag("utilizEPC",utilizEpc)}${utilizEpc===2?tag("eficEpc",yes(Boolean(a.epcEffective))):""}${tag("utilizEPI",utilizEpi)}${utilizEpi===2?tag("eficEpi",yes(Boolean(a.epiEffective))):""}${epis}${compl}</epcEpi>`;return `<agNoc>${tag("codAgNoc",a.agentCode)}${opt("dscAgNoc",a.description)}${tag("tpAval",a.evaluationType)}${a.evaluationType===1?tag("intConc",Number(a.intensity).toFixed(4)):""}${a.toleranceLimit!==null&&a.toleranceLimit!==undefined?tag("limTol",Number(a.toleranceLimit).toFixed(4)):""}${a.evaluationType===1?tag("unMed",a.unitCode):""}${a.evaluationType===1?tag("tecMedicao",a.measurementTechnique):""}${opt("nrProcJud",a.judicialProcessNumber)}${epcEpi}</agNoc>`;}).join("");
 if(!hasNoExposure&&!input.responsible)throw new Error("S-2240 com agente nocivo exige responsável pelos registros ambientais.");const resp=input.responsible?`<respReg>${tag("cpfResp",digits(input.responsible.cpf))}${opt("ideOC",input.responsible.classBody)}${input.responsible.classBody===9?opt("dscOC",input.responsible.classBodyDescription):""}${opt("nrOC",input.responsible.registrationNumber)}${opt("ufOC",input.responsible.state)}</respReg>`:"";const info=`<infoExpRisco>${tag("dtIniCondicao",input.conditionStart)}<infoAmb>${tag("localAmb",input.environmentLocationType)}${tag("dscSetor",input.sectorDescription)}${tag("tpInsc",input.environmentRegistrationType)}${tag("nrInsc",digits(input.environmentRegistrationNumber))}</infoAmb><infoAtiv>${tag("dscAtivDes",input.activityDescription)}</infoAtiv>${agents}${resp}${input.observation?`<obs>${tag("obsCompl",input.observation)}</obs>`:""}</infoExpRisco>`;
 return root(`http://www.esocial.gov.br/schema/evt/evtExpRisco/${LAYOUT}`,"evtExpRisco",eventKey,`${ideEvento(input.environment,input.receipt)}${ideEmpregador(input.employerType,input.employerNumber)}${ideVinculo(input.cpf,input.registrationNumber)}${info}`);
}
