import Link from"next/link";
import{ObservabilityNavigation}from"@/components/observability/observability-navigation";
import{MODULE_REGISTRY}from"@/lib/modules/registry";
import{dateTime,severityLabel}from"@/lib/observability/domain";
import{loadObservabilityEvents}from"@/lib/observability/server";

export const dynamic="force-dynamic";

export default async function ObservabilityEvents({searchParams}:{searchParams:Promise<{module?:string;severity?:string;q?:string;correlation?:string;page?:string;error?:string}>}){
 const query=await searchParams;const page=Math.max(1,Number(query.page)||1);const{events,error}=await loadObservabilityEvents({moduleKey:query.module,severity:query.severity,query:query.q,correlationId:query.correlation,page,pageSize:50});
 const base=new URLSearchParams();if(query.module)base.set("module",query.module);if(query.severity)base.set("severity",query.severity);if(query.q)base.set("q",query.q);if(query.correlation)base.set("correlation",query.correlation);
 return <main className="content observability-app"><section className="page-heading"><div><span className="badge">AUDITORIA · EVENTOS</span><h1>Fluxo unificado</h1><p>{events.total} evento(s) normalizados de auditoria, permissões, CRM, assinaturas, documentos, qualidade, compras, financeiro, relatórios, estoque e SAC.</p></div></section><ObservabilityNavigation/>{(query.error||error)&&<div className="validation blocking">{query.error||error}</div>}
 <form className="card card-pad observability-filter observability-filter-wide" method="get"><label>Módulo<select name="module" defaultValue={query.module??""}><option value="">Todos</option>{MODULE_REGISTRY.map(item=><option key={item.key} value={item.key}>{item.name}</option>)}</select></label><label>Severidade<select name="severity" defaultValue={query.severity??""}><option value="">Todas</option><option value="INFO">Informação</option><option value="WARNING">Atenção</option><option value="ERROR">Erro</option><option value="CRITICAL">Crítico</option></select></label><label>Busca<input name="q" defaultValue={query.q??""} placeholder="evento, recurso ou ação"/></label><label>Correlação<input name="correlation" defaultValue={query.correlation??""} placeholder="UUID"/></label><button className="button button-primary">Filtrar</button></form>
 <section className="card card-pad"><div className="observability-table-wrap"><table className="data-table observability-table"><thead><tr><th>Data</th><th>Severidade</th><th>Módulo</th><th>Evento</th><th>Recurso</th><th>Ator</th><th>Origem</th></tr></thead><tbody>{events.items.map(event=><tr key={`${event.origin_table}-${event.id}`}><td>{dateTime(event.occurred_at)}</td><td><span className={`severity severity-${String(event.severity).toLowerCase()}`}>{severityLabel(event.severity)}</span></td><td>{event.module_key??"sistema"}</td><td><Link className="text-link" href={`/app/auditoria/eventos/${event.id}?origin=${encodeURIComponent(event.origin_table)}`}>{event.event_type}</Link><small>{event.message??event.action}</small></td><td>{event.resource_type}<small>{event.resource_id??"—"}</small></td><td>{event.actor_type}<small>{event.actor_user_id??"sistema"}</small></td><td>{event.origin_table}</td></tr>)}</tbody></table>{!events.items.length&&<div className="empty-state"><h3>Nenhum evento encontrado</h3><p>Ajuste os filtros ou amplie o período consultado.</p></div>}</div>
 <nav className="observability-pagination"><span>Página {events.page} de {events.pages}</span><div>{page>1&&<Link className="button button-secondary" href={`?${base.toString()}&page=${page-1}`}>Anterior</Link>}{page<events.pages&&<Link className="button button-secondary" href={`?${base.toString()}&page=${page+1}`}>Próxima</Link>}</div></nav></section></main>;
}
