do $$
declare v_org uuid;v_user uuid;v_worker uuid;v_emp uuid;v_rub uuid;v_rv uuid;v_period uuid;v_run uuid;v_shadow uuid;v_raised boolean;
begin
 insert into auth.users(email) values('rh-shadow@innovar.local') returning id into v_user;insert into public.organizations(name) values('RH shadow teste') returning id into v_org;insert into public.organization_memberships(organization_id,user_id,role,active) values(v_org,v_user,'ADMIN',true);perform set_config('test.user_id',v_user::text,false);perform set_config('test.permission_granted','true',false);
 v_emp:=public.create_rh_worker(v_org,'Shadow Worker',null,'98765432100','1990-01-01',null,null,'SHW','SHW-001','EMPLOYEE','2026-01-01',3000);select worker_id into v_worker from public.rh_employments where id=v_emp;
 insert into public.rh_rubrics(organization_id,code,name,payroll_kind,created_by) values(v_org,'SALSH','Salário shadow','EARNING',v_user) returning id into v_rub;insert into public.rh_rubric_versions(organization_id,rubric_id,version,valid_from,formula_type,calculation_priority,status,created_by) values(v_org,v_rub,1,'2026-01-01','MANUAL',10,'PUBLISHED',v_user) returning id into v_rv;
 insert into public.rh_payroll_periods(organization_id,reference_month,processing_type,status,created_by) values(v_org,'2026-08-01','MONTHLY','OPEN',v_user) returning id into v_period;insert into public.rh_payroll_inputs(organization_id,period_id,employment_id,rubric_version_id,amount,source_type,created_by) values(v_org,v_period,v_emp,v_rv,3000,'MANUAL',v_user);v_run:=public.run_rh_payroll(v_period);
 v_shadow:=public.create_rh_payroll_shadow_run(v_run,'LEGADO','arquivo-001',0.01);
 perform public.set_rh_shadow_worker_external(v_shadow,v_emp,3000,0,3000,null);perform public.set_rh_shadow_rubric_external(v_shadow,v_emp,'SALSH',3000,null);perform public.reconcile_rh_payroll_shadow(v_shadow);
 if (select status from public.rh_payroll_shadow_runs where id=v_shadow)<>'RECONCILED' then raise exception 'SHADOW 1 falhou: comparação idêntica não reconciliou';end if;perform public.accept_rh_payroll_shadow(v_shadow,'caso idêntico');if (select status from public.rh_payroll_shadow_runs where id=v_shadow)<>'ACCEPTED' then raise exception 'SHADOW 2 falhou: aceite não persistiu';end if;
 v_shadow:=public.create_rh_payroll_shadow_run(v_run,'LEGADO','arquivo-002',0.01);perform public.set_rh_shadow_worker_external(v_shadow,v_emp,3001,0,3001,null);perform public.set_rh_shadow_rubric_external(v_shadow,v_emp,'SALSH',3001,null);perform public.reconcile_rh_payroll_shadow(v_shadow);if (select status from public.rh_payroll_shadow_runs where id=v_shadow)<>'DIVERGENT' then raise exception 'SHADOW 3 falhou: divergência não detectada';end if;
 v_raised:=false;begin perform public.accept_rh_payroll_shadow(v_shadow,'não deveria');exception when others then if sqlerrm like '%divergências ou lacunas%' then v_raised:=true;end if;end;if not v_raised then raise exception 'SHADOW 4 falhou: aceitou divergência';end if;
 raise notice 'RH shadow payroll — reconciliação e gate aprovados.';
end$$;
