import Link from"next/link";
import{MetricCard}from"@/components/reports/metric-card";
import{ReportNavigation}from"@/components/reports/report-navigation";
import{evaluateMetric,formatReportNumber,targetFor}from"@/lib/reports/metrics";
import{loadReportDashboard}from"@/lib/reports/server";

export const dynamic="force-dynamic";

export default async function ReportProjectDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{start?:string;end?:string}>}){
 const{id}=await params;const query=await searchParams;const{dashboard,start,end}=await loadReportDashboard({projectId:id,start:query.start,end:query.end});const project=dashboard.projects[0];
 if(!project)return <main className="content reports-app"><div className="empty-state"><h1>Obra não encontrada</h1><p>O registro não está no seu escopo de acesso.</p></div></main>;
 return <main className="content reports-app"><Link className="back-link" href="/app/relatorios/obras">← Indicadores por obra</Link><section className="page-heading"><div><span className="badge">{project.code} · {project.status}</span><h1>{project.name}</h1><p>Período de {new Date(`${start}T12:00:00`).toLocaleDateString("pt-BR")} a {new Date(`${end}T12:00:00`).toLocaleDateString("pt-BR")}.</p></div><Link className="button button-secondary" href={`/api/relatorios/exportar?projectId=${id}&start=${start}&end=${end}`}>Exportar CSV</Link></section><ReportNavigation/>
 <section className="stats-grid report-stats"><MetricCard label="AVANÇO REAL" value={formatReportNumber(project.actual_progress,"percent")} detail={`previsto ${formatReportNumber(project.planned_progress,"percent")}`} health={evaluateMetric(project.schedule_variance_pp,targetFor(dashboard.targets,"schedule_variance_pp",id))}/><MetricCard label="DIAS DE ATRASO" value={formatReportNumber(project.overdue_days)} detail="prazo contratual da obra" health={evaluateMetric(project.overdue_days,targetFor(dashboard.targets,"overdue_days",id))}/><MetricCard label="VALOR CONTRATADO" value={formatReportNumber(project.contract_value,"currency")} detail="valor consolidado"/><MetricCard label="COMPRAS COMPROMETIDAS" value={formatReportNumber(project.purchase_committed,"currency")} detail={`${project.open_purchase_orders} pedido(s) em aberto`}/><MetricCard label="QUALIDADE" value={formatReportNumber(project.average_quality_score,"percent")} detail={`${project.quality_rejected} resposta(s) rejeitada(s)`} health={evaluateMetric(project.average_quality_score,targetFor(dashboard.targets,"average_quality_score",id))}/><MetricCard label="NPS" value={formatReportNumber(project.nps,"score")} detail="satisfação do cliente" health={evaluateMetric(project.nps,targetFor(dashboard.targets,"nps",id))}/></section>
 <div className="report-three-column"><section className="card card-pad"><span className="eyebrow">PLANEJAMENTO</span><h2>Prazo e tarefas</h2><dl className="detail-list"><div><dt>Total de tarefas</dt><dd>{project.total_tasks}</dd></div><div><dt>Concluídas</dt><dd>{project.completed_tasks}</dd></div><div><dt>Bloqueadas</dt><dd>{project.blocked_tasks}</dd></div><div><dt>Atrasadas</dt><dd>{project.overdue_tasks}</dd></div><div><dt>Desvio de avanço</dt><dd>{formatReportNumber(project.schedule_variance_pp,"percent")}</dd></div></dl></section><section className="card card-pad"><span className="eyebrow">FINANCEIRO</span><h2>Posição da obra</h2><dl className="detail-list"><div><dt>A receber</dt><dd>{formatReportNumber(project.receivable_open,"currency")}</dd></div><div><dt>A pagar</dt><dd>{formatReportNumber(project.payable_open,"currency")}</dd></div><div><dt>Parcelas vencidas</dt><dd>{project.overdue_installments??"Restrito"}</dd></div><div><dt>Aprovações pendentes</dt><dd>{project.pending_finance_approvals??"Restrito"}</dd></div></dl></section><section className="card card-pad"><span className="eyebrow">CAMPO E QUALIDADE</span><h2>Evidências</h2><dl className="detail-list"><div><dt>Respostas de qualidade</dt><dd>{project.quality_responses}</dd></div><div><dt>Revisões pendentes</dt><dd>{project.pending_quality_reviews}</dd></div><div><dt>Atribuições abertas</dt><dd>{project.pending_quality_assignments}</dd></div><div><dt>Diários em 30 dias</dt><dd>{project.daily_logs_30d}</dd></div><div><dt>Documentos ativos</dt><dd>{project.project_documents}</dd></div></dl></section></div>
 <section className="card card-pad"><span className="eyebrow">FLUXO MENSAL</span><h2>Entradas e saídas da obra</h2>{dashboard.financialVisible?<div className="report-table-wrap"><table className="data-table"><thead><tr><th>Mês</th><th>Entrada prevista</th><th>Saída prevista</th><th>Saldo previsto</th><th>Entrada realizada</th><th>Saída realizada</th><th>Saldo realizado</th></tr></thead><tbody>{dashboard.financeMonthly.map(month=><tr key={month.periodMonth}><td>{new Date(`${month.periodMonth}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</td><td>{formatReportNumber(month.plannedInflow,"currency")}</td><td>{formatReportNumber(month.plannedOutflow,"currency")}</td><td>{formatReportNumber(month.plannedNet,"currency")}</td><td>{formatReportNumber(month.realizedInflow,"currency")}</td><td>{formatReportNumber(month.realizedOutflow,"currency")}</td><td>{formatReportNumber(month.realizedNet,"currency")}</td></tr>)}</tbody></table></div>:<div className="empty-state"><h3>Dados financeiros restritos</h3><p>O restante dos indicadores da obra permanece disponível.</p></div>}</section></main>;
}
