import Link from"next/link";
import{notFound}from"next/navigation";
import{sendEsocialBatchAction}from"@/app/actions/rh-esocial";
import{queryAndApplyEsocialBatch}from"@/app/actions/rh-esocial-processing";
import{requireCapability}from"@/lib/authorization";
import{esocialConfigurationStatus}from"@/lib/rh/integrations/government";

export const dynamic="force-dynamic";
export default async function EsocialBatchDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string}>}){
 const{id}=await params;const query=await searchParams;const context=await requireCapability("rh","read");const config=esocialConfigurationStatus();
 const[{data:batch,error:bError},{data:attempts,error:aError}]=await Promise.all([
  context.supabase.from("rh_esocial_batches").select("id,environment,event_group,employer_registration_type,employer_registration_number,transmitter_registration_type,transmitter_registration_number,communication_namespace_version,status,protocol_number,response_code,response_description,estimated_completion_seconds,created_at,sent_at,completed_at,rh_esocial_batch_events(position,rh_esocial_events(id,event_type,event_key,status,payload_sha256,receipt_number))").eq("organization_id",context.organizationId).eq("id",id).maybeSingle(),
  context.supabase.from("rh_esocial_attempts").select("id,operation,attempt_number,endpoint_url,soap_action,http_status,result,request_sha256,response_sha256,error_code,error_message,duration_ms,started_at,completed_at").eq("organization_id",context.organizationId).eq("batch_id",id).order("started_at",{ascending:false})
 ]);
 if(bError||aError)throw new Error(bError?.message??aError?.message??"Falha ao carregar lote.");if(!batch)notFound();const links=Array.isArray(batch.rh_esocial_batch_events)?batch.rh_esocial_batch_events:[];
 const canSend=["READY","UNKNOWN"].includes(batch.status)&&config.certificateConfigured&&config.privateKeyConfigured&&(batch.environment!=="PRODUCTION"||config.productionEnabled);
 const canQuery=Boolean(batch.protocol_number)&&["PROTOCOL_RECEIVED","PROCESSING","UNKNOWN"].includes(batch.status);
 return <main className="content"><section className="page-heading"><div><span className="badge">ESOCIAL · LOTE</span><h1>{batch.protocol_number??`Lote ${batch.id.slice(0,8)}`}</h1><p>{batch.environment} · grupo {batch.event_group} · {links.length} evento(s)</p></div><div className="page-actions"><Link className="button button-secondary" href="/app/rh/obrigacoes/esocial">Voltar</Link><span className="badge">{batch.status}</span></div></section>{query.error?<div className="validation blocking">{query.error}</div>:null}{query.success?<div className="alert alert-success">{query.success}</div>:null}
 <section className="stats-grid"><article className="card"><small>EVENTOS</small><strong>{links.length}</strong><span>máximo 50 por lote</span></article><article className="card"><small>PROTOCOLO</small><strong>{batch.protocol_number?"OK":"—"}</strong><span>{batch.protocol_number??"ainda não recebido"}</span></article><article className="card"><small>TENTATIVAS</small><strong>{attempts?.length??0}</strong><span>envio + consulta</span></article><article className="card"><small>RETORNO</small><strong>{batch.response_code??"—"}</strong><span>{batch.response_description??"sem retorno normalizado"}</span></article></section>
 <div className="finance-two-column"><section className="card card-pad"><span className="eyebrow">TRANSMISSÃO</span><h2>Enviar lote</h2><p>O envio usa HTTPS/mTLS diretamente para o endpoint oficial do ambiente selecionado. Cada evento precisa conter assinatura XMLDSig.</p>{!config.certificateConfigured||!config.privateKeyConfigured?<div className="validation blocking">Configure certificado/chave ou PFX no ambiente seguro do servidor antes de transmitir.</div>:null}{batch.environment==="PRODUCTION"&&!config.productionEnabled?<div className="validation blocking">Produção está bloqueada. Homologue em Produção Restrita.</div>:null}<form action={sendEsocialBatchAction}><input type="hidden" name="batchId" value={batch.id}/><button className="button button-primary" type="submit" disabled={!canSend}>Transmitir ao eSocial</button></form></section><section className="card card-pad"><span className="eyebrow">PROCESSAMENTO</span><h2>Consultar e aplicar retorno</h2><p>{batch.protocol_number?`Protocolo ${batch.protocol_number}`:"A consulta fica disponível depois que o envio retorna protocolo."}</p>{batch.estimated_completion_seconds?<p>Tempo estimado informado: {batch.estimated_completion_seconds}s.</p>:null}<form action={queryAndApplyEsocialBatch}><input type="hidden" name="batchId" value={batch.id}/><button className="button button-secondary" type="submit" disabled={!canQuery}>Consultar processamento</button></form></section></div>
 <section className="card" style={{overflowX:"auto"}}><div className="section-heading card-pad"><div><span className="eyebrow">EVENTOS DO LOTE</span><h2>Conteúdo correlacionado</h2></div></div><table className="data-table"><thead><tr><th>Posição</th><th>Evento</th><th>Chave</th><th>Status</th><th>Recibo</th><th>Hash</th></tr></thead><tbody>{links.sort((a,b)=>a.position-b.position).map(link=>{const event=Array.isArray(link.rh_esocial_events)?link.rh_esocial_events[0]:link.rh_esocial_events;return <tr key={link.position}><td>{link.position}</td><td>{event?<Link className="text-link" href={`/app/rh/obrigacoes/esocial/eventos/${event.id}`}><strong>{event.event_type}</strong></Link>:"—"}</td><td>{event?.event_key??"—"}</td><td><span className="badge">{event?.status??"—"}</span></td><td>{event?.receipt_number??"—"}</td><td><code>{event?.payload_sha256?`${event.payload_sha256.slice(0,12)}…`:"—"}</code></td></tr>})}</tbody></table></section>
 <section className="card" style={{overflowX:"auto"}}><div className="section-heading card-pad"><div><span className="eyebrow">TENTATIVAS</span><h2>Trilha técnica</h2></div></div><table className="data-table"><thead><tr><th>Operação</th><th>#</th><th>Início</th><th>HTTP</th><th>Resultado</th><th>Duração</th><th>Erro</th></tr></thead><tbody>{(attempts??[]).map(item=><tr key={item.id}><td>{item.operation}</td><td>{item.attempt_number}</td><td>{String(item.started_at).replace("T"," ").slice(0,19)}</td><td>{item.http_status??"—"}</td><td><span className="badge">{item.result}</span></td><td>{item.duration_ms!=null?`${item.duration_ms} ms`:"—"}</td><td><small>{item.error_code??""}{item.error_message?`${item.error_code?" · ":""}${item.error_message}`:"—"}</small></td></tr>)}{!attempts?.length?<tr><td colSpan={7}><div className="empty-state"><p>Nenhuma tentativa registrada.</p></div></td></tr>:null}</tbody></table></section>
 </main>;
}
