import Link from"next/link";
import{RelationshipMetric}from"@/components/relationship/relationship-metric";
import{RelationshipNavigation}from"@/components/relationship/relationship-navigation";
import{formatRelationshipDateTime,TICKET_PRIORITY_LABELS,TICKET_STATUS_LABELS,safeText}from"@/lib/relationship/domain";
import{loadSacDashboard}from"@/lib/relationship/server";

export const dynamic="force-dynamic";

function relationValue(value:unknown,key:string):unknown{
 const candidate=Array.isArray(value)?value[0]:value;
 return candidate!==null&&typeof candidate==="object"?Reflect.get(candidate,key):null;
}

export default async function SacDashboardPage(){const{dashboard,tickets}=await loadSacDashboard();return <main className="content relationship-app"><section className="page-heading"><div><span className="badge">APLICATIVO · PÓS-VENDA</span><h1>SAC e Ocorrências</h1><p>Atendimento interno e do portal, com SLA, mensagens, fotos, documentos, histórico e satisfação.</p></div><Link className="button button-primary" href="/app/ocorrencias/novo">Novo chamado</Link></section><RelationshipNavigation/><section className="stats-grid relationship-stats"><RelationshipMetric label="ABERTOS" value={String(dashboard.open)} detail="em acompanhamento" tone={dashboard.open>0?"warning":"ok"}/><RelationshipMetric label="ATRASADOS" value={String(dashboard.overdue)} detail="prazo de resolução vencido" tone={dashboard.overdue>0?"critical":"ok"}/><RelationshipMetric label="AGUARDANDO CLIENTE" value={String(dashboard.waitingClient)} detail="resposta necessária"/><RelationshipMetric label="SATISFAÇÃO MÉDIA" value={dashboard.averageSatisfaction===null?"—":`${dashboard.averageSatisfaction}/5`} detail={dashboard.averageResolutionHours===null?"sem resoluções":"tempo médio: "+dashboard.averageResolutionHours+" h"} tone="ok"/></section><section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">FILA DE ATENDIMENTO</span><h2>Chamados</h2></div></div><div className="report-table-wrap"><table className="data-table"><thead><tr><th>Código</th><th>Assunto</th><th>Cliente</th><th>Obra</th><th>Prioridade</th><th>Status</th><th>SLA</th><th>Atualizado</th></tr></thead><tbody>{tickets.map(ticket=><tr key={ticket.id}><td><Link href={`/app/ocorrencias/${ticket.id}`}>{safeText(ticket.code)}</Link></td><td>{safeText(ticket.title)}</td><td>{safeText(relationValue(ticket.clients,"trade_name"),"")||safeText(relationValue(ticket.clients,"legal_name"))}</td><td>{safeText(relationValue(ticket.projects,"code"),"")} {safeText(relationValue(ticket.projects,"name"),"")}</td><td><span className={`badge ${ticket.priority==="URGENT"?"badge-danger":""}`}>{TICKET_PRIORITY_LABELS[String(ticket.priority)]??ticket.priority}</span></td><td><span className="badge">{TICKET_STATUS_LABELS[String(ticket.status)]??ticket.status}</span></td><td>{formatRelationshipDateTime(ticket.resolution_due_at)}</td><td>{formatRelationshipDateTime(ticket.updated_at)}</td></tr>)}</tbody></table>{!tickets.length?<div className="empty-state"><h3>Nenhum chamado</h3><p>Quando a equipe ou o cliente abrir uma ocorrência, ela aparecerá aqui.</p></div>:null}</div></section></main>;}
