import{mensagemDeFalha}from"@/lib/errors/data-access";
import{createHash}from"node:crypto";
import{NextResponse}from"next/server";
import{requireCapability}from"@/lib/authorization";

function csv(value:unknown){const text=String(value??"");return `"${text.replaceAll('"','""')}"`;}
export async function POST(_request:Request,{params}:{params:Promise<{id:string}>}){const{id}=await params;const context=await requireCapability("rh","approve");const{data:batch,error:bError}=await context.supabase.from("rh_payroll_payment_batches").select("id,provider_code,file_format,status,period_id").eq("organization_id",context.organizationId).eq("id",id).maybeSingle();if(bError)return NextResponse.json({error:mensagemDeFalha("api.rh.payments.batches.[id].POST", bError)},{status:400});if(!batch)return NextResponse.json({error:"Lote não encontrado."},{status:404});if(!["DRAFT","GENERATED"].includes(batch.status))return NextResponse.json({error:`Lote ${batch.status} não permite geração.`},{status:409});
 const{data:items,error:iError}=await context.supabase.from("rh_payroll_payment_batch_items").select("sequence_number,rh_payroll_payments(id,amount,scheduled_date,payment_method,employment_id,rh_employments(registration_number,worker_id,rh_workers(worker_code,rh_people(full_name,cpf))))").eq("organization_id",context.organizationId).eq("batch_id",id).order("sequence_number");if(iError)return NextResponse.json({error:mensagemDeFalha("api.rh.payments.batches.[id].POST", iError)},{status:400});const workerIds=(items??[]).map(i=>{const p=Array.isArray(i.rh_payroll_payments)?i.rh_payroll_payments[0]:i.rh_payroll_payments;const e=p?(Array.isArray(p.rh_employments)?p.rh_employments[0]:p.rh_employments):null;return e?.worker_id??"";}).filter(Boolean);const{data:accounts,error:aError}=workerIds.length?await context.supabase.from("rh_worker_bank_accounts").select("worker_id,account_holder_tax_id,bank_code,branch_number,account_number,account_digit,account_type,pix_key_type,pix_key,priority,valid_from,valid_to").eq("organization_id",context.organizationId).eq("active",true).in("worker_id",workerIds).order("priority"):{data:[],error:null};if(aError)return NextResponse.json({error:mensagemDeFalha("api.rh.payments.batches.[id].POST", aError)},{status:400});
 const header=["sequence","payment_id","registration","worker_code","worker_name","holder_tax_id","amount","scheduled_date","method","bank_code","branch","account","account_digit","account_type","pix_key_type","pix_key"].map(csv).join(";");const rows=(items??[]).map(i=>{const p=Array.isArray(i.rh_payroll_payments)?i.rh_payroll_payments[0]:i.rh_payroll_payments;if(!p)throw new Error("Pagamento do item não encontrado.");const e=Array.isArray(p.rh_employments)?p.rh_employments[0]:p.rh_employments;if(!e)throw new Error("Vínculo do pagamento não encontrado.");const w=Array.isArray(e.rh_workers)?e.rh_workers[0]:e.rh_workers;const person=w?(Array.isArray(w.rh_people)?w.rh_people[0]:w.rh_people):null;const account=(accounts??[]).find(a=>a.worker_id===e.worker_id&&a.valid_from<=p.scheduled_date&&(!a.valid_to||a.valid_to>=p.scheduled_date));if(!account)throw new Error(`Conta ativa não encontrada para ${e.registration_number}.`);return[i.sequence_number,p.id,e.registration_number,w?.worker_code??"",person?.full_name??"",account.account_holder_tax_id,Number(p.amount).toFixed(2),p.scheduled_date,p.payment_method,account.bank_code??"",account.branch_number??"",account.account_number??"",account.account_digit??"",account.account_type??"",account.pix_key_type??"",account.pix_key??""].map(csv).join(";");});const content=`${header}\n${rows.join("\n")}\n`;const hash=createHash("sha256").update(content,"utf8").digest("hex");const fileName=`rh-pagamentos-${batch.period_id}-${id.slice(0,8)}.csv`;const{error:markError}=await context.supabase.rpc("mark_rh_payroll_payment_batch_generated",{p_batch_id:id,p_file_name:fileName,p_storage_path:`generated-on-demand:${hash}`,p_sha256:hash});if(markError&&batch.status!=="GENERATED")return NextResponse.json({error:mensagemDeFalha("api.rh.payments.batches.[id].POST", markError)},{status:400});return new NextResponse(content,{status:200,headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${fileName}"`,"Cache-Control":"no-store, private","X-Content-SHA256":hash}});}
