import {createProcurementSupplier} from "@/app/actions/procurement";
import {requireCapability} from "@/lib/authorization";

export const dynamic="force-dynamic";

export default async function ProcurementSuppliersPage(){
  const context=await requireCapability("compras","read");
  const{data:suppliers}=await context.supabase.from("procurement_suppliers").select("*").eq("organization_id",context.organizationId).neq("status","ARCHIVED").order("legal_name");
  return <main className="content procurement-app"><section className="page-heading"><div><span className="badge">COMPRAS</span><h1>Fornecedores convidados</h1><p>Cadastro interno. O fornecedor só acessa uma cotação por link seguro enviado pela equipe.</p></div></section><div className="procurement-two-column"><section className="card card-pad"><div className="section-heading"><div><span className="eyebrow">BASE DE FORNECEDORES</span><h2>{suppliers?.length??0} cadastro(s)</h2></div></div><div className="procurement-list">{(suppliers??[]).map(supplier=><article className="procurement-row" key={supplier.id}><div><strong>{supplier.trade_name||supplier.legal_name}</strong><small>{supplier.legal_name} · {supplier.email}</small><small>{supplier.categories?.join(", ")||"Sem categorias"}</small></div><span className="badge">{supplier.status}</span></article>)}{!suppliers?.length&&<div className="empty-state"><h3>Nenhum fornecedor cadastrado</h3><p>Cadastre internamente e gere o convite dentro de uma cotação.</p></div>}</div></section><aside><form action={createProcurementSupplier} className="card card-pad"><span className="eyebrow">NOVO FORNECEDOR</span><h2>Cadastro interno</h2><label>Razão social<input required name="legalName"/></label><label>Nome fantasia<input name="tradeName"/></label><label>CNPJ/CPF<input name="taxId"/></label><label>E-mail de cotação<input required name="email" type="email"/></label><label>Telefone<input name="phone"/></label><label>Categorias<input name="categories" placeholder="cimento, elétrica, hidráulica"/></label><label>Observações<textarea name="notes" rows={4}/></label><button className="button button-primary">Salvar fornecedor</button></form></aside></div></main>;
}
