import Link from"next/link";
import{MetricCard}from"@/components/reports/metric-card";
import{ReportNavigation}from"@/components/reports/report-navigation";
import{formatReportNumber}from"@/lib/reports/metrics";
import{loadReportDashboard}from"@/lib/reports/server";

export const dynamic="force-dynamic";

export default async function ReportsFinancePage({searchParams}:{searchParams:Promise<{projectId?:string;start?:string;end?:string}>}){
 const query=await searchParams;const{dashboard,projectId,start,end}=await loadReportDashboard({projectId:query.projectId,start:query.start,end:query.end});
 const executive=dashboard.executive;const plannedIn=dashboard.financeMonthly.reduce((sum,row)=>sum+row.plannedInflow,0);const plannedOut=dashboard.financeMonthly.reduce((sum,row)=>sum+row.plannedOutflow,0);const realizedIn=dashboard.financeMonthly.reduce((sum,row)=>sum+row.realizedInflow,0);const realizedOut=dashboard.financeMonthly.reduce((sum,row)=>sum+row.realizedOutflow,0);
 return <main className="content reports-app"><section className="page-heading"><div><span className="badge">RELATÓRIOS · FINANCEIRO</span><h1>Indicadores financeiros</h1><p>Posição de saldos, compromissos e fluxo de caixa previsto e realizado.</p></div><Link className="button button-secondary" href={`/api/relatorios/exportar?start=${start}&end=${end}${projectId?`&projectId=${projectId}`:""}`}>Exportar CSV</Link></section><ReportNavigation/>{dashboard.financialVisible?<><section className="stats-grid report-stats"><MetricCard label="A RECEBER" value={formatReportNumber(executive.receivableOpen,"currency")} detail="saldo em aberto"/><MetricCard label="A PAGAR" value={formatReportNumber(executive.payableOpen,"currency")} detail="saldo em aberto"/><MetricCard label="ENTRADAS PREVISTAS" value={formatReportNumber(plannedIn,"currency")} detail="período selecionado"/><MetricCard label="SAÍDAS PREVISTAS" value={formatReportNumber(plannedOut,"currency")} detail="período selecionado"/><MetricCard label="ENTRADAS REALIZADAS" value={formatReportNumber(realizedIn,"currency")} detail="baixas registradas"/><MetricCard label="SAÍDAS REALIZADAS" value={formatReportNumber(realizedOut,"currency")} detail="baixas registradas"/></section><section className="card card-pad report-table-wrap"><table className="data-table"><thead><tr><th>Mês</th><th>Entrada prevista</th><th>Saída prevista</th><th>Saldo previsto</th><th>Entrada realizada</th><th>Saída realizada</th><th>Saldo realizado</th></tr></thead><tbody>{dashboard.financeMonthly.map(month=><tr key={month.periodMonth}><td>{new Date(`${month.periodMonth}T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</td><td>{formatReportNumber(month.plannedInflow,"currency")}</td><td>{formatReportNumber(month.plannedOutflow,"currency")}</td><td>{formatReportNumber(month.plannedNet,"currency")}</td><td>{formatReportNumber(month.realizedInflow,"currency")}</td><td>{formatReportNumber(month.realizedOutflow,"currency")}</td><td>{formatReportNumber(month.realizedNet,"currency")}</td></tr>)}</tbody></table>{!dashboard.financeMonthly.length&&<div className="empty-state"><h3>Sem movimentação financeira</h3><p>Não existem parcelas ou baixas no período selecionado.</p></div>}</section></>:<div className="card card-pad empty-state"><h2>Acesso financeiro restrito</h2><p>Seu perfil pode consultar indicadores operacionais, mas não possui autorização para valores sensíveis.</p><Link className="button button-secondary" href="/app/relatorios">Voltar ao painel executivo</Link></div>}</main>;
}
