create table if not exists public.rh_payroll_shadow_runs(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,period_id uuid not null references public.rh_payroll_periods(id) on delete restrict,internal_run_id uuid not null references public.rh_payroll_runs(id) on delete restrict,
 source_system text not null,source_reference text,source_sha256 text check(source_sha256 is null or source_sha256~'^[a-f0-9]{64}$'),absolute_tolerance numeric(18,4) not null default 0.01 check(absolute_tolerance>=0),
 status text not null default 'DRAFT' check(status in('DRAFT','READY','RECONCILED','DIVERGENT','ACCEPTED','REJECTED','SUPERSEDED')),
 matched_workers integer not null default 0,divergent_workers integer not null default 0,missing_workers integer not null default 0,matched_lines integer not null default 0,divergent_lines integer not null default 0,missing_lines integer not null default 0,
 reconciled_by uuid references auth.users(id) on delete set null,reconciled_at timestamptz,approved_by uuid references auth.users(id) on delete set null,approved_at timestamptz,notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.rh_payroll_shadow_workers(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,shadow_run_id uuid not null,worker_result_id uuid not null references public.rh_payroll_worker_results(id) on delete restrict,employment_id uuid not null references public.rh_employments(id) on delete restrict,
 internal_gross numeric(18,2) not null,internal_deductions numeric(18,2) not null,internal_net numeric(18,2) not null,external_gross numeric(18,2),external_deductions numeric(18,2),external_net numeric(18,2),gross_difference numeric(18,2),deduction_difference numeric(18,2),net_difference numeric(18,2),status text not null default 'MISSING' check(status in('MISSING','MATCHED','DIVERGENT','IGNORED')),note text,updated_at timestamptz not null default now(),unique(shadow_run_id,worker_result_id)
);
create table if not exists public.rh_payroll_shadow_rubrics(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,shadow_run_id uuid not null,worker_result_id uuid not null references public.rh_payroll_worker_results(id) on delete restrict,employment_id uuid not null references public.rh_employments(id) on delete restrict,rubric_code text not null,
 internal_amount numeric(18,2) not null,external_amount numeric(18,2),difference_amount numeric(18,2),status text not null default 'MISSING' check(status in('MISSING','MATCHED','DIVERGENT','IGNORED')),note text,updated_at timestamptz not null default now(),unique(shadow_run_id,worker_result_id,rubric_code)
);
alter table public.rh_payroll_shadow_runs add constraint rh_payroll_shadow_runs_org_id_uq unique(organization_id,id);alter table public.rh_payroll_shadow_workers add constraint rh_payroll_shadow_workers_org_id_uq unique(organization_id,id);
alter table public.rh_payroll_shadow_runs add constraint rh_shadow_period_tenant_fk foreign key(organization_id,period_id) references public.rh_payroll_periods(organization_id,id) on delete restrict;
alter table public.rh_payroll_shadow_workers add constraint rh_shadow_workers_run_fk foreign key(organization_id,shadow_run_id) references public.rh_payroll_shadow_runs(organization_id,id) on delete cascade;
alter table public.rh_payroll_shadow_rubrics add constraint rh_shadow_rubrics_run_fk foreign key(organization_id,shadow_run_id) references public.rh_payroll_shadow_runs(organization_id,id) on delete cascade;
create index if not exists rh_shadow_runs_period_idx on public.rh_payroll_shadow_runs(organization_id,period_id,status);create index if not exists rh_shadow_workers_run_idx on public.rh_payroll_shadow_workers(organization_id,shadow_run_id,status);create index if not exists rh_shadow_rubrics_run_idx on public.rh_payroll_shadow_rubrics(organization_id,shadow_run_id,status);

do $$declare t text;begin foreach t in array array['rh_payroll_shadow_runs','rh_payroll_shadow_workers','rh_payroll_shadow_rubrics'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy rh_read on public.%I for select to authenticated using(public.has_module_permission(organization_id,''rh'',''READ'',null,null))',t);execute format('create policy rh_write on public.%I for all to authenticated using(public.has_module_permission(organization_id,''rh'',''EDIT'',null,null)) with check(public.has_module_permission(organization_id,''rh'',''EDIT'',null,null))',t);end loop;end$$;

create or replace function public.create_rh_payroll_shadow_run(p_internal_run_id uuid,p_source_system text,p_source_reference text default null,p_absolute_tolerance numeric default 0.01)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.rh_payroll_runs%rowtype;v_id uuid;begin
 select * into r from public.rh_payroll_runs where id=p_internal_run_id;if r.id is null then raise exception 'Execução interna não encontrada';end if;if r.status<>'COMPLETED' then raise exception 'Folha sombra exige execução COMPLETED';end if;if not public.has_module_permission(r.organization_id,'rh','EDIT',null,null) then raise exception 'FORBIDDEN';end if;if coalesce(p_source_system,'')='' then raise exception 'Sistema fonte externo obrigatório';end if;
 update public.rh_payroll_shadow_runs set status='SUPERSEDED',updated_at=now() where organization_id=r.organization_id and period_id=r.period_id and status in('DRAFT','READY','RECONCILED','DIVERGENT');
 insert into public.rh_payroll_shadow_runs(organization_id,period_id,internal_run_id,source_system,source_reference,absolute_tolerance,status,created_by) values(r.organization_id,r.period_id,r.id,p_source_system,p_source_reference,greatest(coalesce(p_absolute_tolerance,0.01),0),'DRAFT',auth.uid()) returning id into v_id;
 insert into public.rh_payroll_shadow_workers(organization_id,shadow_run_id,worker_result_id,employment_id,internal_gross,internal_deductions,internal_net)
 select r.organization_id,v_id,w.id,w.employment_id,w.gross_amount,w.deduction_amount,w.net_amount from public.rh_payroll_worker_results w where w.run_id=r.id;
 insert into public.rh_payroll_shadow_rubrics(organization_id,shadow_run_id,worker_result_id,employment_id,rubric_code,internal_amount)
 select r.organization_id,v_id,l.worker_result_id,w.employment_id,ru.code,round(sum(case when ru.payroll_kind='DEDUCTION' then -l.amount else l.amount end),2)
 from public.rh_payroll_result_lines l join public.rh_payroll_worker_results w on w.id=l.worker_result_id join public.rh_rubric_versions rv on rv.id=l.rubric_version_id join public.rh_rubrics ru on ru.id=rv.rubric_id where w.run_id=r.id group by l.worker_result_id,w.employment_id,ru.code;
 return v_id;
end$$;grant execute on function public.create_rh_payroll_shadow_run(uuid,text,text,numeric) to authenticated;

create or replace function public.set_rh_shadow_worker_external(p_shadow_run_id uuid,p_employment_id uuid,p_gross numeric,p_deductions numeric,p_net numeric,p_note text default null)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_org uuid;begin select organization_id into v_org from public.rh_payroll_shadow_runs where id=p_shadow_run_id;if v_org is null then raise exception 'Shadow run não encontrado';end if;if not public.has_module_permission(v_org,'rh','EDIT',null,null) then raise exception 'FORBIDDEN';end if;update public.rh_payroll_shadow_workers set external_gross=p_gross,external_deductions=p_deductions,external_net=p_net,note=p_note,updated_at=now() where shadow_run_id=p_shadow_run_id and employment_id=p_employment_id;if not found then raise exception 'Vínculo não pertence ao shadow run';end if;update public.rh_payroll_shadow_runs set status='READY',updated_at=now() where id=p_shadow_run_id and status='DRAFT';end$$;grant execute on function public.set_rh_shadow_worker_external(uuid,uuid,numeric,numeric,numeric,text) to authenticated;
create or replace function public.set_rh_shadow_rubric_external(p_shadow_run_id uuid,p_employment_id uuid,p_rubric_code text,p_amount numeric,p_note text default null)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_org uuid;begin select organization_id into v_org from public.rh_payroll_shadow_runs where id=p_shadow_run_id;if v_org is null then raise exception 'Shadow run não encontrado';end if;if not public.has_module_permission(v_org,'rh','EDIT',null,null) then raise exception 'FORBIDDEN';end if;update public.rh_payroll_shadow_rubrics set external_amount=p_amount,note=p_note,updated_at=now() where shadow_run_id=p_shadow_run_id and employment_id=p_employment_id and rubric_code=p_rubric_code;if not found then raise exception 'Rubrica/vínculo não pertence ao shadow run';end if;update public.rh_payroll_shadow_runs set status='READY',updated_at=now() where id=p_shadow_run_id and status='DRAFT';end$$;grant execute on function public.set_rh_shadow_rubric_external(uuid,uuid,text,numeric,text) to authenticated;

create or replace function public.reconcile_rh_payroll_shadow(p_shadow_run_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare s public.rh_payroll_shadow_runs%rowtype;begin select * into s from public.rh_payroll_shadow_runs where id=p_shadow_run_id for update;if s.id is null then raise exception 'Shadow run não encontrado';end if;if not public.has_module_permission(s.organization_id,'rh','READ',null,'approve') then raise exception 'FORBIDDEN';end if;
 update public.rh_payroll_shadow_workers set gross_difference=case when external_gross is null then null else round(external_gross-internal_gross,2) end,deduction_difference=case when external_deductions is null then null else round(external_deductions-internal_deductions,2) end,net_difference=case when external_net is null then null else round(external_net-internal_net,2) end,status=case when external_gross is null or external_deductions is null or external_net is null then 'MISSING' when abs(external_gross-internal_gross)<=s.absolute_tolerance and abs(external_deductions-internal_deductions)<=s.absolute_tolerance and abs(external_net-internal_net)<=s.absolute_tolerance then 'MATCHED' else 'DIVERGENT' end,updated_at=now() where shadow_run_id=s.id and status<>'IGNORED';
 update public.rh_payroll_shadow_rubrics set difference_amount=case when external_amount is null then null else round(external_amount-internal_amount,2) end,status=case when external_amount is null then 'MISSING' when abs(external_amount-internal_amount)<=s.absolute_tolerance then 'MATCHED' else 'DIVERGENT' end,updated_at=now() where shadow_run_id=s.id and status<>'IGNORED';
 update public.rh_payroll_shadow_runs r set matched_workers=x.mw,divergent_workers=x.dw,missing_workers=x.xw,matched_lines=x.ml,divergent_lines=x.dl,missing_lines=x.xl,status=case when x.dw=0 and x.xw=0 and x.dl=0 and x.xl=0 then 'RECONCILED' else 'DIVERGENT' end,reconciled_by=auth.uid(),reconciled_at=now(),updated_at=now()
 from(select (select count(*) from public.rh_payroll_shadow_workers where shadow_run_id=s.id and status='MATCHED')mw,(select count(*) from public.rh_payroll_shadow_workers where shadow_run_id=s.id and status='DIVERGENT')dw,(select count(*) from public.rh_payroll_shadow_workers where shadow_run_id=s.id and status='MISSING')xw,(select count(*) from public.rh_payroll_shadow_rubrics where shadow_run_id=s.id and status='MATCHED')ml,(select count(*) from public.rh_payroll_shadow_rubrics where shadow_run_id=s.id and status='DIVERGENT')dl,(select count(*) from public.rh_payroll_shadow_rubrics where shadow_run_id=s.id and status='MISSING')xl)x where r.id=s.id;
end$$;grant execute on function public.reconcile_rh_payroll_shadow(uuid) to authenticated;

create or replace function public.accept_rh_payroll_shadow(p_shadow_run_id uuid,p_notes text default null)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare s public.rh_payroll_shadow_runs%rowtype;begin select * into s from public.rh_payroll_shadow_runs where id=p_shadow_run_id for update;if s.id is null then raise exception 'Shadow run não encontrado';end if;if not public.has_module_permission(s.organization_id,'rh','READ',null,'approve') then raise exception 'FORBIDDEN';end if;if s.status<>'RECONCILED' or s.divergent_workers<>0 or s.missing_workers<>0 or s.divergent_lines<>0 or s.missing_lines<>0 then raise exception 'Shadow payroll possui divergências ou lacunas';end if;update public.rh_payroll_shadow_runs set status='ACCEPTED',approved_by=auth.uid(),approved_at=now(),notes=p_notes,updated_at=now() where id=s.id;end$$;grant execute on function public.accept_rh_payroll_shadow(uuid,text) to authenticated;
