create table if not exists public.rh_vacation_entitlements(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,
  employment_id uuid not null references public.rh_employments(id) on delete restrict,
  acquisition_start date not null,acquisition_end date not null,days_entitled numeric(6,2) not null check(days_entitled>=0),days_used numeric(6,2) not null default 0 check(days_used>=0),
  status text not null default 'OPEN' check(status in('OPEN','PARTIAL','CONSUMED','CANCELLED')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),
  unique(organization_id,employment_id,acquisition_start,acquisition_end),check(acquisition_end>=acquisition_start),check(days_used<=days_entitled)
);
create table if not exists public.rh_vacation_cases(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,
  entitlement_id uuid not null references public.rh_vacation_entitlements(id) on delete restrict,employment_id uuid not null references public.rh_employments(id) on delete restrict,
  vacation_start date not null,vacation_end date not null,days numeric(6,2) not null check(days>0),cash_conversion_days numeric(6,2) not null default 0 check(cash_conversion_days>=0),
  divisor_days numeric(6,2) not null default 30 check(divisor_days>0),remuneration_base numeric(18,2) not null,average_amount numeric(18,2) not null default 0,pay_date date,
  status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','EXPORTED_TO_PAYROLL','PAID','IN_PROGRESS','COMPLETED','CANCELLED')),
  reason text,evidence_reference text,approved_by uuid references auth.users(id) on delete set null,approved_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  check(vacation_end>=vacation_start),check(cash_conversion_days<=days)
);
create table if not exists public.rh_vacation_payroll_exports(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,vacation_case_id uuid not null references public.rh_vacation_cases(id) on delete restrict,
  payroll_period_id uuid not null references public.rh_payroll_periods(id) on delete restrict,export_kind text not null check(export_kind in('VACATION','ONE_THIRD','CASH_CONVERSION')),
  rubric_version_id uuid not null references public.rh_rubric_versions(id) on delete restrict,payroll_input_id uuid not null references public.rh_payroll_inputs(id) on delete restrict,amount numeric(18,2) not null,
  created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(vacation_case_id,payroll_period_id,export_kind)
);

create table if not exists public.rh_leave_cases(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,employment_id uuid not null references public.rh_employments(id) on delete restrict,
  leave_type text not null,internal_reason text not null,esocial_reason_code text,start_date date not null,end_date date,paid_percentage numeric(7,4) check(paid_percentage is null or(paid_percentage>=0 and paid_percentage<=100)),
  status text not null default 'OPEN' check(status in('DRAFT','OPEN','EXTERNAL_PENDING','ACTIVE','RETURN_PENDING','CLOSED','CANCELLED')),document_reference text,return_fitness_required boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date is null or end_date>=start_date)
);

create table if not exists public.rh_benefit_catalog(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code text not null,name text not null,benefit_type text not null,
  provider_name text,employee_share_type text not null default 'FIXED' check(employee_share_type in('FIXED','PERCENT','NONE','VARIABLE')),employee_share_value numeric(18,4),active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(organization_id,code)
);
create table if not exists public.rh_benefit_enrollments(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,employment_id uuid not null references public.rh_employments(id) on delete restrict,benefit_id uuid not null references public.rh_benefit_catalog(id) on delete restrict,
  valid_from date not null,valid_to date,status text not null default 'ACTIVE' check(status in('PENDING','ACTIVE','SUSPENDED','ENDED','CANCELLED')),plan_reference text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),check(valid_to is null or valid_to>valid_from)
);
create table if not exists public.rh_benefit_charges(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,enrollment_id uuid not null references public.rh_benefit_enrollments(id) on delete restrict,reference_month date not null,
  provider_amount numeric(18,2) not null default 0,employer_amount numeric(18,2) not null default 0,employee_amount numeric(18,2) not null default 0,copay_amount numeric(18,2) not null default 0,
  source_reference text,status text not null default 'PENDING' check(status in('PENDING','VALIDATED','EXPORTED_TO_PAYROLL','RECONCILED','CANCELLED')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(enrollment_id,reference_month)
);
create table if not exists public.rh_benefit_payroll_exports(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,charge_id uuid not null references public.rh_benefit_charges(id) on delete restrict,payroll_period_id uuid not null references public.rh_payroll_periods(id) on delete restrict,rubric_version_id uuid not null references public.rh_rubric_versions(id) on delete restrict,payroll_input_id uuid not null references public.rh_payroll_inputs(id) on delete restrict,amount numeric(18,2) not null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(charge_id,payroll_period_id)
);

alter table public.rh_vacation_entitlements add constraint rh_vacation_entitlements_org_id_uq unique(organization_id,id);alter table public.rh_vacation_cases add constraint rh_vacation_cases_org_id_uq unique(organization_id,id);alter table public.rh_benefit_catalog add constraint rh_benefit_catalog_org_id_uq unique(organization_id,id);alter table public.rh_benefit_enrollments add constraint rh_benefit_enrollments_org_id_uq unique(organization_id,id);
alter table public.rh_vacation_entitlements add constraint rh_vacation_emp_tenant_fk foreign key(organization_id,employment_id) references public.rh_employments(organization_id,id) on delete restrict;
alter table public.rh_vacation_cases add constraint rh_vacation_case_ent_tenant_fk foreign key(organization_id,entitlement_id) references public.rh_vacation_entitlements(organization_id,id) on delete restrict;alter table public.rh_vacation_cases add constraint rh_vacation_case_emp_tenant_fk foreign key(organization_id,employment_id) references public.rh_employments(organization_id,id) on delete restrict;
alter table public.rh_leave_cases add constraint rh_leave_emp_tenant_fk foreign key(organization_id,employment_id) references public.rh_employments(organization_id,id) on delete restrict;
alter table public.rh_benefit_enrollments add constraint rh_benefit_emp_tenant_fk foreign key(organization_id,employment_id) references public.rh_employments(organization_id,id) on delete restrict;alter table public.rh_benefit_enrollments add constraint rh_benefit_catalog_tenant_fk foreign key(organization_id,benefit_id) references public.rh_benefit_catalog(organization_id,id) on delete restrict;

do $$ declare t text;begin foreach t in array array['rh_vacation_entitlements','rh_vacation_cases','rh_vacation_payroll_exports','rh_leave_cases','rh_benefit_catalog','rh_benefit_enrollments','rh_benefit_charges','rh_benefit_payroll_exports'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy rh_read on public.%I for select to authenticated using(public.has_module_permission(organization_id,''rh'',''READ'',null,null))',t);execute format('create policy rh_write on public.%I for all to authenticated using(public.has_module_permission(organization_id,''rh'',''EDIT'',null,null)) with check(public.has_module_permission(organization_id,''rh'',''EDIT'',null,null))',t);end loop;end$$;

create or replace function public.approve_rh_vacation_case(p_case_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.rh_vacation_cases%rowtype;e public.rh_vacation_entitlements%rowtype;v_used numeric;
begin select * into c from public.rh_vacation_cases where id=p_case_id for update;if c.id is null then raise exception 'Férias não encontradas';end if;if not public.has_module_permission(c.organization_id,'rh','READ',null,'approve') then raise exception 'FORBIDDEN';end if;if c.status='APPROVED' then return;end if;if c.status<>'DRAFT' then raise exception 'Estado não permite aprovação';end if;select * into e from public.rh_vacation_entitlements where id=c.entitlement_id for update;v_used:=c.days+c.cash_conversion_days;if e.days_entitled-e.days_used<v_used then raise exception 'Saldo de férias insuficiente';end if;update public.rh_vacation_entitlements set days_used=days_used+v_used,status=case when days_used+v_used>=days_entitled then 'CONSUMED' else 'PARTIAL' end where id=e.id;update public.rh_vacation_cases set status='APPROVED',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=c.id;end$$;grant execute on function public.approve_rh_vacation_case(uuid) to authenticated;

create or replace function public.export_rh_vacation_to_payroll(p_case_id uuid,p_payroll_period_id uuid,p_vacation_rubric uuid,p_third_rubric uuid,p_cash_rubric uuid default null)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.rh_vacation_cases%rowtype;v_base numeric;v_vac numeric;v_third numeric;v_cash numeric;v_input uuid;
begin select * into c from public.rh_vacation_cases where id=p_case_id for update;if c.id is null then raise exception 'Férias não encontradas';end if;if not public.has_module_permission(c.organization_id,'rh','EDIT',null,null) then raise exception 'FORBIDDEN';end if;if c.status not in('APPROVED','EXPORTED_TO_PAYROLL') then raise exception 'Férias precisam estar aprovadas';end if;if not exists(select 1 from public.rh_payroll_periods where id=p_payroll_period_id and organization_id=c.organization_id and status in('OPEN','CALCULATED','REVIEW','REOPENED')) then raise exception 'Competência inválida';end if;v_base:=c.remuneration_base+c.average_amount;v_vac:=round(v_base*c.days/c.divisor_days,2);v_third:=round(v_vac/3,2);v_cash:=round(v_base*c.cash_conversion_days/c.divisor_days,2);
 if not exists(select 1 from public.rh_vacation_payroll_exports where vacation_case_id=c.id and payroll_period_id=p_payroll_period_id and export_kind='VACATION') then insert into public.rh_payroll_inputs(organization_id,period_id,employment_id,rubric_version_id,amount,source_type,source_reference,created_by) values(c.organization_id,p_payroll_period_id,c.employment_id,p_vacation_rubric,v_vac,'VACATION',c.id::text,auth.uid()) returning id into v_input;insert into public.rh_vacation_payroll_exports values(default,c.organization_id,c.id,p_payroll_period_id,'VACATION',p_vacation_rubric,v_input,v_vac,auth.uid(),now());end if;
 if not exists(select 1 from public.rh_vacation_payroll_exports where vacation_case_id=c.id and payroll_period_id=p_payroll_period_id and export_kind='ONE_THIRD') then insert into public.rh_payroll_inputs(organization_id,period_id,employment_id,rubric_version_id,amount,source_type,source_reference,created_by) values(c.organization_id,p_payroll_period_id,c.employment_id,p_third_rubric,v_third,'VACATION',c.id::text,auth.uid()) returning id into v_input;insert into public.rh_vacation_payroll_exports values(default,c.organization_id,c.id,p_payroll_period_id,'ONE_THIRD',p_third_rubric,v_input,v_third,auth.uid(),now());end if;
 if c.cash_conversion_days>0 and p_cash_rubric is not null and not exists(select 1 from public.rh_vacation_payroll_exports where vacation_case_id=c.id and payroll_period_id=p_payroll_period_id and export_kind='CASH_CONVERSION') then insert into public.rh_payroll_inputs(organization_id,period_id,employment_id,rubric_version_id,amount,source_type,source_reference,created_by) values(c.organization_id,p_payroll_period_id,c.employment_id,p_cash_rubric,v_cash,'VACATION',c.id::text,auth.uid()) returning id into v_input;insert into public.rh_vacation_payroll_exports values(default,c.organization_id,c.id,p_payroll_period_id,'CASH_CONVERSION',p_cash_rubric,v_input,v_cash,auth.uid(),now());end if;
 update public.rh_vacation_cases set status='EXPORTED_TO_PAYROLL',updated_at=now() where id=c.id;end$$;grant execute on function public.export_rh_vacation_to_payroll(uuid,uuid,uuid,uuid,uuid) to authenticated;

create or replace function public.export_rh_benefit_charge_to_payroll(p_charge_id uuid,p_payroll_period_id uuid,p_rubric_version_id uuid)
returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.rh_benefit_charges%rowtype;v_emp uuid;v_input uuid;v_amount numeric;
begin select * into c from public.rh_benefit_charges where id=p_charge_id for update;if c.id is null then raise exception 'Cobrança não encontrada';end if;if not public.has_module_permission(c.organization_id,'rh','EDIT',null,null) then raise exception 'FORBIDDEN';end if;select employment_id into v_emp from public.rh_benefit_enrollments where id=c.enrollment_id;v_amount:=c.employee_amount+c.copay_amount;if exists(select 1 from public.rh_benefit_payroll_exports where charge_id=c.id and payroll_period_id=p_payroll_period_id) then select payroll_input_id into v_input from public.rh_benefit_payroll_exports where charge_id=c.id and payroll_period_id=p_payroll_period_id;return v_input;end if;insert into public.rh_payroll_inputs(organization_id,period_id,employment_id,rubric_version_id,amount,source_type,source_reference,created_by) values(c.organization_id,p_payroll_period_id,v_emp,p_rubric_version_id,v_amount,'BENEFIT',c.id::text,auth.uid()) returning id into v_input;insert into public.rh_benefit_payroll_exports(organization_id,charge_id,payroll_period_id,rubric_version_id,payroll_input_id,amount,created_by) values(c.organization_id,c.id,p_payroll_period_id,p_rubric_version_id,v_input,v_amount,auth.uid());update public.rh_benefit_charges set status='EXPORTED_TO_PAYROLL' where id=c.id;return v_input;end$$;grant execute on function public.export_rh_benefit_charge_to_payroll(uuid,uuid,uuid) to authenticated;
