import{MetricCard}from"@/components/reports/metric-card";
import{ReportNavigation}from"@/components/reports/report-navigation";
import{evaluateMetric,formatReportNumber,targetFor}from"@/lib/reports/metrics";
import{loadReportDashboard}from"@/lib/reports/server";

export const dynamic="force-dynamic";

export default async function ReportsProcurementPage(){
 const{dashboard}=await loadReportDashboard({});const committed=dashboard.projects.reduce((sum,row)=>sum+(row.purchase_committed??0),0);const openOrders=dashboard.projects.reduce((sum,row)=>sum+row.open_purchase_orders,0);const overdue=dashboard.projects.reduce((sum,row)=>sum+row.overdue_purchase_orders,0);const openRequests=dashboard.projects.reduce((sum,row)=>sum+row.open_purchase_requests,0);const receipts=dashboard.projects.reduce((sum,row)=>sum+row.accepted_receipts,0);
 return <main className="content reports-app"><section className="page-heading"><div><span className="badge">RELATÓRIOS · COMPRAS</span><h1>Indicadores de Compras</h1><p>Solicitações, pedidos, recebimentos e atrasos por obra.</p></div></section><ReportNavigation/><section className="stats-grid report-stats"><MetricCard label="COMPRAS COMPROMETIDAS" value={formatReportNumber(dashboard.financialVisible?committed:null,"currency")} detail="pedidos não cancelados"/><MetricCard label="PEDIDOS EM ABERTO" value={formatReportNumber(openOrders)} detail="emitidos ou parcialmente recebidos"/><MetricCard label="PEDIDOS ATRASADOS" value={formatReportNumber(overdue)} detail="entrega prevista vencida" health={evaluateMetric(overdue,targetFor(dashboard.targets,"overdue_purchase_orders"))}/><MetricCard label="SOLICITAÇÕES ABERTAS" value={formatReportNumber(openRequests)} detail="ainda não encerradas"/><MetricCard label="RECEBIMENTOS ACEITOS" value={formatReportNumber(receipts)} detail="aceitos ou com ressalva"/></section><section className="card card-pad report-table-wrap"><table className="data-table"><thead><tr><th>Obra</th><th>Comprometido</th><th>Pedidos abertos</th><th>Pedidos atrasados</th><th>Solicitações abertas</th><th>Recebimentos aceitos</th></tr></thead><tbody>{dashboard.projects.map(project=><tr key={project.project_id}><td><strong>{project.code} · {project.name}</strong></td><td>{formatReportNumber(project.purchase_committed,"currency")}</td><td>{project.open_purchase_orders}</td><td><span className={project.overdue_purchase_orders>0?"report-health-text report-health-warning":""}>{project.overdue_purchase_orders}</span></td><td>{project.open_purchase_requests}</td><td>{project.accepted_receipts}</td></tr>)}</tbody></table>{!dashboard.projects.length&&<div className="empty-state"><h3>Sem obras no escopo</h3><p>Os indicadores de compras serão exibidos quando houver obras autorizadas.</p></div>}</section></main>;
}
