import Link from"next/link";
import{notFound}from"next/navigation";
import{requireCapability}from"@/lib/authorization";

export const dynamic="force-dynamic";
export default async function EsocialEventDetailPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const context=await requireCapability("rh","read");
 const{data:event,error}=await context.supabase.from("rh_esocial_events").select("id,event_type,event_key,event_group,operation,environment,employer_registration_type,employer_registration_number,transmitter_registration_type,transmitter_registration_number,layout_version,source_type,source_id,payload_sha256,status,receipt_number,response_code,response_description,occurrences,created_at,updated_at,rh_esocial_batch_events(batch_id,position,rh_esocial_batches(status,protocol_number,created_at))").eq("organization_id",context.organizationId).eq("id",id).maybeSingle();
 if(error)throw new Error(error.message);if(!event)notFound();
 const batchLinks=Array.isArray(event.rh_esocial_batch_events)?event.rh_esocial_batch_events:[];
 return <main className="content"><section className="page-heading"><div><span className="badge">ESOCIAL · EVENTO</span><h1>{event.event_type}</h1><p>{event.event_key}</p></div><div className="page-actions"><Link className="button button-secondary" href="/app/rh/obrigacoes/esocial">Voltar à fila</Link><span className="badge">{event.status}</span></div></section>
 <div className="finance-two-column"><section className="card card-pad"><span className="eyebrow">IDENTIDADE</span><dl className="detail-list"><div><dt>Operação</dt><dd>{event.operation}</dd></div><div><dt>Grupo</dt><dd>{event.event_group}</dd></div><div><dt>Ambiente</dt><dd>{event.environment}</dd></div><div><dt>Leiaute</dt><dd>{event.layout_version}</dd></div><div><dt>Origem</dt><dd>{event.source_type}{event.source_id?` · ${event.source_id}`:""}</dd></div></dl></section><section className="card card-pad"><span className="eyebrow">INTEGRIDADE</span><dl className="detail-list"><div><dt>SHA-256</dt><dd><code>{event.payload_sha256}</code></dd></div><div><dt>Criado</dt><dd>{String(event.created_at).replace("T"," ").slice(0,19)}</dd></div><div><dt>Atualizado</dt><dd>{String(event.updated_at).replace("T"," ").slice(0,19)}</dd></div><div><dt>Recibo</dt><dd>{event.receipt_number??"—"}</dd></div></dl></section></div>
 <section className="card card-pad"><span className="eyebrow">PARTES</span><h2>Empregador e transmissor</h2><dl className="detail-list"><div><dt>Empregador</dt><dd>tpInsc {event.employer_registration_type} · {event.employer_registration_number}</dd></div><div><dt>Transmissor</dt><dd>tpInsc {event.transmitter_registration_type} · {event.transmitter_registration_number}</dd></div></dl></section>
 <section className="card card-pad"><span className="eyebrow">RETORNO</span><h2>{event.response_code??"Sem processamento externo"}</h2><p>{event.response_description??"O evento ainda não possui retorno normalizado do Ambiente Nacional."}</p>{Array.isArray(event.occurrences)&&event.occurrences.length?<pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(event.occurrences,null,2)}</pre>:null}</section>
 <section className="card card-pad"><span className="eyebrow">LOTES</span><h2>Histórico de agrupamento</h2><div className="finance-list">{batchLinks.map(link=>{const batch=Array.isArray(link.rh_esocial_batches)?link.rh_esocial_batches[0]:link.rh_esocial_batches;return <div className="finance-row" key={link.batch_id}><div><Link className="text-link" href={`/app/rh/obrigacoes/esocial/lotes/${link.batch_id}`}>Lote · posição {link.position}</Link><small>{batch?.protocol_number??"sem protocolo"}</small></div><span className="badge">{batch?.status??"—"}</span></div>})}{!batchLinks.length?<div className="empty-state"><p>Evento ainda não pertence a lote.</p></div>:null}</div></section>
 <section className="card card-pad"><div className="validation"><strong>XML protegido:</strong> esta tela não renderiza o XML assinado bruto. O conteúdo fica persistido sob RLS para composição/transmissão e auditoria autorizada.</div></section>
 </main>;
}
