import Link from"next/link";
import{createInventoryWarehouse}from"@/app/actions/inventory";
import{InventoryNavigation}from"@/components/inventory/inventory-navigation";
import{hasCapability,requireCapability}from"@/lib/authorization";
import{formatInventoryCurrency,formatInventoryQuantity}from"@/lib/inventory/domain";
import{loadInventoryDashboard}from"@/lib/inventory/server";

export const dynamic="force-dynamic";

export default async function InventoryWarehousesPage({searchParams}:{searchParams:Promise<{error?:string}>}){const query=await searchParams;const context=await requireCapability("estoque","read");const canCreate=await hasCapability("estoque","create",null,context);const[{data:projects},{dashboard}]=await Promise.all([context.supabase.from("projects").select("id,code,name").eq("organization_id",context.organizationId).is("archived_at",null).order("name"),loadInventoryDashboard()]);return <main className="content inventory-app"><section className="page-heading"><div><span className="badge">ESTOQUE · ESTRUTURA</span><h1>Depósitos e almoxarifados</h1><p>Estrutura geral, por obra ou móvel, com saldo e reservas por localização.</p></div></section><InventoryNavigation/>{query.error&&<div className="validation blocking">{query.error}</div>}<section className="inventory-warehouse-grid">{dashboard.warehouses.map(warehouse=><Link className="card card-pad inventory-warehouse-card" href={`/app/estoque/depositos/${warehouse.id}`} key={warehouse.id}><header><div><span className="eyebrow">{warehouse.code} · {warehouse.kind}</span><h2>{warehouse.name}</h2></div><span className="badge">ATIVO</span></header><dl className="detail-list"><div><dt>Saldo físico</dt><dd>{formatInventoryQuantity(warehouse.physicalQuantity)}</dd></div><div><dt>Reservado</dt><dd>{formatInventoryQuantity(warehouse.reservedQuantity)}</dd></div><div><dt>Disponível</dt><dd>{formatInventoryQuantity(warehouse.availableQuantity)}</dd></div><div><dt>Valor estimado</dt><dd>{formatInventoryCurrency(warehouse.stockValue)}</dd></div></dl></Link>)}{!dashboard.warehouses.length&&<div className="empty-state"><h3>Nenhum depósito</h3><p>Cadastre o primeiro almoxarifado da organização.</p></div>}</section>{canCreate&&<form action={createInventoryWarehouse} className="card card-pad inventory-form"><div className="section-heading"><div><span className="eyebrow">NOVO DEPÓSITO</span><h2>Cadastrar estrutura</h2></div></div><div className="form-grid form-grid-3"><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><label>Tipo<select name="kind"><option value="GENERAL">Geral</option><option value="PROJECT">Por obra</option><option value="MOBILE">Móvel</option><option value="EXTERNAL">Externo</option></select></label><label>Obra<select name="projectId"><option value="">Sem obra específica</option>{(projects??[]).map(project=><option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></label><label>Código da localização padrão<input name="defaultLocationCode" defaultValue="PADRAO"/></label><label>Nome da localização padrão<input name="defaultLocationName" defaultValue="Localização padrão"/></label></div><label>Endereço<input name="address"/></label><button className="button button-primary">Criar depósito</button></form>}</main>;}
