import Link from"next/link";
import{startInventoryStocktake}from"@/app/actions/inventory";
import{InventoryNavigation}from"@/components/inventory/inventory-navigation";
import{requireCapability}from"@/lib/authorization";

export const dynamic="force-dynamic";
function one<T>(value:T|T[]|null|undefined){return Array.isArray(value)?value[0]??null:value??null;}

export default async function NewInventoryStocktakePage({searchParams}:{searchParams:Promise<{warehouseId?:string;error?:string}>}){const query=await searchParams;const context=await requireCapability("estoque","manage");const{data:warehouses}=await context.supabase.from("inventory_warehouses").select("id,name,project_id,projects(code,name)").eq("organization_id",context.organizationId).eq("active",true).order("name");return <main className="content inventory-app"><Link className="back-link" href="/app/estoque/inventarios">← Inventários</Link><section className="page-heading"><div><span className="badge">ESTOQUE · CONTAGEM</span><h1>Novo inventário físico</h1><p>A posição esperada será congelada no início e comparada com a contagem informada.</p></div></section><InventoryNavigation/>{query.error&&<div className="validation blocking">{query.error}</div>}<form action={startInventoryStocktake} className="card card-pad inventory-form"><label>Depósito<select name="warehouseId" defaultValue={query.warehouseId??""} required><option value="">Selecione</option>{(warehouses??[]).map(warehouse=>{const project=one(warehouse.projects);return <option key={warehouse.id} value={warehouse.id}>{warehouse.name}{project?` · ${project.code} · ${project.name}`:" · Geral"}</option>})}</select></label><input type="hidden" name="projectId" value=""/><label>Nome da contagem<input name="name" defaultValue={`Inventário ${new Date().toLocaleDateString("pt-BR")}`} required/></label><label>Observações<textarea name="notes" rows={4}/></label><div className="validation warning"><strong>Atenção:</strong> apenas um inventário pode permanecer ativo por depósito. Movimentos posteriores ao corte não alteram a posição esperada desta contagem.</div><button className="button button-primary">Iniciar contagem</button></form></main>;}
